// Commonly Used Symbols. Printed page XIX.
//
// Glyphs as printed: blackboard bold for the number systems, ⨮ (plus in a
// right half circle, `plus.o.r`) for the semidirect sum of algebras, ⋊
// (`times.r`) for the semidirect product of groups, ⟨S⟩ with angle brackets
// (`chevron.l`, `chevron.r`), ⊂ for inclusion and ≃ (`tilde.eq`) for
// isomorphism; "id" is italic, as everywhere in the book.
#import "../main-defs.typ": *

#source(15, printed: "XIX")
#heading(numbering: none)[Commonly Used Symbols]

// The list is "symbol---meaning", a run-over line hangs.
#set terms(separator: [---], hanging-indent: 2.8em)
/ $ZZ$: ring of integers
/ $QQ, RR, CC$: fields of rational, real and complex numbers respectively
/ $TT$: group of complex numbers with absolute value 1
/ $HH$: skew field of quaternions
/ $AA^n$: $n$-dimensional coordinate affine space
/ $PP^n$: $n$-dimensional coordinate projective space
/ $P(V)$: projective space associated with a vector space $V$
/ $F(V)$: flag manifold (variety) associated with a vector space $V$
/ $V^*$: vector space dual to a vector space $V$
/ $attach(phi, tl: t)$: linear map of dual spaces dual to a linear map $phi$
/ $A^T$: transpose of a matrix $A$
/ $L(V)$: (associative) algebra of linear transformations of a space $V$
/ $GL(V)$: group of invertible linear transformations of $V$
/ $GA(V)$: group of invertible affine transformations of $V$
/ $L_n (K)$: (associative) algebra of $n times n$ matrices over a field $K$
/ $GL_n (K)$: group of invertible $n times n$ matrices over a field $K$
/ $det, tr$: determinant and trace of a matrix or a linear transformation
/ $E$: unit matrix or identity linear transformation
/ $id$: identity map (for nonlinear maps)
/ $plus.o$: sign of the direct sum of vector spaces or algebras
/ $plus.o.r$: sign of the semidirect sum of algebras (the ideal is to the left)
/ $times.r$: sign of the semidirect product of groups (the normal subgroup is to
  the left)
/ $times.o$: sign of the tensor product of vector spaces or algebras
/ $chevron.l S chevron.r$: linear span of a subset $S$ of a vector space;
  subgroup generated by a subset $S$ of a group
/ $subset$: sign of inclusion, possibly identity
/ $tilde.eq$: sign of isomorphism
