// Chapter 1, § 4. The Derived Algebra and the Radical. Printed pages
// 50-58; page 50 is shared with § 3.
#import "main-defs.typ": *
#import "statements.typ": *

== The Derived Algebra and the Radical <sec:derived-algebra-radical>

This section is devoted to the part of the Lie group theory related to the
construction of the derived algebra. We will define here two opposite types of
Lie groups: solvable and semisimple. Any Lie group is constructed from groups of
these two types in the sense that it possesses a connected solvable normal Lie
subgroup the quotient group modulo which is semisimple.

=== The Commutator Group and the Derived Algebra
<ss:commutator-group-derived-algebra>
Recall that the #idx("commutator group")_commutator group_ of a group $G$ is the
subgroup $(G, G) = G'$ generated by all the commutators
$(x, y) = x y x^(-1) y^(-1)$, where $x, y in G$. This subgroup is normal and it
is the smallest normal subgroup the quotient group modulo which is #source(
  66,
)commutative. The #idx("algebra", "derived (of a Lie algebra)")#idx(
  "Lie algebra",
  "derived",
)_derived algebra_ of a Lie algebra $frak(g)$ is the subalgebra
$[frak(g), frak(g)] = frak(g)'$ generated by the brackets $[xi, eta]$, where
$xi, eta in frak(g)$. It is the smallest ideal such that the corresponding
quotient algebra is commutative.

#theorem[For a connected Lie group $G$, $G'$ is a connected virtual Lie subgroup
  with the tangent algebra $frak(g)'$. If $G$ is simply connected then $G'$ is a
  genuine Lie subgroup.] <th:commutator-subgroup-tangent-algebra>

#proof[First, let $G$ be a simply connected Lie group. Consider the quotient
  algebra $frak(g)\/frak(g)'$. It is commutative and therefore may be identified
  with the tangent algebra of a suitable vector Lie group $V$. By
  Theorem~@th:homomorphism-existence-simply-connected the canonical homomorphism
  $phi: frak(g) -> frak(g)\/frak(g)'$ is the differential of a homomorphism
  $f: G -> V$. The kernel of $f$ will be denoted by $H$. It is a normal Lie
  subgroup whose tangent algebra coincides with the kernel of $phi$, i.e. with
  $frak(g)'$. Since $G\/H tilde.equiv V$ is commutative, $H supset G'$. Since
  $G$ and $G\/H$ are simply connected, $H$ is connected
  (Theorem~@th:homotopy-sequence-homogeneous-space).

  Let us show that $G'$ contains a neighbourhood of the unit of $H$: this will
  imply that $G' = H$.

  #problem[For any $xi, eta in frak(g)$ there exists a differentiable $C^1$-path
    $g(t)$ in $G$ defined in a neighbourhood of zero such that

    1) $g(0) = e, g'(0) = [xi, eta]$;

    2) $g(t)$ is a commutator in the group $G$ for any
    $t$.] <pr:commutator-path-tangent-bracket>

  Now choose a basis ${zeta_1, ..., zeta_m}$ in the space $frak(g)'$ over $RR$
  consisting of brackets. Let $g_i (t)$, where $abs(t) < epsilon_i$, be a path
  satisfying the conditions of Problem~@pr:commutator-path-tangent-bracket for
  $[xi, eta] = zeta_i$. Let $U$ be the neighbourhood of zero in $RR^m$ defined
  by the inequalities $abs(t_i) < epsilon_i$. Consider the map
  $
    f: U -> H, quad "where" quad (t_1, ..., t_m) |-> g_1 (t_1) ... g_m (t_m).
  $
  The properties of the paths $g_i (t)$ imply that $d_0 f$ is an isomorphism of
  tangent spaces. Hence, $f(U)$ contains a neighbourhood of the unit of $H$, but
  $f(U) subset G'$ and therefore $G'$ also contains a neighbourhood of the unit
  of $H$.#qed-mark

  For an arbitrary connected Lie group $G$ consider its simply connected
  covering $p: tilde(G) -> G$. By what we have already proved, $tilde(G)'$ is a
  connected Lie subgroup of $tilde(G)$ with the tangent algebra
  $tilde(frak(g))'$. However, it is obvious that $G' = p(tilde(G)')$. It follows
  that $G'$ is a connected virtual Lie subgroup of $G$ with the tangent algebra
  $d p(tilde(frak(g))') = frak(g)'$
  (Problem~@pr:homomorphic-image-virtual-subgroup). The theorem is proved.]

If $G$ is not simply connected then $G'$ might be not a genuine Lie subgroup
(see Exercise~@exc:commutator-not-lie-subgroup).

#problem[If $G$ is a connected Lie group and $frak(g)' = frak(g)$, then
  $G' = G$.] <pr:perfect-algebra-perfect-group>

#problem[$SL_n (K)$ coincides with its commutator
  group.] <pr:special-linear-perfect>

=== Malcev Closures <ss:malcev-closures>
In the tangent algebra of a Lie group may exist subalgebras that do not
correspond to any Lie subgroups. The following example is in a sense a model
one.

#problem[#source(67)The one-dimensional subalgebra of the tangent algebra of the
  Lie group $TT^n$, generated by $(i a_1, ..., i a_n)$, where
  $a_1, ..., a_n in RR$, is the tangent algebra of a Lie subgroup if and only if
  numbers $a_1, ..., a_n$ are
  commensurable.] <pr:torus-subalgebra-commensurable>

Nevertheless, as we will soon see, there is always a Lie subgroup whose tangent
algebra is only “a little bit” larger than the initial subalgebra.

#theorem[Let ${H_nu}$ be an arbitrary collection of Lie subgroups of $G$. Then
  $H = inter.big H_nu$ is also a Lie subgroup and its tangent algebra coincides
  with $frak(h) = inter.big frak(h)_nu$.] <th:intersection-of-lie-subgroups>

#problem[Prove Theorem~@th:intersection-of-lie-subgroups.]
<pr:prove-intersection-of-lie-subgroups>

Now let $frak(h)$ be an arbitrary subalgebra of the tangent algebra $frak(g)$ of
a Lie group $G$. By Theorem~@th:intersection-of-lie-subgroups there exists the
smallest Lie subgroup of $G$ such that its tangent algebra $frak(h)^M$ contains
$frak(h)$. The subalgebra $frak(h)^M$ will be called the #idx(
  "Malcev closure",
)_Malcev closure_ of $frak(h)$.

#theorem(title: [[@bib:Malcev1945a]])[Let $frak(h)$ be a subalgebra of the
  tangent algebra of the Lie group $G$ and $frak(h)^M$ its Malcev closure. Then
  $(frak(h)^M)' = frak(h)'$.] <th:malcev-closure-derived-algebra>

#proof[Apply Problem~@pr:trivial-on-subquotient-subgroup to the adjoint
  representation of $G$ with subspaces $frak(h)$ and $frak(h)'$ serving as $U$
  and $W$, respectively. We see that
  $ H_1 = {g in G: (Ad g - E) frak(h) subset frak(h)'} $
  is a Lie subgroup in $G$ and its tangent algebra is
  $ frak(h)_1 = {xi in frak(g): (ad xi) frak(h) subset frak(h)'}. $
  Clearly, $frak(h) subset frak(h)_1$. Hence, $frak(h)^M subset frak(h)_1$, i.e.
  $[frak(h)^M, frak(h)] subset frak(h)'$. Now apply
  Problem~@pr:trivial-on-subquotient-subgroup again taking $frak(h)^M$ instead
  of $U$. We see that
  $ H_2 = {g in G: (Ad g - E) frak(h)^M subset frak(h)'} $
  is a Lie subgroup and
  $ frak(h)_2 = {xi in frak(g): (ad xi) frak(h)^M subset frak(h)'}. $
  By what we have proved above, $frak(h) subset frak(h)_2$. Hence,
  $frak(h)^M subset frak(h)_2$, meaning that $(frak(h)^M)' subset frak(h)'$.]

#problem[The Malcev closure of an ideal is an
  ideal.] <pr:malcev-closure-of-ideal>

=== Existence of Virtual Lie Subgroups <ss:existence-virtual-lie-subgroups>
Let us prove Theorem~@th:subalgebra-has-virtual-subgroup. Let $frak(h)$ be a
subalgebra of the tangent algebra of a Lie group $G$. Consider its Malcev
closure $frak(h)^M = frak(f)$. By Theorem~@th:malcev-closure-derived-algebra
$frak(f) supset frak(h) supset frak(f)' = frak(h)'$. Let $F$ be a connected Lie
subgroup of $G$ with the tangent algebra $frak(f)$ and $tilde(F)$ its simply
connected covering Lie group. Since $tilde(F)\/tilde(F)'$ is a vector group, it
contains a connected Lie subgroup (a subspace of a vector space) with the
tangent algebra $frak(h)\/frak(h)' subset frak(f)\/frak(f)'$. (We identify the
tangent algebra #source(68)of $tilde(F)$ with $frak(f)$). Therefore, the group
$tilde(F)$ itself contains a connected Lie subgroup $tilde(H)$ with the tangent
algebra $frak(h)$. The image of this subgroup in $F$ is the desired virtual Lie
subgroup of $G$.#qed-mark

During the proof we have actually obtained a description of arbitrary connected
virtual Lie subgroups. Namely, any connected virtual Lie subgroup $H$ of a Lie
group $G$ may be obtained as follows: there exists a connected Lie subgroup $F$
of $G$ and a connected Lie subgroup $tilde(H)$ of the simply connected covering
Lie group $tilde(F)$ containing its commutator subgroup such that
$H = p(tilde(H))$, where $p: tilde(F) -> F$ is the covering homomorphism.
(Clearly, $tilde(H)$ is the simply connected covering Lie group for $H$.)

=== Solvable Lie Groups <ss:solvable-lie-groups>
Recall that the #idx("commutator group", "iterated")_iterated commutator groups_
$G^((k))$ $(k = 0, 1, 2, ...)$ of $G$ are defined by induction:
$ G^((0)) = G, wide G^((1)) = G', wide G^((k+1)) = (G^((k)))'. $
A group $G$ is called #idx("Group", "solvable")_solvable_ if there exists an $m$
such that $G^((m)) = {e}$. Any subgroup and any quotient group of a solvable
group is solvable. Conversely, if a normal subgroup $N subset G$ and the
quotient group $G\/N$ are solvable then so is $G$.

A Lie group is called #idx("Lie group", "solvable")_solvable_ if it is solvable
as an abstract group.

#example[The group $B_n = B_n (K)$ of invertible (upper) triangular $n times n$
  matrices over $K$. Denote by $B_(n, k)$ $(k = 0, 1, ..., n)$ its subgroup
  consisting of the matrices $A = (a_(i j))$ with $a_(i j) = delta_(i j)$ for
  $j - i < k$. Clearly, $B'_n subset B_(n, 1)$ and for $k >= 1$ the map
  $
    A |-> (a_(1, k+1), a_(2, k+2), ..., a_(n-k, n))
  $ <eq:superdiagonal-homomorphism>
  is a homomorphism of $B_(n, k)$ onto the vector group $K^(n-k)$. The kernel of
  this homomorphism coincides with $B_(n, k+1)$. Therefore
  $B'_(n, k) subset B_(n, k+1)$. Since $B_(n, n) = {e}$, we have
  $B_n^((n)) = {e}$.] <exm:triangular-group-solvable>

Similarly, the #idx("algebra", "iterated derived (of a Lie algebra)")#idx(
  "Lie algebra",
  "derived",
  "iterated",
)_iterated derived algebras_ $frak(g)^((k))$ $(k = 0, 1, 2, ...)$ of a Lie
algebra $frak(g)$ are defined by induction as:
$
  frak(g)^((0)) = frak(g), wide frak(g)^((1)) = frak(g)', wide
  frak(g)^((k+1)) = (frak(g)^((k)))'.
$
A Lie algebra $frak(g)$ is called #idx("Lie algebra", "solvable")_solvable_ if
there exists an $m$ such that $frak(g)^((m)) = 0$. Subalgebras and quotient
algebras of a solvable Lie algebra are solvable. Conversely, if an ideal
$frak(n) subset frak(g)$ and the quotient algebra $frak(g)\/frak(n)$ are
solvable then so is $frak(g)$.

#example[The tangent algebra of $B_n (K)$ is the Lie algebra
  $frak(b)_n = frak(b)_n (K)$ of all upper triangular $n times n$ matrices over
  $K$. Let us prove that $frak(b)_n$ is solvable. Let $frak(b)_(n, k)$
  $(k = 0, 1, ..., n)$ be its subalgebra consisting of matrices $X = (x_(i j))$
  with $x_(i j) = 0$ for $j - i < k$. Clearly,
  $frak(b)'_n subset frak(b)_(n, 1)$ and the map~@eq:superdiagonal-homomorphism
  is a homomorphism of $frak(b)_(n, k)$ onto a commutative Lie algebra
  $K^(n-k)$. The kernel of this homomorphism coincides with $frak(b)_(n, k+1)$.
  Therefore $frak(b)'_(n, k) subset frak(b)_(n, k+1)$. Since
  $frak(b)_(n, n) = 0$, we have
  $frak(b)_n^((n)) = 0$.] <exm:triangular-algebra-solvable>

#source(69)The induction shows that the iterated commutator group $G^((k))$ of a
connected Lie group $G$ is its connected virtual Lie subgroup with the tangent
algebra $frak(g)^((k))$. This implies

#theorem[A connected Lie group $G$ is solvable if and only if so is its tangent
  algebra. More precisely, $G^((m)) = {e}$ if and only if
  $frak(g)^((m)) = 0$.] <th:solvable-group-iff-algebra>

#problem[Any nontrivial solvable Lie algebra splits into a semidirect sum of an
  ideal of codimension 1 and a 1-dimensional
  subalgebra.] <pr:solvable-algebra-semidirect-sum>

Applying Problem~@pr:semidirect-sum-integrates and induction in $dim frak(g)$ we
see that for any solvable Lie algebra $frak(g)$ there exists a simply connected
Lie group whose tangent algebra is isomorphic to $frak(g)$. Simultaneously we
establish the following fact.

#problem[Any nontrivial simply connected solvable Lie group decomposes into a
  semidirect product of a normal Lie subgroup of codimension 1 and a
  one-dimensional Lie subgroup (isomorphic to
  $K$).] <pr:simply-connected-solvable-semidirect>

=== Lie's Theorem <ss:lie-theorem>
The most important tool in the study of solvable Lie groups is

#theorem(title: [#idx("Lie’s theorem")Lie's theorem])[Let $R: G -> GL(V)$ be a
  complex linear representation of a connected solvable (real or complex) Lie
  group $G$. There exists a one-dimensional subspace $U subset V$ invariant with
  respect to $R(G)$.] <th:lie-theorem>

Before we prove this theorem let us introduce certain definitions and prove
several simple statements on linear representations of abstract groups.

Let $R: G -> GL(V)$ be a linear representation (over an arbitrary field). For
any character $chi$ of $G$ (see definition of character in
@ss:operations-on-representations) set
$
  V_chi (G) = {v in V: R(g) v = chi(g) v "for all" g in G}.
$ <eq:weight-subspace>
If $V_chi (G) != 0$ then $chi$ is called a #idx(
  "weight of a representation",
)_weight_ of $R$, the subspace $V_chi (G)$ a #idx("weight subspace")_weight
subspace_ and its nonzero elements the #idx("weight vector")_weight vectors_
corresponding to $chi$. In other words, the weights of a representation are the
characters that occur in it as one-dimensional subrepresentations and the weight
vectors are the vectors generating one-dimensional invariant subspaces.

#problem[The weight subspaces corresponding to different weights are linearly
  independent.] <pr:weight-subspaces-independent>

This implies, in particular, that a linear representation may only have a finite
number of weights.

Now let $H$ be a normal subgroup of $G$.

#problem[For any character $chi$ of $H$ and any $g in G$ we have
  $ R(g) V_chi (H) = V_(chi^g) (H), $
  where $chi^g (h) = chi(g^(-1) h g)$ for
  $h in H$.] <pr:normal-subgroup-weights-permuted>

#source(70)Therefore the operators corresponding to elements of $G$ can only
permute weight subspaces of $H$.

_Proof_ of Theorem~@th:lie-theorem will be carried out by induction in $dim G$.
Suppose that $dim G > 0$ and that the theorem holds for groups whose dimension
is less than $dim G$. Passing to the simply connected covering Lie group we can
reduce the proof to the case when $G$ is simply connected. In this case by
Problem~@pr:simply-connected-solvable-semidirect we have
$ G = H times.r P, $
where $H$ is a normal Lie subgroup of codimension 1 and $P$ is a one-dimensional
Lie subgroup.

By inductive hypothesis there exists a one-dimensional subspace of $V$ invariant
with respect to $R(H)$. This means that $V_chi (H) != 0$ for a character $chi$
of $H$. Since the operators $R(g)$, $g in G$, can only permute weight subspaces
of $H$ and since $G$ is connected, then $V_chi (H)$ is invariant with respect to
$R(G)$, hence with respect to $d R(frak(g))$.

Now let $xi$ be a nonzero element of the tangent algebra of $P$ and $U$ a
one-dimensional subspace of $V_chi (H)$ invariant with respect to $d R(xi)$.
Then it is also invariant with respect to $R(P)$, hence with respect to $R(G)$.
The theorem is proved.#qed-mark

#problem(corollary: true)[Under the conditions of the theorem there exists a
  basis of $V$ in which all the operators $R(g)$, $g in G$, are expressed by
  (upper) triangular matrices.] <pr:lie-theorem-triangular-basis>

=== The Radical. Semisimple Lie Groups <ss:radical-semisimple-lie-groups>

#problem[The sum of solvable ideals of a Lie algebra is a solvable
  ideal.] <pr:sum-of-solvable-ideals>

It follows, that in any Lie algebra $frak(g)$ there exists the largest solvable
ideal. It is called the #idx(
  "Radical (of a Lie algebra or a Lie group)",
)_radical_ of $frak(g)$. We will denote it by $rad frak(g)$.

#theorem[In any Lie group $G$ there is the largest connected solvable normal Lie
  subgroup. Its tangent algebra coincides with
  $rad frak(g)$.] <th:radical-of-lie-group>

#proof[Consider the Malcev closure $(rad frak(g))^M$. By
  Theorem~@th:malcev-closure-derived-algebra
  $((rad frak(g))^M)' = (rad frak(g))'$. Hence, $(rad frak(g))^M$ is a solvable
  Lie algebra. By Problem~@pr:malcev-closure-of-ideal $(rad frak(g))^M$ is an
  ideal. Since $rad frak(g)$ is the largest solvable ideal of $frak(g)$, then
  $(rad frak(g))^M = rad frak(g)$. This means that there exists a connected Lie
  subgroup $R subset G$ such that its tangent algebra coincides with
  $rad frak(g)$.

  The definition of $rad frak(g)$ implies that $rad frak(g)$ is invariant with
  respect to all automorphisms of $frak(g)$. Hence, $R$ is invariant with
  respect to all automorphisms of $G$. In particular, $R$ is normal. By
  Theorem~@th:solvable-group-iff-algebra it is solvable.

  Any connected solvable normal Lie subgroup $H subset G$ must be contained in
  $R$ since its tangent algebra $frak(h)$ being a solvable ideal of $frak(g)$ is
  contained in $rad frak(g)$. Thus, $R$ is the largest connected solvable normal
  Lie subgroup of $G$.]

The subgroup satisfying the hypotheses of Theorem~@th:radical-of-lie-group is
called the _radical of the Lie group $G$_. We will denote it by $Rad G$.

#source(71)A Lie group $G$ (a Lie algebra $frak(g)$) is called #idx(
  "Lie algebra",
  "semisimple",
)#idx("Lie group", "semisimple")_semisimple_ if $Rad G = {e}$ (resp.
$rad frak(g) = 0$). Obviously, a Lie group is semisimple if and only if its
tangent algebra is semisimple. For any Lie group $G$ (resp. Lie algebra
$frak(g)$) the quotient group $G\/Rad G$ (resp. the quotient algebra
$frak(g)\/rad frak(g)$) is semisimple.

#problem[A Lie algebra $frak(g)$ is semisimple if and only if it has no nonzero
  commutative ideals.] <pr:semisimple-no-commutative-ideals>

In Chapters~@ch:complex-semisimple-lie-groups and @ch:real-semisimple-groups we
will show that the classical Lie groups $SL_n (K)$, $SO_n (K)$ for $n >= 3$,
$Sp_n (K)$ and several other groups are semisimple. The theory of semisimple Lie
groups is the most difficult and significant part of the Lie group theory.

=== Complexification <ss:complexification-lie-algebras>
Complex Lie algebras have a simpler structure than real ones. Therefore the
usual way to study real Lie algebras is to complexify them. In order to prove
anything in this way we should know which properties of a Lie algebra are
preserved under the complexification. In this section we will prove that
solvability and semisimplicity are among these properties.

Let $V(CC) = V times.o_RR CC$ be the #idx(
  "complexification",
)_complexification_ of a real vector space $V$. Any vector $z in V(CC)$ can be
uniquely presented in the form $z = x + i y$, where $x, y in V$. The vector
$overline(z) = x - i y$ is called the #idx("complex conjugation")_complex
conjugate_ to $z$. The complex conjugation is an antilinear transformation of
the space $V(CC)$. Therefore if $W subset V(CC)$ is a subspace then so is
$overline(W)$.

#problem[A subspace $W subset V(CC)$ is the complexification of a subspace
  $U subset V$ if and only if
  $overline(W) = W$.] <pr:real-subspace-iff-conjugation-stable>

Now let $frak(g)(CC) = frak(g) times.o_RR CC$ be the complexification of a real
Lie algebra $frak(g)$. Clearly, a subspace $frak(h) subset frak(g)$ is a
subalgebra (resp. ideal) if and only if its complexification $frak(h)(CC)$ is a
subalgebra (ideal) of $frak(g)(CC)$. Obviously, the complex conjugation is an
antilinear automorphism of $frak(g)(CC)$.

#problem[$(frak(g)(CC))' = frak(g)'(CC)$]
<pr:derived-algebra-complexification>

This implies that $frak(g)(CC)$ _is solvable if and only if so is_ $frak(g)$.

#problem[$rad frak(g)(CC) = (rad frak(g))(CC)$.] <pr:radical-complexification>

It follows, that $frak(g)(CC)$ _is semisimple if and only if so is_ $frak(g)$.

#exercises[
  #exercise[$(GL_n (K))' = SL_n (K)$.] <exc:general-linear-commutator>

  #exercise[$(upright(O)_n (K))' = SO_n (K)$.] <exc:orthogonal-commutator>

  #exercise[$upright(U)'_n = SU_n$.] <exc:unitary-commutator>

  #exercise[Let $H$ be the Lie group of $3 times 3$ unitriangular real matrices
    and $G = (H times TT)\/N$, where $N$ is the cyclic subgroup generated by
    $ (mat(1, 0, 1; 0, 1, 0; 0, 0, 1), c), wide "where" wide c in TT. $
    If $c$ is an element of infinite order of $TT$ then $G'$ is not a Lie
    subgroup.] <exc:commutator-not-lie-subgroup>

  #exercise[#source(72)A subspace of the tangent algebra of $TT^n$ is the
    tangent space to a Lie subgroup if and only if it is generated by vectors of
    the form $(i a_1, ..., i a_n)$, where
    $a_1, ..., a_n in QQ$.] <exc:torus-rational-subspaces>

  #exercise[Let $frak(a)$ and $frak(b)$ be subalgebras of the tangent algebra of
    a Lie group such that $[frak(a), frak(b)] subset frak(a) inter frak(b)$. Let
    $frak(a)^M$, $frak(b)^M$ be their Malcev closures. Then
    $[frak(a)^M, frak(b)^M] = [frak(a), frak(b)]$. (Here $[frak(a), frak(b)]$ is
    the subspace generated by the brackets $[xi, eta]$, where
    $xi in frak(a), eta in frak(b)$).] <exc:malcev-closures-bracket>

  #exercise[The Malcev closure of a commutative subalgebra is a commutative
    subalgebra.] <exc:malcev-closure-commutative>

  #exercise[If a Lie group (resp. Lie algebra) is not semisimple it has a
    connected commutative normal Lie subgroup (resp. a commutative ideal) of
    positive dimension.] <exc:non-semisimple-commutative-ideal>

  #exercise[Let $R$ be a connected solvable normal Lie subgroup of $G$. If
    $G\/R$ is semisimple then $R = Rad G$.] <exc:radical-characterization>

  #exercise[$SL_n (K)$ is semisimple.] <exc:special-linear-semisimple>

  #exercise[A direct product of semisimple Lie groups is a semisimple Lie
    group.] <exc:product-of-semisimple-groups>

  #exercise[Let $U$ be a subspace of a complex vector space $V$. The radical of
    the Lie group
    $ GL(V; U) = {A in GL(V): A U subset U} $
    consists of all the transformations $A in GL(V; U)$ that act as
    multiplications by scalars on $U$ and on
    $V\/U$.] <exc:radical-subspace-stabilizer>

  #exercise[The radical of a complex Lie group coincides with the radical of
    this group considered as a real Lie
    group.] <exc:radical-complex-group-as-real>

  #exercise[Any nontrivial connected solvable real Lie group has a connected
    normal Lie subgroup of codimension 1.] <exc:solvable-codimension-one-normal>

  #exercise[Let $G$ be a connected solvable real Lie group and $H$ its connected
    solvable normal Lie subgroup of codimension 1. Then $G = H times.r P$, where
    $P$ is a connected one-dimensional Lie
    subgroup.] <exc:codimension-one-normal-complement>
]

#hints[
  #hint[@pr:commutator-path-tangent-bracket][Let $x(t)$ and $y(t)$, where
    $0 <= t < epsilon$, be differentiable paths in $G$ such that
    $x(0) = y(0) = e$, $x'(0) = xi$, $y'(0) = eta$. Then we may take
    $
      g(t) = cases(
        (x(sqrt(t)), y(sqrt(t))) & "for" t >= 0,
        (x(sqrt(abs(t))), y(sqrt(abs(t))))^(-1) & "for" t <= 0.
      )
    $]

  #hint[@pr:special-linear-perfect][Let $E_(i j)$ be a matrix unit, i.e. its
    $(i, j)$-th entry is 1 and the other entries are zeros. Clearly,
    $
      [E_(i i) - E_(j j), E_(i j)] = 2 E_(i j) \
      [E_(i j), E_(j i)] = E_(i i) - E_(j j)
    $
    for $i != j$. This implies that $frak(s l)_n (K)' = frak(s l)_n (K)$, hence
    $SL_n (K)' = SL_n (K)$.]

  #hint[@pr:torus-subalgebra-commensurable][#source(73)If the required Lie
    subgroup exists, it is the image of $RR$ under the homomorphism $RR -> TT^n$
    such that its differential maps 1 into $(i a_1, ..., i a_n)$. This
    homomorphism is of the form
    $ x |-> (e^(i a_1 x), ..., e^(i a_n x)). $
    Further, use Problem~@pr:torus-winding-commensurable.]

  #hint[@pr:prove-intersection-of-lie-subgroups][For a finite number of
    subgroups the statement is just the contents of
    Problem~@pr:intersection-of-two-lie-subgroups. In the general case the
    subalgebra $inter.big frak(h)_nu$ coincides with the intersection of a
    finite number of subalgebras, say $frak(h)_(nu_1), ..., frak(h)_(nu_k)$, and
    by the above it is the tangent algebra of the Lie subgroup
    $hat(H) = H_(nu_1) inter dots.c inter H_(nu_k)$. For any $nu$ the Lie
    subgroup $hat(H) inter H_nu$ has the same tangent algebra as $hat(H)$. Hence
    $hat(H) inter H_nu$ is contained in $hat(H)$ and contains $hat(H)^0$ and
    therefore so is and does $H$. Thus $H$ is a Lie subgroup and its tangent
    algebra coincides with $inter.big frak(h)_nu$.]

  #hint[@pr:malcev-closure-of-ideal][Clearly, if $a$ is an automorphism of the
    Lie group $G$, then $(d a(frak(h)))^M = d a(frak(h)^M)$ for any Lie
    subalgebra $frak(h) subset frak(g)$. In particular,
    $((Ad g) frak(h))^M = (Ad g) frak(h)^M$. Further, use the fact that
    $frak(h)$ is an ideal if and only if $(Ad g) frak(h) = frak(h)$ for any
    $g in G^0$.]

  #hint[@pr:solvable-algebra-semidirect-sum][For an ideal take any subspace of
    codimension 1 containing the derived algebra and for a subalgebra take any
    complementary subspace.]

  #hint[@pr:weight-subspaces-independent][The proof is similar to that of the
    theorem on linear independence of eigensubspaces of a linear operator.]

  #hint[@pr:lie-theorem-triangular-basis][Take a one-dimensional invariant
    subspace $U subset V$ which exists due to the theorem and consider the
    quotient representation of $G$ in $V\/U$. Apply the theorem again to this
    representation, etc.]

  #hint[@pr:semisimple-no-commutative-ideals][Consider the last nonzero iterated
    derived algebra of $rad frak(g)$.]

  #hint[@pr:real-subspace-iff-conjugation-stable][If $overline(W) = W$ then with
    any $z = x + i y$ $(x, y in V)$ the subspace $W$ contains both
    $x = 1/2 (z + overline(z))$ and $y = 1/(2 i) (z - overline(z))$, which means
    that $W$ is the complexification of $U = W inter V$.]

  #hint[@pr:radical-complexification][Notice that $overline(rad frak(g)(CC))$ is
    a solvable ideal of $frak(g)(CC)$ hence is contained in $rad frak(g)(CC)$.]
]
