// Chapter 2, § 1. Affine Algebraic Varieties. Printed pages 59-74.
#import "main-defs.typ": *
#import "statements.typ": *
#import "diagrams/cd.typ": ar, cd
#import "diagrams/21-affine-varieties.typ": factorization, factorization-proof

== Affine Algebraic Varieties <sec:affine-algebraic-varieties>

In subsections~@ss:embedded-affine-varieties–@ss:direct-product-affine-varieties
the ground field $K$ is an arbitrary infinite field.

=== Embedded Affine Varieties <ss:embedded-affine-varieties>
An #idx("submanifold", "algebraic")_algebraic variety_ in $AA^n$ or an #idx(
  "algebraic variety",
  "affine",
  "embedded",
)_embedded affine algebraic variety_ is a subset in $AA^n$ defined by a system
of equations
$ f(X_1, ..., X_n) = 0 wide (f in S), $ <eq:variety-defining-equations>
#source(75)where $S$ is a (not necessarily finite) set of polynomials. An
algebraic variety defined by system~@eq:variety-defining-equations will be
denoted by $M(S)$.

The collection $I$ of polynomials of the form $Sigma g_i f_i$, where
$g_i in K[X_1, ..., X_n]$ and $f_i in S$, is an ideal of the algebra
$K[X_1, ..., X_n]$. It is the smallest ideal that contains $S$. We will say that
the ideal $I$ is _generated by the set $S$_ or that $S$ is a _system of
generators of the ideal $I$_. Evidently, $M(S) = M(I)$.

An algebra is _noetherian_ if one of the following conditions is satisfied

a) each its ideal is finitely generated;

b) any nondescending chain of its ideals $I_1 subset I_2 subset dots.c$
stabilizes, i.e. $I_m = I_(m+1) = dots.c$ for some $m$.

#problem[Conditions a) and b) are
  equivalent.] <pr:noetherian-conditions-equivalent>

#theorem(title: [#idx("Hilbert’s ideal basis theorem")Hilbert’s ideal basis
  theorem])[If $R$ is noetherian then so is $R[X]$. In particular,
  $K[X_1, ..., X_n]$ is noetherian.] <th:hilbert-basis>

_Proof_: see e.g. [@bib:Humphreys1987].

#problem(corollary: true)[Any affine algebraic variety can be determined by a
  finite system of equations.] <pr:finitely-many-equations>

Let $I$ be an ideal of $K[X_1, ..., X_n]$ and $A = K[X_1, ..., X_n]\/I$. The
natural homomorphism of $K[X_1, ..., X_n]$ onto $A$ will be denoted by $pi$; put
$pi(X_i) = x_i$. The algebra $A$ is generated over $K$ by $x_1, ..., x_n$, i.e.
any element of $A$ is presented (in general, non uniquely) as a polynomial in
$x_1, ..., x_n$ with coefficients in $K$. We will express this fact as follows:
$A = K[x_1, ..., x_n]$. Clearly, if $f in I$, then $f(x_1, ..., x_n) = 0$ and
for any homomorphism $phi: A -> K$ we have $f(phi(x_1), ..., phi(x_n)) = 0$.
This means that for any homomorphism $phi: A -> K$ the point
$(phi(x_1), ..., phi(x_n))$ belongs to the variety $M(I)$.

#problem[This correspondence between the homomorphisms $A -> K$ and the points
  of $M(I)$ is one to one.] <pr:points-correspond-to-homomorphisms>

Now let $A = K[x_1, ..., x_n]$ be an algebra generated by its elements
$x_1, ..., x_n$. There is the unique homomorphism $pi: K[X_1, ..., X_n] -> A$
such that $pi(X_i) = x_i$. If $I = ker pi$, then $A = K[X_1, ..., X_n]\/I$. By
Problem~@pr:points-correspond-to-homomorphisms the homomorphisms $A -> K$ are in
one-to-one correspondence with the points of $M(I)$. Thus we may speak about an
_affine algebraic variety defined by an algebra with a fixed finite system of
generators._

Different ideals (algebras) may define the same variety. For example, the ideals
$(X)$ and $(X^2)$ in $K[X]$ define the subvariety in $AA^1$ that consists of the
single point $(0)$. Among all the ideals defining a given variety $M$ there is
the largest one, namely, the ideal $I(M)$ generated by all polynomials that
vanish on $M$.

Let $M subset AA^n$ be an algebraic variety. For any polynomial
$f in K[X_1, ..., X_n]$ denote by $f|_M$ its restriction (as of a function) onto
$M$. The map $f |-> f|_M$ is a homomorphism of $K[X_1, ..., X_n]$ into the
algebra of functions on $M$ and the kernel of this homomorphism is $I(M)$.
Therefore, elements of the algebra
$ K[M] = K[X_1, ..., X_n]\/I(M) $ <eq:coordinate-algebra>
#source(76)may be interpreted as functions on $M$. These functions will be
called _polynomials on $M$_ and the algebra $K[M]$ will be called _the algebra
of polynomials on $M$_ or #idx("algebra", "coordinate")_the coordinate algebra
of $M$._

#problem[Suppose $A = K[x_1, ..., x_n]$ defines a variety $M$. Then there exists
  a unique homomorphism $rho: A -> K[M]$ such that
  $rho(x_i) = X_i|_M$.] <pr:canonical-map-to-coordinate-algebra>

In the sequel, as long as it is clear what $M$ is meant and unless mentioned
otherwise we will write $x_i$ for $X_i|_M$; then $K[M] = K[x_1, ..., x_n]$.

An element $a in A$ is called #idx(
  "Element",
  "nilpotent (of an algebra)",
)_nilpotent_ if $a^k = 0$ for a certain $k$. Clearly, $K[M]$ does not have
nilpotent elements. (When talking about algebras without zero divisors or
nilpotent elements one obviously has in mind nonzero elements.)

Let $L$ be a field extension of $K$. The space $AA^n$ is naturally embedded into
the $n$-dimensional affine space $AA^n (L)$ over $L$. For any algebraic variety
$M subset AA^n$ one may consider the algebraic variety
$ M(L) = {x in AA^n (L): f(x) = 0 "for all" f in I(M)} $
in $AA^n (L)$. Obviously, $M = M(L) inter AA^n$.

=== Morphisms <ss:morphisms-affine-varieties>
A morphism of an algebraic variety $M subset AA^n$ into an algebraic variety
$N subset AA^m$ is any polynomial map $f: M -> N$ i.e. a map that (in
coordinates) may be determined by polynomials. More precisely, it means that
there are polynomials $f_1, ..., f_m in K[X_1, ..., X_n]$ such that the map $f$
transforms a point $x in M$ into the point of the variety $N$ with coordinates
$f_1 (x), ..., f_m (x)$.

As any map, a morphism $f: M -> N$ induces a homomorphism of algebras of
functions defined by the formula
$ (f^* g)(x) = g(f(x)) $ <eq:pullback-of-function>
(Here $g$ is a function on $N$, $x in M$). The definition of the morphism
clearly implies that if $g$ is a polynomial on $N$, then $f^* g$ is a polynomial
on $M$. So we get a homomorphism of algebras: $f^*: K[N] -> K[M]$.

#problem[For any algebra homomorphism $phi: K[N] -> K[M]$ there exists a unique
  morphism $f: M -> N$ such that
  $f^* = phi$.] <pr:morphisms-from-algebra-homomorphisms>

Thus, to define a morphism of embedded affine algebraic varieties is the same as
to define a homomorphism of algebras of polynomials on these varieties.

Clearly, the product $g f$ of morphisms $f: M -> N$ and $g: N -> P$ is a
morphism and $(g f)^* = f^* g^*$. A morphism $f: M -> N$ is called an
_isomorphism_ if there exists an inverse morphism $f^(-1): N -> M$, i.e. if $f$
is bijective and the inverse map is also a polynomial one. This is equivalent to
the fact that $f^*$ is an isomorphism of algebras.

The class of isomorphic embedded affine algebraic varieties is called an
(_abstract_) #idx("algebraic variety", "affine")_affine algebraic variety_ (or,
in short, _affine variety_) and its representatives will be called _embeddings_
of this variety into the affine space, or #idx("model")_models._ Practically, an
affine variety is identified with one of its models (always having in mind,
however, the possibility to pass to any other model).

#source(77)A #idx("polynomial on an affine variety")_polynomial on an affine
variety_ is a function which is a polynomial on a model of this variety (it does
not matter on which one). The polynomials on an affine variety $M$ constitute
the algebra denoted by $K[M]$. Similarly, a _morphism_ or a _polynomial map of
affine varieties_ is a map which is a morphism of their models (it does not
matter of which ones).

By Problem~@pr:points-correspond-to-homomorphisms there is a one-to-one
correspondence between the points of an affine variety $M$ and algebra
homomorphisms of $K[M]$ into $K$. Explicitly, to each point $x in M$ the
homomorphism $phi_x$ corresponds which assigns to each polynomial $f in K[M]$
its value at $x$:
$ phi_x: f |-> f(x) wide (f in K[M]). $ <eq:evaluation-homomorphism>

It is clear from the above that to determine an affine variety $M$ is the same
as to determine the algebra $K[M]$ and to determine an embedding of $M$ in an
affine space is the same as to choose a system of generators in the algebra
$K[M]$. To determine a morphism of affine varieties is the same as to determine
a homomorphism of their polynomial algebras. This makes it principally possible
to translate any statement about affine varieties from the geometric language
into the algebraic one and, the other way around, to translate statements on
polynomial algebras into the geometric language.

Thus, the question arises what are the algebras that are algebras of polynomials
on affine varieties?

An exact answer to this question in the case of an algebraically closed $K$ will
be given in n.~@ss:hilbert-nullstellensatz. For the time being we can say that
they can only be finitely generated algebras without nilpotent elements. In
algebraic geometry more general geometric objects (affine schemes) are also
considered which correspond to arbitrary finitely generated algebras. However,
for our purposes affine varieties in the above “naive” sense will do.

Let $L$ be a field extension of $K$. Clearly, any morphism $M -> N$ of embedded
affine varieties extends to a morphism $M(L) -> N(L)$ determined by the same
polynomials. Therefore we may speak about an abstract affine variety $M(L)$ over
$L$ determined by an abstract affine variety $M$ over $K$ and about an embedding
$M subset M(L)$.

=== Zariski Topology <ss:zariski-topology>
Let us consider algebraic varieties as _closed subsets_ of $AA^n$.

#problem[This system of closed subsets determines a topology in $AA^n$ (i.e. the
  intersection of closed subsets and the union of a finite number of closed
  subsets are closed).] <pr:zariski-topology-axioms>

This topology in $AA^n$ is called the #idx("Zariski topology")_Zariski
topology._ Clearly, a point is closed in the Zariski topology.

The Zariski topology of $AA^n$ induces a topology on any algebraic variety
$M subset AA^n$ which is called the _Zariski topology_ on $M$. According to this
definition the closed subsets are distinguished in $M$ by systems of equations
of the form $f(x) = 0$, where $f in K[M]$. In particular, the Zariski topology
on $M$ is defined #source(78)by $K[M]$, and that is why we may speak about the
_Zariski topology_ on an abstract affine variety. Clearly, morphisms of affine
varieties are continuous in Zariski topology. Closed subsets $N$ of an affine
variety $M$ are canonically endowed with an affine variety structure so that
$ K[N] = K[M]\/I_M (N), $
where $I_M (N)$ is the ideal of $K[M]$ consisting of the polynomials that vanish
on $N$.

Notice that the Zariski topology on $AA^(n+m)$ does not coincide with the direct
product topology on $AA^n times AA^m$ (e.g. the set in $AA^2$ determined by the
equation $X_1 = X_2$ is closed but it is not closed in $AA^1 times AA^1$).

In the sequel, unless otherwise stated, all the topological terms, excluding
connectedness and simple connectedness are referred to the Zariski topology.

The space $AA^n times AA^m$ is supposed to be endowed with the Zariski topology
of the space $AA^(n+m)$.

A topological space $X$ is #idx("space", "noetherian topological")_noetherian_
if it satisfies the descending chain condition for closed subsets.

#problem[A subspace of a noetherian space is
  noetherian.] <pr:noetherian-subspace>

#problem[The space $AA^n$ endowed with the Zariski topology is a noetherian
  topological space.] <pr:affine-space-noetherian>

This implies that any affine variety is a noetherian topological space.

A topological space $M$ is _irreducible_ if it is nonempty and one of the
following three conditions is satisfied:

a) any nonempty open set is dense in $M$;

b) any two nonempty open sets intersect;

c) it is impossible to present $M$ as a union of two of its proper closed
subsets.

#problem[Prove the equivalence of these
  conditions.] <pr:irreducibility-conditions-equivalent>

#theorem[Any noetherian topological space $M$ can be presented as a union of a
  finite number of closed irreducible subsets $M_i$, so that
  $M_i subset.not M_j$ for $i != j$. This decomposition is unique up to a
  renumbering of the $M_i$.] <th:irreducible-decomposition>

The subsets $M_i$ defined in Theorem~@th:irreducible-decomposition are called
#idx(
  "component",
  "irreducible (of a topological space)",
)_irreducible components_ of $M$.

#problem[Prove
  Theorem~@th:irreducible-decomposition.] <pr:prove-irreducible-decomposition>

#problem[An affine variety $M$ is irreducible if and only if $K[M]$ does not
  have zero divisors. More precisely, zero divisors in $K[M]$ are the
  polynomials which vanish on an irreducible component of $M$. In particular,
  $AA^n$ is irreducible.] <pr:irreducible-iff-integral-domain>

The _closure_ of a subset $M$ in a topological space will be denoted by
$overline(M)$.

#problem[Let $M$ be a subset of a noetherian topological space. If
  $M = union.big_i M_i$ is the decomposition of $M$ into irreducible components,
  then $overline(M) = union.big_i overline(M)_i$ is the decomposition of
  $overline(M)$ into irreducible components. In particular, $M$ is irreducible
  if and only if so is $overline(M)$.] <pr:closure-irreducible-components>

#source(79)Let $M$ be an affine variety. The open subsets of the form
$ M_h = {x in M: h(x) != 0} wide (h in K[M]) $
are called #idx("subset", "principal open")_principal open subsets_ of $M$.
Clearly,
$ M_(h_1) inter M_(h_2) = M_(h_1 h_2) $
It follows from Problem~@pr:irreducible-iff-integral-domain that $M_h$ is dense
in $M$ if and only if $h$ is not a zero divisor in $K[M]$.

#problem[The principal open subsets of an affine variety constitute a base of
  the Zariski topology (i.e. any open subset is a union of principal open
  subsets).] <pr:principal-open-subsets-base>

If $h in K[M]$ is not a zero divisor then the elements of
$K[M][1\/h] subset Q K[M]$ can be naturally considered as functions on $M_h$
since for $x in M_h$ the homomorphism~@eq:evaluation-homomorphism uniquely
extends to a homomorphism $K[M][1\/h] -> K$. On the other hand, for
$x in.not M_h$ such an extension is clearly impossible. This means that $M_h$
can be considered as an affine variety with the polynomial algebra
$ K[M_h] = K[M][1/h]. $
If $h$ is a zero divisor and $M'$ is the union of irreducible components of $M$
on which $h$ does not vanish identically then $M_h = M'_(h')$, where
$h' = h|_(M') in K[M']$. Since $h'$ is not a zero divisor in $K[M']$, then $M_h$
can be considered as an affine variety with the polynomial algebra
$K[M_h] = K[M'][1\/h']$. Keeping the above in mind, we will speak from now on
about principal open subsets of affine varieties as about affine varieties.

Let $L$ be a field extension of $K$.

#problem[The Zariski topology on $AA^n$ coincides with the topology induced by
  the Zariski topology on $AA^n (L)$. The closure in $AA^n (L)$ of any algebraic
  variety $M subset AA^n$ coincides with $M(L)$ and
  $I(M(L)) = L I(M)$.] <pr:field-extension-zariski-closure>

=== The Direct Product <ss:direct-product-affine-varieties>
Let $M$ and $N$ be algebraic varieties in $AA^n$ and $AA^m$, respectively. Then
$M times N$ is an algebraic variety in $AA^n times AA^m = AA^(n+m)$.

#problem[If $M$ and $N$ are irreducible then so is
  $M times N$.] <pr:product-of-irreducible-varieties>

In order to describe the polynomial algebra on $M times N$ it is necessary to
introduce the notion of the tensor product of algebras. The _tensor product
$A times.o B$ of algebras $A$_ and $B$ is the tensor product of the vector
spaces $A$ and $B$ with the multiplication
$ (a_1 times.o b_1)(a_2 times.o b_2) = a_1 a_2 times.o b_1 b_2. $
The maps $iota_A: a |-> a times.o 1$ and $iota_B: b |-> 1 times.o b$ determine
natural embeddings of algebras $A$ and $B$ into $A times.o B$.

#source(80)The tensor product of algebras is characterized by the following
universality condition: for any algebra $C$ and algebra homomorphisms
$phi: A -> C$ and $psi: B -> C$ there exists a unique homomorphism
$omega: A times.o B -> C$ such that the diagram
$
  #cd(
    (T: (0, 1, $A times.o B$), A: (1, 0, $A$), B: (1, 2, $B$), C: (2, 1, $C$)),
    (
      ar("A", "T", label: $iota_A$),
      ar("B", "T", label: $iota_B$, side: "right"),
      ar("T", "C", label: $omega$),
      ar("A", "C", label: $phi$, side: "right"),
      ar("B", "C", label: $psi$),
    ),
    column: 17mm,
    row: 10mm,
  )
$
commutes. This homomorphism is defined by the formula
$ omega(a times.o b) = phi(a) psi(b). $
When $omega$ is an isomorphism, we say that $C$ is the tensor product of $A$ and
$B$ with respect to homomorphisms $phi$ and $psi$. If it is clear which
homomorphisms $phi$ and $psi$ we have in mind, we write $C = A times.o B$. For
example
$
  K[X_1, ..., X_n, Y_1, ..., Y_m]
  = K[X_1, ..., X_n] times.o K[Y_1, ..., Y_m].
$

Let $M subset AA^n$ and $N subset AA^m$ be algebraic varieties. Put $pi_M$ and
$pi_N$ for projections of $M times N$ onto $M$ and $N$, respectively.

#problem[$K[M times N] = K[M] times.o K[N]$ with respect to homomorphisms
  $pi_M^*$ and $pi_N^*$. The ideal $I(M times N)$ of the algebra
  $K[X_1, ..., X_n, Y_1, ..., Y_m]$ is generated by the ideals $I(M)$ and $I(N)$
  of the algebras $K[X_1, ..., X_n]$ and $K[Y_1, ..., Y_m]$ naturally embedded
  into $K[X_1, ..., X_n, Y_1, ..., Y_m]$.] <pr:coordinate-algebra-of-product>

In the sequel we will identify the algebras $K[M times N]$ and
$K[M] times.o K[N]$ having in mind the isomorphism constructed in
Problem~@pr:coordinate-algebra-of-product. Under such an identification an
element $f times.o g in K[M] times.o K[N]$ is presented as the function on
$M times N$ defined by the formula
$ (f times.o g)(x, y) = f(x) g(y). $

An important corollary of Problem~@pr:coordinate-algebra-of-product: The
polynomial algebra on $M times N$ is defined by polynomial algebras on $M$ and
$N$, hence does not depend on embeddings of $M$ and $N$ into affine spaces. This
enables us to define the #idx(
  "product",
  "direct",
  "of affine varieties",
)_direct product of abstract affine varieties $M$_ and $N$ as the affine variety
$M times N$ whose model is the direct product of any models of $M$ and $N$.

It also follows from Problem~@pr:coordinate-algebra-of-product that
$(M times N)(L) = M(L) times N(L)$ for any field extension $L$ of $K$.

=== Homomorphism Extension Theorems <ss:homomorphism-extension-theorems>
From here and till the end of the chapter
(subsections~@ss:analytic-structure-of-varieties–@ss:real-forms-of-varieties
excluded) we will assume that $K$ is algebraically closed.

Suppose $A$ is a subalgebra of $B$. For any subset $U subset B$ put $A[U]$ (or
$A[u_1, ...]$ if $U = {u_1, ...}$) for the subalgebra in $B$ generated by the
set $U$ over $A$, i.e. for #source(81)the collection of all elements of $B$
presentable as polynomials in elements of $U$ with coefficients in $A$. If
$A[U] = B$ we will say that $U$ is a #idx("system of generators")_system of
generators of the algebra $B$ over $A$_ (do not confuse with the notion of
generators of an ideal!) The algebra $B$ is called _finitely generated over
$A$_ if it has a finite number of generators over $A$. Clearly, if $B$ is
finitely generated over $K$ then so it is over $A$.

Algebras finitely generated over $K$ will be simply called _finitely generated._

Suppose $B$ is without zero divisors. An element $b in B$ is called _algebraic
over $A$_ if there is a nonzero polynomial $f in A[X]$ such that $f(b) = 0$;
otherwise $b$ is called _transcendental_ (_over $A$_). If $b$ is transcendental
over $A$, then $A[b] tilde.equiv A[X]$. An algebra $B$ is called an _algebraic
extension_ of $A$ if any of its elements is algebraic over $A$. It is convenient
to introduce the quotient field $Q B$ into which the algebra $B$ and the field
$Q A$ are isomorphically embedded.

#problem[An element $b in B$ is algebraic over $A$ if and only if $Q A[b]$ is a
  finite-dimensional vector space over
  $Q A$.] <pr:algebraic-iff-finite-dimensional>

#problem[If $B = A[b_1, ..., b_n]$, where $b_1, ..., b_n$ are algebraic over
  $A$, then $B$ is an algebraic extension of
  $A$.] <pr:generated-by-algebraic-is-algebraic>

#theorem[Suppose $B$ is an algebra without zero divisors finitely generated over
  its subalgebra $A$. Then for any nonzero element $b in B$ there exists a
  nonzero element $a in A$ such that any homomorphism $phi: A -> K$ that does
  not annihilate $a$ extends to a homomorphism $psi: B -> K$ which does not
  annihilate $b$.] <th:homomorphism-extension-nonvanishing>

#problem[Prove Theorem~@th:homomorphism-extension-nonvanishing when $B = A[u]$,
  where $u$ is transcendental over $A$.] <pr:extension-transcendental-generator>

#problem[Prove Theorem~@th:homomorphism-extension-nonvanishing when $B = A[u]$,
  where $u$ is algebraic over $A$.] <pr:extension-algebraic-generator>

#problem[Prove Theorem~@th:homomorphism-extension-nonvanishing.]
<pr:prove-homomorphism-extension>

#corollary[If $B$ is a finitely generated algebra without zero divisors then for
  any nonzero $b in B$ there exists a homomorphism $psi: B -> K$ which does not
  annihilate $b$.]

#theorem[Let $char K = 0$. Suppose $B$ is a finitely generated algebra without
  zero divisors and $A$ is its finitely generated subalgebra. If there exists a
  nonzero element $b in B$ such that any homomorphism $A -> K$ has no more than
  one extension to a homomorphism $B -> K$ which does not annihilate $b$, then
  $B subset Q A$.] <th:unique-extension-in-fraction-field>

#problem[Prove Theorem~@th:unique-extension-in-fraction-field.]
<pr:prove-unique-extension-fraction-field>

=== The Image of a Dominant Morphism <ss:image-dominant-morphism>
A morphism $f: M -> N$ of irreducible affine varieties is called #idx(
  "morphism",
  "dominant",
)_dominant_ if $overline(f(M)) = N$.

#problem[A morphism $f$ is dominant if and only if the corresponding algebra
  homomorphism $f^*: K[N] -> K[M]$ is
  injective.] <pr:dominant-iff-comorphism-injective>

A dominant morphism may be not surjective. For instance let
$M = {(X_1, X_2) in AA^2: X_1 X_2 = 1}$, $N = AA^1$ and
$f: (X_1, X_2) |-> (X_1)$; then $f(M) = AA^1 without {0}$. Nevertheless, the
image of a dominant morphism is sufficiently large as it is shown by the
following theorem.

#source(82)A subset of an irreducible topological space is called #idx(
  "subset",
  "épais",
)_épais_ if it contains a nonempty open subset. Clearly, any épais subset is
dense. The intersection of a finite number of épais subsets is épais itself.

#theorem[Let $f: M -> N$ be a dominant morphism of irreducible affine varieties.
  The image $f(M_0)$ of any épais subset $M_0 subset M$ is an épais subset in
  $N$.] <th:dominant-morphism-image-epais>

#proof[It suffices to prove that the image of any nonempty principal open subset
  of $M$ contains a nonempty principal open subset of $N$. This is the geometric
  equivalent of Theorem~@th:homomorphism-extension-nonvanishing applied to
  $A = K[N]$ and $B = K[M]$ if we identify the elements of $K[N]$ with their
  images under $f^*$.

  Indeed, the points of $M$ and $N$ can be considered as homomorphisms into $K$
  of $K[M]$ and $K[N]$ respectively. Then $f$ can be viewed as a restriction
  onto $K[N]$ of the homomorphisms $K[M] -> K$. By
  Theorem~@th:homomorphism-extension-nonvanishing for any nonzero $g in K[M]$
  there exists a nonzero $h in K[N]$ such that any homomorphism $K[N] -> K$ that
  does not annihilate $h$ extends to a homomorphism $K[M] -> K$ that does not
  annihilate $g$; but this means that $f(M_g) supset N_h$.]

=== Hilbert’s Nullstellensatz <ss:hilbert-nullstellensatz>
An ideal $I$ of $A$ different from $A$ is _prime_ if $A\/I$ does not have zero
divisors. This means that if $a b in I$ then either $a in I$ or $b in I$. For
example, in $K[X]$, the ideal generated by a nonzero polynomial $f$ is prime if
and only if $f$ is a first degree polynomial.

Clearly, a prime ideal contains all nilpotent elements. The set of all nilpotent
elements of $A$ is an ideal called the _radical_ of $A$ and is denoted by $R A$.

#theorem[The radical of an algebra $A$ coincides with the intersection of all
  the prime ideals of $A$.] <th:nilradical-intersection-of-primes>

Proof see e.g. in [@bib:Humphreys1987], [@bib:Shafarevich1974].

#problem[The kernel of the homomorphism $rho$ defined in
  Problem~@pr:canonical-map-to-coordinate-algebra equals
  $R A$.] <pr:kernel-of-restriction-is-nilradical>

In particular, a finitely generated algebra $A$ coincides with the polynomial
algebra on the affine variety that $A$ defines if and only if $A$ has no nonzero
nilpotent elements.

A reformulation of Problem~@pr:kernel-of-restriction-is-nilradical is

#theorem(title: [#idx("Hilbert’s Nullstellensatz")Hilbert’s Nullstellensatz
  which in German means ‘theorem on zeroes’])[Suppose $M = M(I) subset AA^n$ is
  the variety defined by an ideal $I subset K[X_1, ..., X_n]$. For any
  $f in I(M)$ there exists $k$ such that
  $f^k in I$.] <th:hilbert-nullstellensatz>

Applying this theorem to $f = 1$ we obtain

#corollary[If $M(I) = emptyset$ then $I = K[X_1, ..., X_n]$.]

#problem[Let $M$ be an affine variety and $I$ an ideal of $K[M]$. If there is no
  point of $M$ at which all the polynomials of $I$ vanish, then
  $I = K[M]$.] <pr:weak-nullstellensatz-on-variety>

#problem[Suppose an affine variety $M$ is presented in the form of a union of
  non-intersecting closed subsets $M_1, ..., M_q$. Then the homomorphism
  $K[M] -> K[M_1] times dots.c times K[M_q]$, $f |-> (f|_(M_1), ..., f|_(M_q))$
  is an isomorphism.] <pr:disjoint-union-coordinate-algebra>

#source(83)In other words, any function on $M$ whose restrictions to
$M_1, ..., M_q$ are polynomials is a polynomial itself.

=== Rational Functions <ss:rational-functions>
Let $M$ be an affine variety. The algebra $Q K[M]$ is called the #idx(
  "algebra of rational functions",
)_algebra of rational functions on $M$_ and is denoted by $K(M)$.
Problem~@pr:irreducible-iff-integral-domain shows that if $M$ is irreducible
then $K(M)$ is a field. In particular, $K(AA^n) = K(X_1, ..., X_n)$ is the field
of rational functions in $X_1, ..., X_n$.

The elements of $K(M)$ are called _rational functions on $M$._ A function
$f in K(M)$ is _defined at a point_ $x in M$ if $f$ can be presented in the form
of a ratio $g\/h$, where $g, h in K[M]$, such that $h(x) != 0$. In this case the
element $g(x)\/h(x)$ is called the _value of $f$_ at $x$ and is denoted by
$f(x)$. The value does not depend on the choice of representation of $f$ in the
form of such a ratio.

The set of all points $x in M$ where a rational function $f in K(M)$ is defined
is called the _domain_ of $f$. This set will be denoted by $D_f$.

The following properties of rational functions are obvious:

(R1) the domain $D_f$ of $f in K(M)$ is a dense open subset in $M$;

(R2) the map $f: D_f -> K$ is continuous ($K$ is considered here as $AA^1$ with
the Zariski topology);

(R3) $f$ as an element of $K(M)$, is uniquely determined by its restriction to
any dense open subset;

(R4) the operations on the elements of $K(M)$ coincide with the usual operations
on functions where these functions are defined.

Let $f$ be a rational function on $M$. The denominators of all possible
presentations of $f$ in the form of a ratio of two polynomials are precisely the
nondivisors of zero contained in the ideal
$ I_f = {h in K[M]: f h in K[M]} $

#problem[The ideal $I_f$ is generated by the nondivisors of zero contained in
  it. The domain of $f$ is the complement of the variety of zeros of this
  ideal.] <pr:denominator-ideal-and-domain>

#problem[Any rational function defined at all points of $M$ is a polynomial,
  i.e. belongs to $K[M]$.] <pr:everywhere-defined-is-polynomial>

#problem[Any rational function defined at all points of a principal open subset
  $M_h$, where $h in K[M]$ is a nondivisor of zero, can be presented in the form
  $g\/h^k$ ($g in K[M]$), i.e. belongs to
  $K[M][1\/h] subset K(M)$.] <pr:rational-functions-on-principal-open>

Let $M'$ be the union of some irreducible components of $M$. Since the
restriction homomorphism $K[M] -> K[M']$ maps the nondivisors of zero into
nondivisors of zero, it extends to a homomorphism $K(M) -> K(M')$. The image of
a rational function $f in K(M)$ under this homomorphism is called its
_restriction_ to $M'$ and is denoted by $f|_(M')$.

#problem[If $f$ is defined at $x in M'$ then so is $f|_(M')$ and
  $f|_(M') (x) = f(x)$.] <pr:restriction-preserves-values>

Let $M''$ be the union of the irreducible components of $M$ which do not occur
in $M'$.

#problem[#source(84)If $f|_(M')$ is defined at $x in M' without M''$ then so is
  $f$.] <pr:definedness-from-restriction>

#problem[Let $M = M_1 union dots.c union M_q$ be the decomposition of $M$ into
  irreducible components. Then the homomorphism
  $
    K(M) -> K(M_1) times dots.c times K(M_q), f |-> (f|_(M_1), ..., f|_(M_q))
  $
  is an isomorphism.] <pr:rational-functions-product-components>

=== Rational Maps <ss:rational-maps>
A #idx("map", "rational")_rational map_ of an affine variety $M$ into $AA^m$ is
a map of the form
$ f: x |-> (f_1 (x), ..., f_m (x)), $ <eq:rational-map-coordinates>
where $f_1, ..., f_m in K(M)$. The map $f$ is considered as _defined at a point
$x in M$_ if all the functions $f_1, ..., f_m$ are defined at this point.

#problem[The domain of a rational map is an open dense subset of $M$. A rational
  map is continuous on its domain.] <pr:rational-map-domain-open-dense>

Now let $N$ be another affine variety. Considering $N$ as embedded into $AA^m$
define a _rational map_ $f: M -> N$ as a rational map $f: M -> AA^m$ such that
$f(M) subset N$.

#problem[The notion of a rational map into a variety $N$ does not depend on the
  embedding of $N$ into an affine
  space.] <pr:rational-map-embedding-independent>

Under the inversely directed homomorphism of the algebras of functions defined
by formula~@eq:pullback-of-function the coordinate functions are mapped into the
functions $f_i$ while the polynomials on $N$ are mapped into the rational
functions on $M$. Thus, a rational map $f: M -> N$ induces a homomorphism
$f^*: K[N] -> K(M)$. Formula~@eq:pullback-of-function means here that if $f$ is
defined at $x$ then so is $f^* g$ and @eq:pullback-of-function holds.

#problem[For any homomorphism $phi: K[N] -> K(M)$ there is a unique rational map
  $f: M -> N$ such that $f^* = phi$.] <pr:rational-maps-from-homomorphisms>

Thus, to define a rational map of a variety $M$ into a variety $N$ is the same
as to define an algebra homomorphism $K[N] -> K(M)$. If the image of $K[N]$
under this homomorphism is contained in $K[M]$, then the corresponding rational
map is a morphism.

Suppose that a rational map $f: M -> N$ is defined by
formula~@eq:rational-map-coordinates and $h in K[M]$ is a polynomial which is
not a zero divisor in $K[M]$ such that $h f_i in K[M]$ for $i = 1, ..., m$ (e.g.
we may take for $h$ the product of denominators of some presentations of the
functions $f_i$ in the form of a ratio of polynomials). Then
$f_i in K[M][1\/h]$, i.e. the functions $f_i$, where $i = 1, ..., m$, are
polynomials on the affine variety $M_h$ (see
Problem~@pr:restriction-preserves-values). Thus the restriction of a rational
map to a suitable dense principal open subset is a morphism.

A rational map $f: M -> N$ of irreducible affine varieties is called #idx(
  "map",
  "rational",
  "dominant",
)_dominant_ if $overline(f(M)) = N$.

#problem[A rational map $f$ is dominant if and only if $f^*$ is injective. If
  $f$ is dominant then $f^*$ extends to an algebra homomorphism $K(N) -> K(M)$
  (also denoted by $f^*$).] <pr:dominant-rational-map-criterion>

#source(85)Formula~@eq:pullback-of-function is valid for any rational function
$g$ defined at the point $f(x)$.

The superposition of a dominant rational map $f: M -> N$ and a rational map
$g: N -> P$ can be defined as a rational map $g f: M -> P$ such that
$(g f)^* = f^* g^*$.

Clearly, if $f$ is defined at $x in M$ and $g$ is defined at $f(x) in N$ then
$g f$ is defined at $x$ and $(g f)(x) = g(f(x))$.

Note that the map $g f$ may be defined not only at points satisfying the above
condition. For example, let $M = N = P = AA^1$ and $f = g: (X) |-> (1\/X)$; then
$g f$ is the identity morphism which is defined everywhere, whereas $f$ is not
defined at 0.

=== Factorization of a Morphism <ss:factorization-of-morphism>

#theorem[Let $char K = 0$, let $M, N, P$ be irreducible affine varieties and let
  $f: M -> N$, $h: M -> P$ be dominant morphisms. If $f(x') = f(x'')$ implies
  $h(x') = h(x'')$ for any points $x', x''$ of an épais subset $M_0 subset M$,
  then there exists a rational map $g: N -> P$ such that
  $h = g f$.] <th:morphism-factors-through-dominant>

The situation is illustrated by the following commutative diagram
$ #factorization $

#proof[First consider a particular case, when $P = M$ and $h = id$. In this case
  the condition of the theorem means that $f$ is one-to-one on $M_0$. Let $M_b$,
  where $b in K[M]$, $b != 0$, be a principal open subset contained in $M_0$.

  The same arguments as in the proof of
  Theorem~@th:dominant-morphism-image-epais yield the following algebraic
  formulation of the bijectiveness of $f$ on $M_b$: any homomorphism of
  $f^* K[N] tilde.equiv K[N]$ into $K$ extends in no more than one way to a
  homomorphism $K[M] -> K$ that does not annihilate $b$. By
  Theorem~@th:unique-extension-in-fraction-field this implies that
  $K[M] subset f^* K(N)$. In other words, there is a homomorphism
  $phi: K[M] -> K(N)$ such that $f^* phi = id$. The rational map $g: N -> M$
  defined by this homomorphism is the required inverse of $f$.

  In general case, consider an auxiliary rational map
  $ l: M -> N times P, x |-> (f(x), h(x)) $
  The closure of its image will be denoted by $L$. Furthermore, let $p_1$ and
  $p_2$ be the restrictions onto $L$ of the projections of the product
  $N times P$ onto the first and second factor, respectively. The conditions of
  the theorem imply that $p_1$ is a bijection on the épais subset
  $l(M_0) subset L$. By the above there exists a rational map $k: N -> L$
  inverse to $p_1$. The map $g = p_2 k$ is the one sought for. Proof is
  illustrated by the following commuting diagram:
  #source(86)
  $ #factorization-proof $]

Note that the assumption $char K = 0$ is essential. Indeed, suppose that
$char K = p > 0$. Then the morphism $f: AA^1 -> AA^1$, $(X) |-> (X^p)$ is a
bijection but the inverse map is not rational.

#exercises[
  The ground field $K$ is assumed to be algebraically closed.

  #exercise[Let $M$ and $N$ be algebraic varieties in $AA^n$ and $N subset M$.
    Then $K[N]$ is a quotient algebra of
    $K[M]$.] <exc:subvariety-quotient-algebra>

  #exercise[What is the Zariski topology in
    $AA^1$?] <exc:zariski-topology-affine-line>

  #exercise[The Zariski topology in $AA^n$ is not the Hausdorff
    one.] <exc:zariski-not-hausdorff>

  #exercise[Any open covering of a noetherian topological space has a finite
    subcovering.] <exc:noetherian-space-quasi-compact>

  #exercise[Suppose $f = p_1^(k_1) ... p_s^(k_s)$ is a decomposition of a
    polynomial $f in K[X_1, ..., X_n]$ into irreducible factors. Then
    $M(f) = union.big M(p_i)$ is the decomposition of the variety $M(f)$ into
    irreducible components.] <exc:hypersurface-irreducible-components>

  #exercise[Give an example of two nonisomorphic algebras that define the same
    algebraic variety in $AA^n$.] <exc:nonisomorphic-algebras-same-variety>

  #exercise[An affine algebraic variety defined by a finite-dimensional algebra
    consists of a finite number of
    points.] <exc:finite-dimensional-algebra-finite-set>

  #exercise[A finitely generated algebra which is a field coincides with
    $K$.] <exc:finitely-generated-field-equals-k>

  #exercise[Suppose $A$ is a finitely generated algebra, $I$ its maximal ideal.
    Then $A\/I tilde.equiv K$.] <exc:maximal-ideal-residue-field>

  #exercise[There is a one-to-one correspondence between the points of an affine
    algebraic variety $M$ defined by a finitely generated algebra $A$ and the
    maximal ideals of this algebra: to a point $x in M$ the kernel of the
    homomorphism $phi_x: A -> K$ corresponds.] <exc:points-maximal-ideals>

  #exercise[If two finitely generated algebras do not have zero divisors (or
    nilpotent elements) then so does their tensor product. (Prove
    geometrically.)] <exc:tensor-product-domain-reduced>

  #exercise[The radical of a finitely generated algebra coincides with the
    intersection of all its maximal ideals.

    An ideal $I$ of an algebra $A$ is called a _radical ideal_ if $f^m in I$
    implies $f in I$.] <exc:nilradical-intersection-of-maximal>

  #exercise[Any radical ideal of a finitely generated algebra is the
    intersection of a finite number of prime
    ideals.] <exc:radical-ideal-prime-decomposition>

  #exercise[Find the domain of the rational function $x_1\/x_3$ on the algebraic
    variety in $AA^4$ defined by the equation
    $X_1 X_4 = X_2 X_3$.] <exc:rational-function-domain-quadric>

  #exercise[Find the image of the variety $M = AA^1$ under the rational map
    $(X) |-> ((1 - X^2)\/(1 + X^2), 2 X\/(1 + X^2))$.]
  <exc:circle-rational-parametrization>

  #exercise[#source(87)Suppose $M = AA^1$, and $f: (X) |-> (X^2, X^3)$. There is
    an inverse rational map $f^(-1): f(M) -> AA^1$ but it is not defined at
    $f(0)$.] <exc:cuspidal-cubic-inverse-map>

  #exercise[Let $char K = 0$.#ed-note[The book omits this assumption, needed
      here as in Theorem~@th:morphism-factors-through-dominant: if
      $char K = p > 0$, the function $x$ on $AA^1$ is constant on the level
      surfaces of $x^p$ (they are points) but is not a rational function of
      $x^p$.] Suppose $f_1, ..., f_k, g$ are rational functions on $AA^n$. If
    $g$ is constant on the level surfaces of the family ${f_1, ..., f_k}$, then
    it may be presented in the form of a rational function in $f_1, ..., f_k$.

    An _elementary algebraic predicate_ in variables $x in AA^n$, $y in AA^m$,
    $z in AA^p$, ... is a predicate of the form “$F(x, y, z, ...) = 0$”, where
    $F$ is a polynomial in $n + m + p + dots.c$ variables. Furthermore an #idx(
      "predicate",
      "algebraic",
    )_algebraic predicate_ is any predicate obtained from elementary ones within
    the framework of the logic of predicates, i.e. by making use of (a finite
    number of) conjunctions, disjunctions and negations and also quantifiers of
    existence and generality.

    A set $M subset AA^n times AA^m times AA^p times dots.c$ is #idx(
      "subset",
      "constructible",
    )_constructible_ if there exists a predicate $P$ containing free variables
    $x in AA^n$, $y in AA^m$, $z in AA^p$, ... (and containing no other free
    variables), such that $(a, b, c, ...) in M$ if and only if
    $P(a, b, c, ...) = 0$.] <exc:constant-on-level-sets-rational>

  #exercise[An irreducible component of a constructible set is constructible
    itself.] <exc:constructible-irreducible-components>

  #exercise[The image of an irreducible constructible set under a rational map
    into $AA^q$ is a constructible set in
    $AA^q$.] <exc:constructible-image-rational-map>

  #exercise[Any constructible set can be presented as a finite union of sets of
    the form $F without G$, where $F$ and $G$ are closed
    sets.] <exc:constructible-locally-closed-union>

  #exercise[An irreducible constructible set is épais in its
    closure.] <exc:constructible-epais-in-closure>
]

#hints[
  #hint[@pr:morphisms-from-algebra-homomorphisms][The desired morphism is of the
    form $x |-> (f_1 (x), ..., f_m (x))$, where $f_i = phi(y_i)$, where
    $y_1, ..., y_m$ are the restrictions on $N$ of coordinates in $AA^m$.]

  #hint[@pr:zariski-topology-axioms][$M(S_1) union M(S_2) = M(S)$, where
    $S = {f_1 f_2: f_1 in S_1 "and" f_2 in S_2}$.]

  #hint[@pr:affine-space-noetherian][This is a geometric equivalent of
    Theorem~@th:hilbert-basis.]

  #hint[@pr:prove-irreducible-decomposition][The topological spaces that are not
    representable as unions of finite numbers of closed irreducible subsets will
    be called bad spaces. Suppose $M$ is bad. Then, in particular, $M$ can not
    be irreducible, therefore $M = M_1 union M_2$, where $M_1, M_2$ are proper
    closed subsets and at least one of $M_1, M_2$ is bad. Suppose $M_1$ is bad.
    Then $M_1 = M_(11) union M_(12)$, where $M_(11), M_(12)$ are proper closed
    subsets and at least one of $M_(11), M_(12)$ is bad. Suppose this is
    $M_(11)$. Continuing the process, we obtain an infinite descending chain
    $M supset M_1 supset M_(11) supset dots.c$ of closed subsets of $M$. If $M$
    is noetherian, this is impossible.

    Suppose $M = union.big_(1 <= i <= k) M_i$, where $M_i$ is a closed
    irreducible subset such that $M_i subset.not M_j$ for $i != j$. Then
    $M_1, ..., M_k$ are all the maximal irreducible subsets of $M$, and
    therefore the $M_i$ are uniquely defined.]

  #hint[@pr:irreducible-iff-integral-domain][Suppose there are nonzero elements
    $f_1, f_2 in K[M]$ such that $f_1 f_2 = 0$. Then $M = M_1 union M_2$, where
    $M_k = {x in M: f_k (x) = 0}$ so that $M_1 != M$ and $M_2 != M$. Thus, if
    $K[M]$ has zero divisors then $M$ is reducible, and each zero divisor
    vanishes on an irreducible component of $M$.]

  #hint[@pr:field-extension-zariski-closure][Let ${u_alpha}$ be a basis of $L$
    as of a vector space over $K$. Any polynomial $f in L[X_1, ..., X_n]$ is
    representable in the form $f = sum_alpha u_alpha f_alpha$, where
    $f_alpha in K[X_1, ..., X_n]$ and for a point $x in AA^n$ the condition
    $f(x) = 0$ is equivalent to the conjunction of the conditions
    $f_alpha (x) = 0$. Therefore the intersection of any #source(88)closed
    subset of $AA^n (L)$ with $AA^n$ is closed in $AA^n$. Proof of the remaining
    statements is similar.]

  #hint[@pr:product-of-irreducible-varieties][Suppose
    $M times N = P_1 union P_2$, where $P_1$ and $P_2$ are closed subsets. For
    any $x in M$ consider the closed sets
    $ P_k (x) = {y in N: (x, y) in P_k} subset N quad "for" quad k = 1, 2. $
    Since $P_1 (x) union P_2 (x) = N$, one of the sets $P_1 (x)$ or $P_2 (x)$
    coincides with $N$. Now consider the closed sets
    $M_k = {x in M: (x, y) in P_k "for any" y in N} subset M$, where $k = 1, 2$.
    By the previous results $M = M_1 union M_2$. Hence, $M$ coincides either
    with $M_1$ or with $M_2$. If $M = M_k$, then $M times N = P_k$, therefore
    $M times N = P_1$ or $P_2$.]

  #hint[@pr:coordinate-algebra-of-product][Let ${f_1, f_2, ...}$ be a basis of
    $K[M]$. The homomorphism $omega: K[M] times.o K[N] -> K[M times N]$ defined
    by $pi_M^*$ and $pi_N^*$ assigns to $u = sum_i f_i times.o g_i$
    ($g_i in K[N]$) the function $h(x, y) = sum_i f_i (x) g_i (y)$ ($x in M$,
    $y in N$). If $h = 0$, then $g_i (y) = 0$ for any $i$ and $y in N$, but then
    $u = 0$. This proves the injectivity of $omega$. Its surjectivity is clear.
    The second statement of the problem follows from the first one.]

  #hint[@pr:extension-transcendental-generator][For any $f in A[X]$ put $f^phi$
    for a polynomial of $K[X]$ which is obtained from $f$ by applying the
    homomorphism $phi$ coefficient-wise. Let $b = g(u)$ and $alpha in K$ be any
    number which is not a root of $g^phi$. Define the homomorphism $psi$ setting
    $psi(f(u)) = f^phi (alpha)$. In this case $g^phi != 0$ is the only
    restriction on $phi$. This condition is verified if we take for $a$ any
    nonzero coefficient of $g$.]

  #hint[@pr:extension-algebraic-generator][Let $p in A[X]$ be the minimal
    polynomial of $u$. Denote by $a_1$ the highest degree coefficient of $p$. If
    $q in A[X]$ is such that $q(u) = 0$, then $q$ is divisible by $p$ in
    $Q A[X]$ and there exists $k$ such that $a_1^k q$ is divisible by $p$ in
    $A[X]$.

    Therefore, if $phi(a_1) != 0$ and $alpha in K$ is a root of $p^phi$, then
    the homomorphism $psi: B -> K$ that coincides with $phi$ on $A$ is
    well-defined by the formula $psi(f(u)) = f^phi (alpha)$.

    Now let us make $psi(b) != 0$. By
    Problem~@pr:generated-by-algebraic-is-algebraic $b$ is algebraic over $A$.
    Let $h in A[X]$ be a nonzero polynomial such that $h(b) = 0$. We may assume
    that the constant term $a_2$ of $h$ is nonzero (otherwise we divide $h$ by
    $X$). If $psi(b) = beta$, then $h^phi (beta) = 0$. Let $phi(a_2) != 0$. Then
    $beta$ is a root of a polynomial with a nonzero constant term and therefore
    $beta != 0$. Thus we may put $a = a_1 a_2$.]

  #hint[@pr:prove-homomorphism-extension][The induction in the number of
    generators of the algebra $B$ over $A$ reduces the proof to the cases
    considered in Problems~@pr:extension-transcendental-generator and
    @pr:extension-algebraic-generator.]

  #hint[@pr:prove-unique-extension-fraction-field][The induction in the number
    of generators of the algebra $B$ over $A$ enables us to reduce the proof to
    the case $B = A[u]$. In this case we are under the conditions of
    Problems~@pr:extension-transcendental-generator or
    @pr:extension-algebraic-generator. Let $a in A$ be a nonzero element
    constructed while solving the corresponding problem. By Corollary of
    Theorem~@th:homomorphism-extension-nonvanishing there is a homomorphism
    $phi: A -> K$ that does not annihilate $a$. The solutions of
    Problems~@pr:extension-transcendental-generator and
    @pr:extension-algebraic-generator show that the homomorphism $phi$ uniquely
    extends to a homomorphism $psi: B -> K$ only when $u$ is algebraic over $A$
    and $p^phi$ has a unique root, i.e. $p^phi = c(X - alpha)^k$, where $c in K$
    and $c != 0$.

    #source(89)Let us show that if $m = deg p > 1$, then $phi$ can be chosen so
    that the polynomial $p^phi$ is not of this form. Since $p$ is irreducible
    over $Q A$, then, in particular, $p$ is not proportional to any power of a
    linear binomial. Let
    $
      p = p_0 + p_1 X + dots.c + p_m X^m, quad "where" quad
      p_i in A, p_m != 0.
    $
    There exists $i <= m - 2$ such that
    $p_i != p_m binom(m, i) (p_(m-1)\/m p_m)^(m-i)$, i.e.
    $m^(m-i) p_m^(m-i-1) p_i != binom(m, i) p_(m-1)^(m-i)$, otherwise
    $p = p_m (X + (p_(m-1)\/m p_m))^m$. If we require an extra condition:
    $phi(m^(m-i) p_m^(m-i-1) p_i - binom(m, i) p_(m-1)^(m-i)) != 0$, then
    $p^phi$ also is not proportional to any degree of a linear binomial.

    Thus, $deg p = 1$. But this means exactly that $u in Q A$ and hence
    $B subset Q A$.]

  #hint[@pr:kernel-of-restriction-is-nilradical][First show that the kernel of
    $rho$ coincides with the intersection of the kernels of all the
    homomorphisms $A -> K$. Further, apply
    Theorem~@th:nilradical-intersection-of-primes and Corollary of
    Theorem~@th:homomorphism-extension-nonvanishing.]

  #hint[@pr:weak-nullstellensatz-on-variety][Consider an embedding $M -> AA^n$
    and apply Theorem~@th:hilbert-nullstellensatz to the preimage of the ideal
    $I$ with respect to the restriction homomorphism $K[X_1, ..., X_n] -> K[M]$
    and to $f = 1$.]

  #hint[@pr:disjoint-union-coordinate-algebra][The proof reduces to the case
    $q = 2$. In this case Problem~@pr:weak-nullstellensatz-on-variety implies
    that $I_M (M_1) + I_M (M_2) = K[M]$. This means that the considered map is
    surjective. Its injectivity is obvious.]

  #hint[@pr:denominator-ideal-and-domain][Let $M = M_1 union dots.c union M_q$
    be the decomposition of $M$ into irreducible components. By
    Problem~@pr:irreducible-iff-integral-domain the set of zero divisors of
    $K[M]$ is the union of the ideals $I_M (M_s)$, $s = 1, ..., q$. Since $I_f$
    contains at least one nondivisor of zero, then $I_f inter I_M (M_s)$ is a
    proper subspace of $I_f$ for any $s$. If all the nondivisors of zero
    contained in $I_f$ had belonged to some of its proper subspaces, then $I_f$
    would have been a union of a finite number of proper subspaces which is
    impossible.]

  #hint[@pr:everywhere-defined-is-polynomial][Let $f$ be such a function. The
    conditions of the problem imply that the variety of zeros of $I_f$ is empty.
    By Problem~@pr:weak-nullstellensatz-on-variety this implies that
    $I_f in.rev 1$, i.e. $f$ is presentable in the form $f = g\/1$, where
    $g in K[M]$, as required.]

  #hint[@pr:rational-functions-on-principal-open][Is solved like
    Problem~@pr:everywhere-defined-is-polynomial but with the help of Hilbert’s
    Nullstellensatz itself.]

  #hint[@pr:definedness-from-restriction][Passing to an appropriate dense
    principal open subset reduce to the case when $M' inter M'' = emptyset$ and
    use Problem~@pr:disjoint-union-coordinate-algebra.]

  #hint[@pr:rational-functions-product-components][Passing to an appropriate
    dense principal open subset reduce to the case when irreducible components
    of $M$ do not intersect and use
    Problem~@pr:disjoint-union-coordinate-algebra.]

  #hint[@pr:rational-maps-from-homomorphisms][Let $N$ be embedded in the affine
    space $AA^m$ with coordinates $Y_1, ..., Y_m$. Then the required map is of
    the form $x |-> (f_1 (x), ..., f_m (x))$, where $f_i = phi(y_i)$,
    $y_i = Y_i|_N$.]
]
