// Chapter 2, § 2. Projective and Quasiprojective Varieties. Printed pages
// 74-87. Page 74 begins with the hints of § 1, which carry its source-page
// anchor.
#import "main-defs.typ": *
#import "statements.typ": *

== Projective and Quasiprojective Varieties
<sec:projective-quasiprojective-varieties>

=== Graded Algebras <ss:graded-algebras>
Before we start to define projective varieties recall certain elementary facts
on graded vector spaces and algebras.

#source(90)A vector space $V$ is _graded_ if there are distinguished subspaces
$V_k$ ($k in ZZ$) in it called _grading subspaces_ such that
$V = plus.o.big_k V_k$. The nonzero elements of $V_k$ are then called
_homogeneous_ elements of degree $k$. By definition any nonzero element is
uniquely presentable as the sum of homogeneous elements called its #idx(
  "component",
  "homogeneous",
)_homogeneous components._ A subspace $U subset V$ is called _homogeneous_ if
together with each of its elements it contains all its homogeneous components.
This is equivalent to the fact that $U = plus.o.big_k U_k$, where
$U_k subset V_k$. If $U$ is a homogeneous subspace then the quotient space
$V\/U$ inherits the grading such that $(V\/U)_k = V_k\/U_k$.

A grading is called _nonnegative_ if $V_k = 0$ for $k < 0$. In this chapter we
will only consider nonnegative gradings.

An algebra $A$ is called #idx("algebra", "graded")_graded_ if it is graded by
subspaces $A_k$ ($k in ZZ$) as a vector space and $A_k A_l subset A_(k+l)$ for
any $k, l in ZZ$. If $I$ is a homogeneous ideal of a graded algebra $A$ then
$A\/I$ is also a graded algebra.

A polynomial algebra possesses a standard nonnegative grading: the homogeneous
elements of degree $k$ are just the forms (homogeneous polynomials) of degree
$k$. Notice, that in this case all the grading subspaces are finite dimensional
(though the algebra itself is infinite dimensional).

#problem[The radical of a graded algebra is a homogeneous
  ideal.] <pr:graded-radical-homogeneous>

#problem[If there are no homogeneous zero divisors in a graded algebra $A$ i.e.
  $p q = 0$ for $p in A_k$, $q in A_l$ implies either $p = 0$ or $q = 0$, then
  there are no zero divisors in $A$ at all.] <pr:graded-no-zero-divisors>

=== Embedded Projective Algebraic Varieties <ss:embedded-projective-varieties>
Let $PP^n$ be an $n$-dimensional projective space over $K$ and
$U_0, U_1, ..., U_n$ homogeneous coordinates in $PP^n$. Since homogeneous
coordinates of a point are only defined up to a simultaneous multiplication by a
nonzero element of $K$, it is impossible to speak about the value of a
polynomial $p in K[U_0, U_1, ..., U_n]$ at a point $x in PP^n$. But if $p$ is a
form (i.e. a homogeneous polynomial) the equality $p(x) = 0$ is meaningful. If
$p$ and $q$ are forms of the same degree and $q(x) != 0$, then the ratio
$p(x)\/q(x)$ is well defined.

An algebraic variety in $PP^n$ or an embedded #idx(
  "algebraic variety",
  "projective",
  "embedded",
)_projective algebraic variety_ is a subset in $PP^n$ singled out by the system
of equations
$ p(U_0, U_1, ..., U_n) = 0 quad (p in S) $ <eq:projective-variety-equations>
where $S$ is a set of forms. The variety defined by
system~@eq:projective-variety-equations will be denoted by $M^"pr" (S)$.

#problem[Any homogeneous ideal of $K[U_0, U_1, ..., U_n]$ possesses a finite
  system of homogeneous generators.] <pr:homogeneous-ideal-finite-generators>

Let $M$ be an algebraic variety in $PP^n$. Consider a subspace of
$K[U_0, U_1, ..., U_n]$ generated by all forms that vanish on $M$. This subspace
is a homogeneous ideal. Denote it by $I^"pr" (M)$. If $S$ is a system of its
homogeneous generators, then $M = M^"pr" (S)$. Therefore
Problem~@pr:homogeneous-ideal-finite-generators implies that any algebraic
variety in $PP^n$ can be defined by a finite number of homogeneous equations.

#source(91)Call the algebraic varieties in $PP^n$ its closed subsets. This
introduces a topology in $PP^n$ (cf. Problem~@pr:zariski-topology-axioms) called
the #idx(
  "Zariski topology",
)_Zariski topology._

#problem[The space $PP^n$ endowed with the Zariski topology is an irreducible
  noetherian topological space (see
  @ss:zariski-topology).] <pr:projective-space-noetherian-irreducible>

Now define rational functions on an algebraic variety $M subset PP^n$. Consider
the algebra
$ K[M]^"pr" = K[U_0, U_1, ..., U_n]\/I^"pr" (M). $
Since $I^"pr" (M)$ is a homogeneous ideal, $K[M]^"pr"$ inherits the grading of
$K[U_0, U_1, ..., U_n]$.

Unlike in the affine case, the elements of $K[M]^"pr"$ cannot be considered as
functions on $M$. However, if $p in K[M]^"pr"$ is a homogeneous element then the
identity $p(x) = 0$ makes sense for $x in M$; if $p, q in K[M]^"pr"$ are
homogeneous elements of the same degree and $q(x) != 0$, then the ratio
$p(x)\/q(x)$ makes sense.

#problem[$M$ is irreducible if and only if $K[M]^"pr"$ has no zero divisors.
  More precisely, the homogeneous zero divisors of $K[M]^"pr"$ are its
  homogeneous elements which vanish on an irreducible component of
  $M$.] <pr:projective-irreducible-no-zero-divisors>

In $Q K[M]^"pr"$, consider the subalgebra generated by the ratios of the form
$p\/q$, where $p$, $q$ are homogeneous elements of the same degree (and $q$ is
not a zero divisor). This subalgebra is denoted by $K(M)$ and is called the
#idx("algebra of rational functions")_algebra of rational functions_ on $M$.
Problem~@pr:projective-irreducible-no-zero-divisors shows that if $M$ is
irreducible then $K(M)$ is a field.

The elements of $K(M)$ are called _rational functions_ on $M$. A function
$f in K(M)$ _is considered defined_ at $x in M$ if it is presentable in the form
$p\/q$, where $p, q in K[M]^"pr"$ are homogeneous elements of the same degree
and $q(x) != 0$. In this case the ratio $p(x)\/q(x) in K$ (independent of the
choice of such a presentation) is called the _value_ of $f$ at $x$ and is
denoted by $f(x)$. As in the affine case, the properties (R1)--(R4) of
@ss:rational-functions hold.

Let $f$ be a rational function on $M$. The denominators of all possible
representations of $f$ in the form of a ratio of two homogeneous elements (of
the same degree) of $K[M]^"pr"$ are exactly the homogeneous nondivisors of zero
contained in the homogeneous ideal
$ I_f = {h in K[M]^"pr": f h in K[M]^"pr"}. $

#problem[The domain $D_f$ of $f$ is the complement of the set of zeros of $I_f$,
  i.e. of the set of points where all homogeneous elements of $I_f$
  vanish.] <pr:projective-rational-function-domain>

The following theorem demonstrates the crucial difference between projective
varieties and affine ones.

#theorem[Let $M subset PP^n$ be an irreducible algebraic variety. Any rational
  function $f in K(M)$ defined at all points of $M$ is a constant, i.e. belongs
  to $K$.] <th:projective-regular-functions-constant>

#proof[Consider the affine space $AA^(n+1)$ with coordinates
  $U_0, U_1, ..., U_n$. Let $I$ be the pre-image of $I_f$ with respect to the
  canonical homomorphism
  #source(92)
  $ pi: K[U_0, U_1, ..., U_n] -> K[M]^"pr". $
  The absence of zeros of $I_f$ on $M$ means that the unique zero of $I$ on
  $AA^(n+1)$ is the origin. Applying Hilbert's Nullstellensatz to the ideal
  $I subset K[U_0, U_1, ..., U_n]$ and the coordinate functions
  $U_0, U_1, ..., U_n$ we see that $I$ contains some powers of all coordinate
  functions and therefore contains all homogeneous polynomials of a sufficiently
  high degree. Therefore $I_f$ contains all homogeneous elements of $K[M]^"pr"$
  of a sufficiently high degree.

  Let $V$ be one of the grading subspaces of $K[M]^"pr"$ belonging entirely to
  $I_f$. The map $h |-> f h$ ($h in V$) is a linear transformation. Consider an
  eigenvector $h_0$ of this transformation. We have $f h_0 = c h_0$ ($c in K$)
  and since $h_0$ is not a zero divisor ($M$ is irreducible!), we have $f = c$,
  as required.]

Developing the arguments contained in the first part of this proof we may assign
to every algebraic variety $M subset PP^n$ an algebraic variety
$hat(M) subset AA^(n+1)$, “the cone over $M$”, defined by the same equations as
$M$ (but in which $U_0, U_1, ..., U_n$ are considered as coordinates in
$AA^(n+1)$). Then $K[M]^"pr"$ is identified with $K[hat(M)]$ and $K(M)$ with a
subfield of $K(hat(M))$. Problems~@pr:projective-rational-function-domain and
@pr:denominator-ideal-and-domain imply that the domain of $f in K(M)$ on
$hat(M)$ is a cone (perhaps without the vertex) over its domain on $M$.
Problems~@pr:projective-irreducible-no-zero-divisors and
@pr:irreducible-iff-integral-domain show that the irreducible components of
$hat(M)$ are cones over the irreducible components of $M$.

#problem[The subfield $K(M) subset K(hat(M))$ consists of all functions
  invariant with respect to homotheties, i.e. constant on generatrices of
  $hat(M)$.] <pr:cone-homothety-invariant-functions>

The described trick enables one to apply the affine theory to the study of
projective varieties. In particular, it enables one to derive from
Problems~@pr:restriction-preserves-values–@pr:rational-functions-product-components
their projective analogues.

Namely, let $M subset PP^n$ be an algebraic variety, $M'$ the union of some of
its irreducible components and $M''$ the union of the remaining components. In
exactly the same way as in the affine case the restriction homomorphism
$K(M) -> K(M')$ is defined.

#problem[If a function $f$ is defined at $x in M'$ then so is $f|_(M')$ and
  $f|_(M') (x) = f(x)$.] <pr:projective-restriction-preserves-domain>

#problem[If a function $f|_(M')$ is defined at $x in M' without M''$ then so is
  $f$.] <pr:projective-restriction-reflects-domain>

#problem[Let $M = M_1 union dots.c union M_q$ be a decomposition of $M$ into
  irreducible components. Then the homomorphism
  $
    K(M) -> K(M_1) times dots.c times K(M_q), wide
    f |-> (f|_(M_1), ..., f|_(M_q))
  $
  is an isomorphism.] <pr:projective-rational-functions-components>

=== Sheaves of Functions <ss:sheaves-of-functions>
To consider affine and projective algebraic varieties from a unified point of
view and to be able to define abstract projective and more general algebraic
varieties introduce the notion of a topological space with a sheaf of functions
or, briefly, of sheafed space.

#source(93)One says that on a topological space $M$ the #idx("sheaf")_sheaf_
$cal(O)$ of functions (_or, more precisely, of algebras of functions_) is
defined if for any open subset $U subset M$ a subalgebra $cal(O)(U)$ is
distinguished in the algebra of all continuous functions on $U$ with values in
$K$ so that

(S1) if $V subset U$ and $f in cal(O)(U)$ then $f|_V in cal(O)(V)$

(S2) if $U = union.big_alpha U_alpha$ and $f$ is a function on $U$ such that
$f|_(U_alpha) in cal(O)(U_alpha)$ for all $alpha$ then $f in cal(O)(U)$.

When needed we will write $cal(O)_M$ instead of $cal(O)$.

A continuous map $f: M -> N$ of #idx("space", "sheafed")sheafed spaces is a
_morphism_ if $f^* cal(O)_N (V) subset cal(O)_M (f^(-1) (V))$ for any open
subset $V subset N$. Clearly, the composition of morphisms is a morphism.

A subspace $N$ of a sheafed space $M$ is canonically endowed with a sheaf of
functions. Namely, a function $f$ on an open subset $V$ of $N$ is assumed to
belong to $cal(O)_N (V)$ if there exist open subsets $U_alpha$ of $M$ and
functions $f_alpha in cal(O)_M (U_alpha)$ such that
$V = N inter (union.big_alpha U_alpha)$ and
$f|_(N inter U_alpha) = f_alpha|_(N inter U_alpha)$ for all $alpha$.

#problem[This structure on $N$ satisfies the axioms of the sheaf of
  functions.] <pr:sheaf-restriction-to-subspace>

The sheaf $cal(O)_N$ is called the _restriction_ of $cal(O)_M$ onto $N$. Its
definition implies that the identity embedding $N subset M$ is a morphism. If
$N$ is open in $M$ then $cal(O)_N (V) = cal(O)_M (V)$ for any open $V subset N$.

#problem[The restriction of sheaves of functions is a transitive operation
  meaning that if $P subset N subset M$ then the sheaf of functions on $P$
  obtained by consecutive restrictions of $cal(O)_M$ first onto $N$ and then
  onto $P$ coincides with the sheaf obtained by directly restricting $cal(O)_M$
  onto $P$.] <pr:sheaf-restriction-transitive>

Let $M$ and $N$ be two sheafed spaces.

#problem[If $f: M -> N$ is a morphism and $f(M) subset N_0 subset N$ then
  $f: M -> N_0$ is a morphism.] <pr:morphism-into-subspace>

#problem[Let $M = union.big_alpha U_alpha$ be an open covering. If a map
  $f: M -> N$ is such that its restriction onto any subset $U_alpha$ is a
  morphism (into $N$) then $f$ is a morphism.] <pr:morphism-local-on-covering>

Now suppose $M$ is irreducible (see @ss:zariski-topology). Any morphism of a
nonempty open subset $U subset M$ into $N$ will be called a #idx(
  "morphism",
  "partial",
)_partial morphism_ of $M$ into $N$. Two partial morphisms are called
_equivalent_ if they coincide on the common domain.

#problem[The above is an equivalence relation on partial
  morphisms.] <pr:partial-morphisms-equivalence>

#problem[An equivalence class of partial morphisms contains a (unique) morphism
  whose domain contains the domains of all partial morphisms of the given
  class.] <pr:partial-morphism-maximal-domain>

A partial morphism satisfying the conditions of this problem is called a #idx(
  "map",
  "rational",
)_rational map_ of $M$ into $N$. Clearly, an everywhere defined rational map is
a morphism.

A rational map $f: M -> N$ is called #idx(
  "map",
  "rational",
  "dominant",
)_dominant_ if $overline(f(M)) = N$. (In this case $N$ is also irreducible).

The product of a dominant rational map $f: M -> N$ and a rational map
$g: N -> P$ is a rational map $g f: M -> P$ equivalent to any partial morphism
of the #source(94)form $g_0 f_0$, where $f_0$ and $g_0$ are partial morphisms
equivalent to $f$ and $g$ respectively and the image of $f_0$ is contained in
the domain of $g_0$. It is easy to see that such pairs $(f_0, g_0)$ exist and if
$f$ is defined at $x in M$ and $g$ is defined at $f(x) in N$ then $g f$ is
defined at $x$ and $(g f)(x) = g(f(x))$; however $g f$ may also be defined at
points which do not satisfy these conditions.

=== Sheaves of Algebras of Rational Functions
<ss:sheaves-of-rational-functions>
Let $M$ be an embedded affine or projective algebraic variety. In both cases the
notion of a rational function is defined. For any open subset $U subset M$
denote by $cal(O)(U)$ the algebra of functions on $U$ defined by restrictions
onto $U$ of rational functions whose domains contain $U$. (If $U$ is dense in
$M$ then $cal(O)(U)$ is identified with a subalgebra of $K(M)$.)

#problem[This structure $cal(O)$ on $M$ is a sheaf of
  functions.] <pr:rational-functions-form-sheaf>

This sheaf is called the #idx("sheaf of rational functions")_sheaf of_
(_algebras of_) _rational functions._

#problem[The sheaf $cal(O)$ on $M$ coincides with the restriction onto $M$ of
  the sheaf of rational functions on the hosting affine or projective
  space.] <pr:rational-sheaf-ambient-restriction>

The open subset in $PP^n$ defined by $U_0 != 0$ can be identified with $AA^n$
and the functions $X_i = U_i\/U_0$ ($i = 1, ..., n$) form a coordinate system in
this $AA^n$. Therefore a point $(X_1, ..., X_n) in AA^n$ is identified with the
point $(1 ratio X_1 ratio ... ratio X_n) in PP^n$.

#problem[The sheaf of rational functions on $AA^n$ coincides with the
  restriction of the sheaf of rational functions on
  $PP^n$.] <pr:affine-chart-sheaf-restriction>

#problem[Let $M_h$ ($h in K[M]$) be a principal open subset of an affine variety
  $M$. The sheaf of rational functions on $M_h$ as on an affine variety (see
  @ss:rational-functions[°]) coincides with the restriction of the sheaf of
  rational functions on $M$.] <pr:principal-open-sheaf-restriction>

#problem[The morphisms of affine varieties are the same as their morphisms as of
  sheafed spaces.] <pr:affine-morphisms-sheafed>

This means that affine varieties can be considered as special objects in the
category of sheafed spaces. Namely an (abstract) affine algebraic variety is a
sheafed space isomorphic to a closed subset of an affine space.

#problem[The rational maps of irreducible affine varieties (see
  @ss:rational-maps[°]) are the same as their rational maps as of sheafed spaces
  (see @ss:sheaves-of-functions).] <pr:affine-rational-maps-sheafed>

Similarly, an (abstract) #idx("algebraic variety", "projective")projective
algebraic variety is defined as a sheafed space isomorphic to a closed subset of
a projective space. The _morphisms_ of _projective varieties_ are by definition
the morphisms of sheafed spaces.

=== Quasiprojective Varieties <ss:quasiprojective-varieties>
A #idx("algebraic variety", "quasiprojective")_quasiprojective algebraic
variety_ (or simply a _quasiprojective variety_) is a sheafed space isomorphic
to an open subset of a projective variety or, which is the same, a locally
closed subset of a projective space.

Affine and projective algebraic varieties are particular cases of
quasiprojective ones. These cases exclude each other. More precisely, if an
irreducible quasiprojective variety $M$ is simultaneously affine and projective
then it consists of one #source(95)point. Indeed, if $M$ is affine then
$cal(O)(M) = K[M]$, and if $M$ is projective then $cal(O)(M) = K$
(Theorem~@th:projective-regular-functions-constant). Therefore if it is both
affine and projective then $K[M] = K$, but for an affine variety this means that
it consists of one point.

A locally closed subset of a quasiprojective variety $M$ (endowed with the
induced topology and a sheaf of functions which is the restriction of the sheaf
$cal(O)_M$) is called a _subvariety_ of $M$. Clearly, it is also a
quasiprojective variety; any closed subvariety of an affine (resp. projective)
variety is affine (resp. projective).

By definition any quasiprojective variety $M$ can be embedded as an open
subvariety into a projective variety $P$. Assuming that $M$ is dense in $P$ (we
can always do this without loss of generality) set $K(M) = K(P)$ and consider
each element of $K(M)$ as a function on $M$ which is the restriction of the
corresponding rational function on $P$. The functions on $M$ obtained in this
way will also be called _rational_ ones. They are characterized in inner terms
as the functions from $cal(O)_M$ whose domains cannot be extended.

On the other hand, $cal(O)_M$ is completely defined by the algebra of rational
functions on $M$ since for any open subset $U subset M$ the functions from
$cal(O)_M (U)$ are nothing but the restrictions of rational functions.

Clearly, if $M_0 subset M$ is a dense open subvariety then there exists a
natural isomorphism of algebras $K(M)$ and $K(M_0)$ which to any rational
function on $M$ assigns its restriction onto $M_0$.

The following problems show that quasiprojective varieties can be in a sense
approximated by affine ones and their morphisms by morphisms of affine
varieties.

#problem[For any finite set of points of a quasiprojective variety there exists
  a dense open affine subvariety containing
  it.] <pr:open-affine-contains-finite-set>

#problem[For any morphism $f: M -> N$ of quasiprojective varieties there exist
  dense open affine subvarieties $M_0 subset M$ and $N_0 subset N$ such that
  $f(M_0) subset N_0$ (and then the map $f: M_0 -> N_0$ is automatically a
  morphism, cf. Problem~@pr:morphism-into-subspace). Moreover, we may require
  that $M_0$ and $N_0$ contain any prescribed finite sets of points of $M$ and
  $N$ respectively.] <pr:morphism-affine-open-restriction>

Due to this, Theorems~@th:dominant-morphism-image-epais and
@th:morphism-factors-through-dominant are obviously generalized to any
quasiprojective varieties. Let us formulate theorems thus obtained.

#theorem[Let $f: M -> N$ be a dominant morphism of irreducible quasiprojective
  varieties. Then $f(M)$ is an épais subset of
  $N$.] <th:quasiprojective-dominant-image-epais>

#theorem[Let $char K = 0$, let $M$, $N$, $P$ be irreducible quasiprojective
  varieties, and let $f: M -> N$, $h: M -> P$ be dominant morphisms. If
  $f(x') = f(x'')$ implies $h(x') = h(x'')$ for any $x', x'' in M$ then there
  exists a (dominant) rational map $g: N -> P$ such that
  $h = g f$.] <th:quasiprojective-morphism-factorization>

Clearly, a complex quasiprojective variety is projective if and only if it is
compact in a real topology.

=== The Direct Product <ss:direct-product-quasiprojective>
The direct product $M times N$ of affine varieties $M$ and $N$ defined in
@ss:direct-product-affine-varieties[°] is their set-theoretic direct product
endowed with an affine #source(
  96,
)variety structure. Let us characterize this structure in terms meaningful for
any quasiprojective varieties.

#problem[The projections of the direct product $M times N$ onto $M$ and $N$ are
  morphisms. For any affine variety $P$ and morphisms $f: P -> M$ and
  $g: P -> N$ the map
  $ P -> M times N, wide z |-> (f(z), g(z)) $
  is a morphism.] <pr:affine-product-universal-property>

Taking this as a guide, give the following axiomatic definition of the #idx(
  "product",
  "direct",
  "of quasiprojective varieties",
)_direct product of quasiprojective varieties $M_1, ..., M_k$_: it is their
set-theoretical direct product $M_1 times dots.c times M_k$ endowed with a
quasiprojective variety structure so that

(P1) the projections $p_i: M_1 times dots.c times M_k -> M_i$ ($i = 1, ..., k$)
are morphisms;

(P2) for any quasiprojective variety $P$ and any morphisms $f_i: P -> M_i$
($i = 1, ..., k$) the map
$ P -> M_1 times dots.c times M_k, wide z |-> (f_1 (z), ..., f_k (z)) $
is a morphism.

#problem[On $M_1 times dots.c times M_k$, there exists no more than one
  quasiprojective variety structure satisfying these
  axioms.] <pr:quasiprojective-product-uniqueness>

(The existence of such a structure, however, is not clear from the definition.)

Thanks to Problem~@pr:morphism-local-on-covering and the existence of an open
covering of any quasiprojective variety by affine subvarieties
(Problem~@pr:open-affine-contains-finite-set) one may confine oneself in the
above definition to affine varieties $P$. Therefore the direct product of affine
varieties in the sense of @ss:direct-product-affine-varieties is also their
direct product in the sense of the new definition.

The direct product topology of quasiprojective varieties need not coincide with
the topology of the direct product of topological spaces and in nontrivial cases
never coincides with the latter (see @ss:zariski-topology). However, the
following problem shows that in any case the direct product topology is not
weaker than the latter one.

#problem[Let $M_1 times dots.c times M_k$ be the direct product of
  quasiprojective varieties $M_1, ..., M_k$ and $N_i subset M_i$
  ($i = 1, ..., k$) be locally closed (resp. open, closed) subsets. Then
  $N_1 times dots.c times N_k$ is a locally closed (resp. open, closed) subset
  of $M_1 times dots.c times M_k$. Endowed with a quasiprojective variety
  structure as a subvariety of $M_1 times dots.c times M_k$ it is the direct
  product of varieties $N_1, ..., N_k$.] <pr:product-of-subvarieties>

Now, let us consider the question of the existence of the direct product.

#theorem[For any quasiprojective varieties $M_1, ..., M_k$ there exists their
  direct product $M_1 times dots.c times M_k$ and if $M_1, ..., M_k$ are affine
  (resp. projective) varieties then so is $M_1 times dots.c times M_k$. The
  direct product of irreducible varieties is an irreducible
  variety.] <th:quasiprojective-product-existence>

The following problem enables us to reduce the proof to the case of two factors.

#problem[#source(97)Let $M_1 times dots.c times M_(k-1) = N$ be the direct
  product of quasiprojective varieties $M_1, ..., M_(k-1)$, and $N times M_k$ be
  the direct product of $N$ and $M_k$. Then $N times M_k$ naturally identified
  with $M_1 times dots.c times M_k$ is the direct product of
  $M_1, ..., M_k$.] <pr:direct-product-associativity>

Furthermore, since any quasiprojective variety is by definition a subvariety of
a projective space, Problem~@pr:product-of-subvarieties shows that it suffices
to prove the existence of the direct product of projective spaces. For this let
us make use of the following criterion.

#problem[Let $M = union.big_alpha M_alpha$ and $N = union.big_beta N_beta$ be
  open coverings of quasiprojective varieties $M$ and $N$ and let a
  quasiprojective variety structure on $M times N$ be introduced so that the
  subvariety $M_alpha times N_beta subset M times N$ is the direct product of
  varieties $M_alpha$ and $N_beta$ for any $alpha$, $beta$. Then $M times N$ is
  the direct product of $M$ and $N$.] <pr:direct-product-local-criterion>

Now let $PP^n$ and $PP^m$ be the projective spaces with homogeneous coordinates
$U_i$ ($i = 0, 1, ..., n$) and $V_j$ ($j = 0, 1, ..., m$) respectively. Consider
the projective space $PP^(n m+n+m)$ with homogeneous coordinates $W_(i j)$
($i = 0, 1, ..., n; j = 0, 1, ..., m$) and the map
$ eta: PP^n times PP^m -> PP^(n m+n+m) $
defined by the formulas $W_(i j) = U_i V_j$.

#problem[The map $eta$ is one-to-one. Its image is closed in
  $PP^(n m+n+m)$.] <pr:segre-map-injective-closed>

Identifying $PP^n times PP^m$ with its image under $eta$ we introduce on it a
projective variety structure.

Let us identify the open subsets of $PP^n$, $PP^m$ and $PP^(n m+n+m)$
distinguished by the inequalities
$ U_0 != 0, wide V_0 != 0, wide W_(00) != 0, $ <eq:segre-affine-charts>
respectively, with the affine spaces $AA^n$, $AA^m$ and $AA^(n m+n+m)$ (see
@ss:sheaves-of-rational-functions). We have
$ eta(AA^n times AA^m) subset AA^(n m+n+m). $

#problem[The map $eta$ induces the isomorphism of $AA^n times AA^m = AA^(n+m)$
  onto a closed subvariety of
  $AA^(n m+n+m)$.] <pr:segre-affine-chart-isomorphism>

This means that the projective variety structure introduced on $PP^n times PP^m$
induces a direct product structure on $AA^n times AA^m$. Since instead of $U_0$,
$V_0$ and $W_(00)$ in @eq:segre-affine-charts we might have taken $U_i$, $V_j$
and $W_(i j)$ with any $i$, $j$, then the conditions of
Problem~@pr:direct-product-local-criterion are satisfied, hence
$PP^n times PP^m$ is actually the direct product of $PP^n$ and $PP^m$.

We have therefore simultaneously proved the first statement of the theorem and
the fact that the direct product of projective varieties is a projective
variety. The fact that the direct product of affine varieties is an affine
variety had actually already been proved in §~@sec:affine-algebraic-varieties.
The irreducibility of the direct product of irreducible varieties is proved as
in the affine case (Problem~@pr:product-of-irreducible-varieties).

#source(98)It is useful to describe the topology of $PP^n times PP^m$ in the
inner terms.

#problem[A subset $F subset PP^n times PP^m$ is closed if and only if it can be
  defined by a system of equations of the form
  $ p(U_0, U_1, ..., U_n; V_0, V_1, ..., V_m) = 0, $
  where $p$ is a polynomial homogeneous separately in $U_0, U_1, ..., U_n$ and
  in $V_0, V_1, ..., V_m$.] <pr:bihomogeneous-closed-subsets>

=== Flag Varieties <ss:flag-varieties>
Let $V$ be an $n$-dimensional vector space.

A #idx("Flag")_flag_ in $V$ is a set ${V_1, ..., V_n}$ of its subspaces such
that $dim V_k = k$ and $V_k subset V_(k+1)$ ($k = 1, ..., n - 1$).

In this subsection we aim to introduce a natural structure of a projective
algebraic variety on the set of flags. This variety is called the _flag variety_
and plays an important role in the theory of algebraic groups.

Let $Lambda(V) = plus.o.big_(k >= 0) Lambda^k (V)$ be the _exterior (Grassmann)
algebra_ of $V$ (see [@bib:Bourbaki1958, @bib:Lang1965]). The elements of
$Lambda^k (V)$ are called _$k$-vectors._ There is a canonical isomorphism
$theta$ between the space $Lambda^k V$ and the space of the $k$-th degree
skewsymmetric tensors, defined by the formula
$
  theta(x_1 and dots.c and x_k)
  = sum (-1)^("parity of" sigma) x_(sigma(1)) times.o dots.c times.o
  x_(sigma(k)),
$
where $sigma$ runs through all permutations.

A nonzero $k$-vector is called _simple_ (or _decomposable_) if it can be
presented in the form $x_1 and dots.c and x_k$, where $x_i in V$. The above
isomorphism defines a coordinate system in $Lambda^k V$ in which coordinates of
a simple $k$-vector $x_1 and dots.c and x_k$ are the $k$-th order minors of the
matrix formed by the coordinates of vectors $x_1, ..., x_k$ in a fixed basis of
$V$. These are the #idx("Plücker coordinates")_Plücker coordinates._

#problem[Suppose $u = x_1 and dots.c and x_k$ is a simple $k$-vector. The
  subspace $V(u) subset V$ spanned by the vectors $x_1, ..., x_k$ is uniquely
  recovered from $u$ as follows:
  $
    V(u) = {x in V: u and x = 0}
  $ <eq:multivector-annihilator>] <pr:simple-multivector-subspace>

Clearly, a simple $k$-vector $u$ is defined by the subspace $V(u)$ up to a
factor. Thus, there is a one-to-one correspondence between the $k$-dimensional
subspaces of $V$ and the one-dimensional subspaces of $Lambda^k V$ consisting of
simple $k$-vectors.

#problem[If a nonzero $k$-vector $u$ is not simple then $dim V(u) < k$, where
  $V(u) subset V$ is constructed in
  @eq:multivector-annihilator.] <pr:nonsimple-multivector-annihilator>

Let $P(U)$ be the projective space associated with the vector space $U$. (The
points of $P(U)$ are the one-dimensional subspaces of $U$). In accordance with
the above, the set of all $k$-dimensional subspaces of $V$ is identified with
some subset $Gr_k (V) subset P(Lambda^k V)$ called the #idx(
  "Grassmann variety",
)_Grassmann variety._

#problem[#source(99)$Gr_k (V)$ is closed in
  $P(Lambda^k V)$.] <pr:grassmannian-closed>

Let us prove that the Grassmann variety is irreducible. Let $upright(E)(V)$ be
the set of all frames of $V$. There is a surjective map
$ g_k: upright(E)(V) -> Gr_k (V), $
which to each basis assigns the subspace spanned by the first $k$ of its
elements. The set $upright(E)(V)$ is endowed with the structure of an
irreducible affine variety as a principal open subset of the irreducible affine
variety $V times dots.c times V$ ($n$ factors).

#problem[The map $g_k$ is a morphism of $upright(E)(V)$ into
  $P(Lambda^k V)$.] <pr:frames-to-grassmannian-morphism>

Since the image of an irreducible topological space under a continuous mapping
is irreducible, the above implies that $Gr_k (V)$ is irreducible.

Let $1 <= k < l <= n$. Consider the subset
$Gr_(k, l) (V) subset Gr_k (V) times Gr_l (V)$ consisting of pairs $(W, U)$ of
subspaces, such that $dim W = k$, $dim U = l$ and $W subset U$.

#problem[The subspace $Gr_(k, l) (V)$ is closed in
  $Gr_k (V) times Gr_l (V)$.] <pr:grassmannian-incidence-closed>

The set $upright(F)(V)$ of all flags of $V$ is a subset in the direct product
$Gr_1 (V) times dots.c times Gr_n (V)$.

#problem[The set $upright(F)(V)$ is closed in
  $Gr_1 (V) times dots.c times Gr_n (V)$.] <pr:flag-variety-closed>

#problem[The set $upright(F)(V)$ is irreducible.] <pr:flag-variety-irreducible>

Thus, the set $upright(F)(V)$ is an irreducible closed subset of the projective
variety $Gr_1 (V) times dots.c times Gr_n (V)$ and due to this fact it is
endowed with an irreducible projective variety structure. This variety is called
the #idx("Flag variety")_flag variety_ of $V$.

#exercises[
  #exercise[The projective variety $M^"pr" (S)$ defined by
    @eq:projective-variety-equations is empty if and only if there exists $k$
    such that the ideal of $K[U_0, U_1, ..., U_n]$ generated by $S$ contains all
    the forms of degree $k$ (therefore all forms of greater degrees as
    well).] <exc:projective-nullstellensatz>

  #exercise[Let $S = {p_1, p_2, ...}$ be the set of forms of degrees
    $k_1, k_2, ...$ respectively. For given $k_1$, $k_2$, ... the necessary and
    sufficient conditions for $M^"pr" (S)$ to be nonempty can be expressed in
    the form of a system of algebraic relations in the coefficients of forms
    $p_1$, $p_2$, ... each of relations being homogeneous in the coefficients of
    each form. (Each relation contains coefficients of only a finite number of
    forms.)] <exc:elimination-solvability-conditions>

  #exercise[Let $M subset PP^n$ be an irreducible algebraic variety. An ordered
    set $(p_0, p_1, ..., p_m)$ of homogeneous elements of equal degree from
    $K[M]^"pr"$ is _admissible_ if it contains at least one nonzero element.
    Admissible sets $(p_0, p_1, ..., p_m)$ and $(q_0, q_1, ..., q_m)$ are
    _equivalent_ if $p_i q_j = p_j q_i$ for all $i, j$.

    This equivalence relation is
    well-defined.] <exc:admissible-sets-equivalence>

  #exercise[Each equivalence class of admissible sets defines a map (perhaps not
    everywhere defined) $f: M -> PP^m$ according to the following rule: $f$ is
    defined at $x in M$ if the given class contains a set $(p_0, p_1, ..., p_m)$
    such that $p_i (x) != 0$ for some $i$ and in this case
    #source(100)
    $ f(x) = (p_0 (x) ratio p_1 (x) ratio ... ratio p_m (x)). $

    This is a rational map (in the sense of
    @ss:sheaves-of-functions).] <exc:admissible-set-defines-rational-map>

  #exercise[Any rational map $f: M -> PP^m$ is defined in the above sense by an
    equivalence class of admissible sets.] <exc:every-rational-map-admissible>

  #exercise[Any rational map $f: PP^1 -> PP^m$ is a morphism, i.e. is defined
    everywhere.] <exc:rational-maps-of-projective-line>

  #exercise[Find the image of the morphism $PP^1 -> PP^m$ defined by the set
    $(U_0^m, U_0^(m-1) U_1, ..., U_1^m)$.] <exc:rational-normal-curve>

  #exercise[Find the domain and the range of the rational map $f: PP^2 -> PP^2$
    defined by $(U_1 U_2, U_2 U_0, U_0 U_1)$. Prove that
    $f^2 = id$.] <exc:standard-cremona-transformation>

  #exercise[Let $char K != 2$, let $M subset PP^2$ be the conic defined by
    $U_0^2 - U_1^2 - U_2^2 = 0$ and $f: M -> PP^1$ the rational map
    (stereographic projection) defined by the set $(u_0 - u_1, u_2)$, where
    $u_0$, $u_1$, $u_2$ are the images of $U_0$, $U_1$, $U_2$ under the
    canonical homomorphism $K[U_0, U_1, U_2] -> K[M]^"pr"$. Prove that $f$ is an
    isomorphism.] <exc:conic-stereographic-projection>

  #exercise[The image of any morphism of a projective variety into a
    quasiprojective variety is closed. (Hint: make use of
    Exercises~@exc:every-rational-map-admissible and
    @exc:elimination-solvability-conditions.)] <exc:projective-image-closed>

  #exercise[Let $M = M(S)$ be an algebraic variety in $AA^n$ defined by the
    system of equations~@eq:variety-defining-equations and $tilde(M)$ an
    algebraic variety in $PP^n$ defined by the system
    $ U_0^(deg f) f(U_1/U_0, ..., U_n/U_0) = 0 $
    The closure $overline(M)$ of $M$ in $PP^n$ coincides with the union of
    irreducible components of $tilde(M)$ which are not entirely contained in the
    hyperplane $U_0 = 0$.] <exc:projective-closure-homogenization>

  #exercise[In the notation of Exercise~@exc:projective-closure-homogenization,
    if $S = {X_1, X_1^2 + X_2}$ then
    $overline(M) != tilde(M)$.] <exc:homogenized-generators-counterexample>

  #exercise[In any quasiprojective variety the open affine subvarieties
    constitute a basis of its topology.] <exc:open-affine-basis-topology>
]

#hints[
  #hint[@pr:graded-radical-homogeneous, @pr:graded-no-zero-divisors][Consider
    the highest components of nilpotent elements and of zero divisors
    respectively.]

  #hint[@pr:homogeneous-ideal-finite-generators][Deduce from Hilbert's theorem
    on the basis of an ideal.]

  #hint[@pr:projective-irreducible-no-zero-divisors][Is proved similarly to
    Problem~@pr:irreducible-iff-integral-domain.]

  #hint[@pr:projective-rational-function-domain][Let
    $M = M_1 union dots.c union M_q$ be a decomposition of $M$ into irreducible
    components and $I_s$ ($s = 1, ..., q$) the ideal of $K[M]^"pr"$ generated by
    the homogeneous elements that vanish on $M_s$. Since $I_f$ contains
    homogeneous nondivisors of zero, then there exists a homogeneous element
    $q in I_f$ which does not belong to any of the $I_s$. Let $x in M$ be a
    point which does not belong to the set of zeros of $I_f$ and $r in I_f$ a
    homogeneous element such that $r(x) != 0$. Replacing $q$ and $r$ by their
    appropriate powers we may achieve that $deg q = deg r$. An appropriate
    linear combination of $q$ and $r$ is then a nondivisor of zero contained in
    $I_f$ and does not vanish at $x$. Therefore $x in D_f$.]

  #hint[@pr:cone-homothety-invariant-functions][If $f in K(hat(M))$ is invariant
    with respect to homotheties then so is the ideal $I_f$ of
    $K[hat(M)] = K[M]^"pr"$, i.e. $I_f$ is homogeneous. We must prove that it
    contains homogeneous nondivisors of zero. Since it contains some nondivisors
    of #source(
      101,
    )zero, then in the notation of the solution of
    Problem~@pr:projective-rational-function-domain $I_f subset.not I_s$ for any
    $s$. Therefore, for any $s$ there exists a homogeneous element $q_s in I_f$
    such that $q_s in.not I_s$. We may assume (see the solution of
    Problem~@pr:projective-rational-function-domain) that the degrees of all
    these elements are equal. Then their appropriate linear combination is the
    required homogeneous nondivisor of zero.]

  #hint[@pr:projective-rational-functions-components][Make use of
    Problem~@pr:cone-homothety-invariant-functions.]

  #hint[@pr:rational-functions-form-sheaf][To verify axiom (S2) in the affine
    case make use of Problems~@pr:definedness-from-restriction and
    @pr:rational-functions-product-components and in the projective case make
    use of Problems~@pr:projective-restriction-reflects-domain and
    @pr:projective-rational-functions-components.]

  #hint[@pr:rational-sheaf-ambient-restriction][Due to axiom (S2), it suffices
    to prove the statement for an irreducible $M$.]

  #hint[@pr:open-affine-contains-finite-set][Let a given quasiprojective variety
    $M$ be embedded as a subvariety into $PP^n$. By an appropriate projective
    transformation we can achieve that none of the given points and none of the
    irreducible components of $M$ belong to the hyperplane $U_0 = 0$. Then
    $M inter AA^n$ is a dense open subset of $M$ containing all the given
    points. Furthermore in the affine variety $overline(M) inter AA^n$ there
    exists a principal open subset contained in $M inter AA^n$ and containing
    all the given points. This is the desired subvariety of $M$.]

  #hint[@pr:morphism-affine-open-restriction][First, choose a subvariety
    $N_0 subset N$ which contains at least one point of the image of every
    irreducible component of $M$.]

  #hint[@pr:affine-product-universal-property][This is a geometric reformulation
    of the properties of the tensor product of algebras (see
    @ss:direct-product-affine-varieties).]

  #hint[@pr:product-of-subvarieties][Make use of
    Problem~@pr:morphism-into-subspace.]

  #hint[@pr:direct-product-local-criterion][For any morphisms $f: P -> M$ and
    $g: P -> N$ consider their restrictions onto
    $P_(alpha beta) = f^(-1) (M_alpha) inter g^(-1) (N_beta)$ and make use of
    Problem~@pr:morphism-local-on-covering.]

  #hint[@pr:segre-map-injective-closed][If we arrange the homogeneous
    coordinates of a point of $PP^(n m+n+m)$ into an
    $(n + 1) times (m + 1)$-matrix then the image of $eta$ consists of the
    points whose matrix of coordinates is of rank 1 and is determined by the
    conditions that the second order minors of this matrix vanish.]

  #hint[@pr:segre-affine-chart-isomorphism][Follows from the fact that among the
    coordinates of the point
    $ eta((X_1, ..., X_n), (Y_1, ..., Y_m)) in AA^(n m+n+m) $
    some are equal to $X_1, ..., X_n, Y_1, ..., Y_m$ and the remaining ones are
    their products.]

  #hint[@pr:bihomogeneous-closed-subsets][Let the subset $F$ be defined by
    equations of the form mentioned in the conditions of the problem. Suppose
    one of these equations is of the form $p = 0$, where $p$ is a
    quasihomogeneous polynomial of degree $k$ in $U_0, U_1, ..., U_n$ and of
    degree $l$ in $V_0, V_1, ..., V_m$. If, say, $k > l$ then multiplying
    $p = 0$ by all monomials of degree $k - l$ in $V_0, V_1, ..., V_m$ we obtain
    a system of equations equivalent to the initial equation and consisting of
    equations of homogeneity degree $k$ in each group of coordinates. Therefore,
    we may require that each of equations that determine $F$ have the same
    homogeneity degree in both groups of coordinates. The equations of this form
    can be presented as homogeneous equations in the products $U_i V_j$, where
    $i = 0, 1, ..., n$ and $j = 0, 1, ..., m$, yielding the closedness of $F$.
    The converse is obvious.]

  #hint[@pr:nonsimple-multivector-annihilator][#source(102)Let $(x_1, ..., x_l)$
    be a basis of the subspace $V(u)$. Let us complete this basis to a basis of
    the space $V$ by vectors $x_(l+1), ..., x_n$. Let
    $u = sum_(i_1 < dots.c < i_k) u_(i_1 ... i_k) x_(i_1) and dots.c and
    x_(i_k)$. The relations $u and x_i = 0$ for $i = 1, ..., l$ imply that
    $u_(i_1 ... i_k) = 0$ if at least one of $1, ..., l$ is not one of
    $i_1, ..., i_k$. It follows that $l <= k$ and if $l = k$ then
    $u = c x_1 and dots.c and x_l$ for $c in K$.]

  #hint[@pr:grassmannian-closed][Problems~@pr:simple-multivector-subspace and
    @pr:nonsimple-multivector-annihilator imply that a $k$-vector $u$ is simple
    if and only if the rank of the linear map $x |-> u and x$ is not greater
    than $n - k$ (and in this case it equals $n - k$). The latter is equivalent
    to the vanishing of all minors of order $n - k + 1$ of the matrix of this
    map.]

  #hint[@pr:frames-to-grassmannian-morphism][The map $g_k$ is defined by the
    $k$-th order minors of the matrix constructed from the coordinates (in a
    fixed basis) of the first $k$ vectors of a basis.]

  #hint[@pr:grassmannian-incidence-closed][Let $u$ be a simple $k$-vector and
    $v$ a _simple_ $l$-vector. Problem~@pr:simple-multivector-subspace implies
    that $V(u) subset V(v)$ if and only if the rank of the linear map
    $
      V -> Lambda^(k+1) V plus.o Lambda^(l+1) V, wide x |-> (u and x, v and x)
    $
    is not greater than $n - k$ (and in this case it automatically equals
    $n - k$).]

  #hint[@pr:flag-variety-closed][Follows from
    Problem~@pr:grassmannian-incidence-closed.]

  #hint[@pr:flag-variety-irreducible][The proof follows the line of the proof of
    irreducibility of $Gr_k (V)$.]
]
