// Chapter 3, § 3. The Tangent Algebra. Printed pages 122-130.
#import "main-defs.typ": *
#import "statements.typ": *

== The Tangent Algebra <sec:tangent-algebra-algebraic-group>

The tangent Lie algebra can be defined for an algebraic group over an arbitrary
field (see e.g. [@bib:Merzlyakov1987]) but for simplicity we confine ourselves
to $CC$ and $RR$. In these cases no special definition is needed since any
complex or real algebraic group is at the same time a Lie group and its tangent
algebra may be understood in the sense of the Lie group theory.

=== Connectedness of Irreducible Complex Algebraic Groups
<ss:irreducible-complex-groups-connected>
The notion of the tangent algebra can be used to prove the following theorem.

#theorem[Any irreducible complex algebraic group is
  connected.] <th:irreducible-complex-group-connected>

#problem[Any irreducible commutative complex algebraic group is
  connected.] <pr:commutative-irreducible-connected>

_Proof of the theorem._ Let $G$ be an irreducible complex algebraic group,
$frak(g)$ its tangent algebra. Consider some one-parameter subgroups
$P_1, ..., P_n$ of $G$ whose generators generate $frak(g)$. Denote by $G_i$
($i = 1, ..., n$) the closure of $P_i$ in the Zariski topology. This is a
commutative algebraic subgroup. Since its irreducible components are closed in
the real topology, $P_i$ is entirely contained in one irreducible component; but
this means that $G_i$ is irreducible.

The subgroup $hat(G) subset G$ generated by $G_1, ..., G_n$ is closed in the
Zariski topology (Theorem~@th:generated-subgroup-algebraic). Its tangent algebra
contains the tangent algebras of $G_1, ..., G_n$ and, in particular, the
generators of $P_1, ..., P_n$; therefore it coincides with $frak(g)$. Thus
$dim hat(G) = dim G$ and therefore $hat(G) = G$.

By Problem~@pr:commutative-irreducible-connected the subgroups $G_1, ..., G_n$
are connected and therefore, contained in the unit component of $G$. But by what
we have already proved they generate $G$. Therefore $G$ is connected.#qed-mark

Thus, for a complex algebraic group its irreducibility is equivalent to its
connectedness in the real topology. Notice that since irreducible components of
an algebraic group do not intersect, its irreducibility is equivalent to its
connectedness in the Zariski topology. All this being taken into account, we
#source(138)will, speaking about complex algebraic groups, say #idx(
  "algebraic group",
  "connected",
)“connected” instead of “irreducible” in order to avoid confusion with the
irreducibility of linear groups which means the absence of nontrivial invariant
subspaces.

=== The Rational Structure on the Tangent Algebra of a Torus
<ss:rational-structure-torus-algebra>
Since a complex algebraic torus is a commutative Lie group, the Lie algebra
structure on its tangent space is trivial. However, this space is naturally
endowed with the structure of another kind.

Let $T$ be an $n$-dimensional torus and $frak(t)$ its tangent algebra. The
differential $d chi$ (at the unit) of any character $chi in cal(X)(T)$ is a
linear function on $frak(t)$. Clearly,
$ d(chi_1 + chi_2) = d chi_1 + d chi_2. $ <eq:character-differential-additive>
(Recall that $chi_1 + chi_2$ is by definition the product of functions $chi_1$
and $chi_2$ on $T$. The sum on the right-hand side of
identity~@eq:character-differential-additive is the usual sum of linear
functions on $frak(t)$.)

#problem[If $(epsilon_1, ..., epsilon_n)$ is a basis of $cal(X)(T)$ then
  $(d epsilon_1, ..., d epsilon_n)$ is a basis of the space $frak(t)^*$ of
  linear functions on $frak(t)$.] <pr:character-differentials-basis>

For any additive number group $A$, set
$
  frak(t)(A) & = {xi in frak(t) | d chi(xi) in A "for all" chi in cal(X)(T)} \
             & = {xi in frak(t) | d epsilon_i (xi) in A "for" i = 1, ..., n}.
$
If $k$ is a number field, then $frak(t)(k)$ is a $k$-form of the space $frak(t)$
(see the definition in @ss:forms-of-vector-spaces-algebras).

In the sequel, while speaking about the field over which the linear maps and
subspaces of the tangent algebras of tori are defined we will have these very
forms in mind.

#problem[The differential of any homomorphism (in particular, any automorphism)
  of a torus is defined over $QQ$ (and the more so over any other number
  field).] <pr:torus-differential-rational>

#problem[The tangent algebras of algebraic subgroups of a torus are exactly the
  subspaces of its tangent algebra which are defined over
  $QQ$.] <pr:torus-subgroups-rational-subspaces>

=== Algebraic Subalgebras <ss:algebraic-subalgebras>
Let $G$ be a complex algebraic group. A subalgebra $frak(h) subset frak(g)$ is
called #idx("subalgebra", "algebraic")_algebraic_ if it is the tangent algebra
of an algebraic subgroup $H subset G$ or, in other words, if the corresponding
connected virtual Lie subgroup of $G$ is an algebraic subgroup. As shown e.g. in
Problem~@pr:torus-subgroups-rational-subspaces, certainly not any subalgebra is
algebraic.

In this subsection we will find certain sufficient conditions for algebraicity
of a subalgebra (and therefore sufficient conditions for this subalgebra to be
the tangent algebra of a Lie subgroup). The existence of such conditions is one
of the reasons why algebraic group theory is useful in the Lie group theory.

#problem[The derived algebra of an algebraic subalgebra is an algebraic
  subalgebra.] <pr:derived-of-algebraic-is-algebraic>

#theorem[#source(139)Let an algebraic subgroup $H$ of a complex algebraic group
  $G$ be generated by connected algebraic subgroups $H_alpha$, $alpha in A$ for
  a set $A$. Then the tangent algebra $frak(h)$ of $H$ is generated by the
  tangent algebras $frak(h)_alpha$ of
  $H_alpha$'s.] <th:generated-subgroup-tangent-algebra>

#problem[Prove this theorem.] <pr:prove-generated-subgroup-tangent-algebra>

#corollary[The subalgebra generated by any family of algebraic subalgebras is
  algebraic.]

Obviously the intersection of any family of algebraic subgroups is an algebraic
subgroup. Therefore for any subalgebra $frak(h) subset frak(g)$ there exists the
smallest algebraic subalgebra containing $frak(h)$. It is called the #idx(
  "algebraic closure (of a subalgebra)",
)_algebraic closure_ of $frak(h)$ and is denoted by $frak(h)^a$.

#problem[$frak(h)^a$ is the tangent algebra of the closure (in the Zariski
  topology) of the connected virtual Lie subgroup $H subset G$ corresponding to
  $frak(h)$.] <pr:algebraic-closure-zariski-closure>

The properties of the algebraic closure are similar to those of the Malcev
closure (see @ss:malcev-closures).

#theorem[Let $frak(h)$ be a subalgebra of the tangent algebra of a complex
  algebraic group $G$ and $frak(h)^a$ its algebraic closure. Then
  $(frak(h)^a)' = frak(h)'$.] <th:algebraic-closure-same-derived>

This theorem is proved in exactly the same way as
Theorem~@th:malcev-closure-derived-algebra (the subgroups $H_1$ and $H_2$ turn
out to be algebraic: see Example~@exm:subspace-stabilizer-algebraic).

#corollary[The derived algebra of any subalgebra is an algebraic subalgebra. In
  particular, any subalgebra coinciding with its derived algebra is
  algebraic.] <cor:derived-subalgebra-algebraic>

#corollary[The algebraic closure of a commutative (solvable) algebra is
  commutative (solvable).] <cor:algebraic-closure-preserves-solvable>

Maximal solvable subalgebras of $frak(g)$ are called its #idx(
  "Borel subalgebra",
)_Borel subalgebras._

#problem[Any Borel subalgebra of $frak(g)$ is the tangent algebra of a Borel
  subgroup of $G$.] <pr:borel-subalgebra-of-borel-subgroup>

#problem[The algebraic closure of an ideal is an
  ideal.] <pr:algebraic-closure-of-ideal>

#problem[The radical of $G$ is an algebraic
  subgroup.] <pr:radical-algebraic-subgroup>

A #idx("Lie algebra", "linear")linear Lie algebra $frak(h) subset frak(g l)(V)$
is called #idx(
  "Lie algebra",
  "linear",
  "algebraic",
)_algebraic_ if it is algebraic as a subalgebra of the tangent algebra of
$GL(V)$, i.e. if it is the tangent algebra of an algebraic linear group
$H subset GL(V)$.

All that has been stated in this subsection surely holds for $G = GL(V)$. In
particular, Corollary~@cor:derived-subalgebra-algebraic of
Theorem~@th:algebraic-closure-same-derived enables us to conclude that any
linear Lie algebra coinciding with its derived algebra is algebraic.

=== The Algebraic Structure on Certain Complex Lie Groups
<ss:algebraic-structure-complex-lie-groups>

#theorem[Let $G$ be a connected complex algebraic group coinciding with its
  commutator group. Then any differentiable homomorphism of $G$ into a complex
  algebraic group $H$ is
  polynomial.] <th:perfect-group-homomorphisms-polynomial>

#proof[#source(140)Let $f: G -> H$ be a differentiable homomorphism. Consider
  its graph $Gamma = {(g, f(g)) in G times H: g in G}$. Clearly $Gamma$ is a
  connected Lie subgroup of $G times H$ and its projection onto $G$ is
  isomorphic to $Gamma$. Its tangent algebra is isomorphic to the tangent
  algebra of $G$, hence it coincides with its derived algebra. Therefore $Gamma$
  is an algebraic subgroup of $G times H$
  (Corollary~@cor:derived-subalgebra-algebraic of
  Theorem~@th:algebraic-closure-same-derived). By
  Theorem~@th:bijective-homomorphism-isomorphism the map $g |-> (g, f(g))$,
  inverse to the projection $Gamma -> G$ is polynomial. Therefore $f$ is also
  polynomial.]

An #idx("algebraic structure (on a complex Lie group)")#idx(
  "structure",
  "algebraic",
)_algebraic structure on a complex Lie group $G$_ is an algebraic group
structure on $G$ compatible with the Lie group structure, i.e. generating the
same Lie group structure. Since any algebraic group has a faithful linear
representation, for the existence of an algebraic structure on a complex Lie
group it is necessary that this group has a faithful linear representation (as a
Lie group).

#theorem[A connected complex Lie group coinciding with its commutator group and
  having a faithful linear representation admits a unique algebraic
  structure.] <th:perfect-lie-group-algebraic-structure>

#problem[Prove this theorem.] <pr:prove-perfect-lie-group-structure>

=== Engel's Theorem <ss:engel-theorem>
In this subsection we consider vector spaces and Lie algebras over an arbitrary
field.

A linear Lie algebra $frak(g) subset frak(g l)(V)$ is called #idx(
  "Lie algebra",
  "linear",
  "unipotent",
)_unipotent_ if all its operators are nilpotent. (The origin of this term will
become clear in the sequel: see
Problem~@pr:unipotent-group-iff-unipotent-algebra.)

#problem[If a linear Lie algebra $frak(g) subset frak(g l)(V)$ is unipotent then
  so is the linear Lie algebra $ad frak(g) subset frak(g l)(frak(g))$.]
<pr:unipotent-algebra-adjoint-unipotent>

#theorem(title: [#idx("Engel’s theorem")Engel's theorem])[Let
  $frak(g) subset frak(g l)(V)$ be a unipotent linear Lie algebra. There exists
  a nonzero vector in $V$ annihilated by all operators of $frak(g)$.] <th:engel>

_Proof_ will be carried out by induction in $dim frak(g)$. Suppose
$dim frak(g) > 0$ and the statement holds for all linear Lie algebras whose
dimensions are less than $dim frak(g)$. Let $frak(h)$ be a maximal subalgebra of
$frak(g)$. Let us prove that $frak(h)$ is an ideal of codimension 1.

Consider the linear representation $rho$ of $frak(h)$ in $frak(g)\/frak(h)$
induced by the adjoint representation of $frak(g)$.
Problem~@pr:unipotent-algebra-adjoint-unipotent implies that the linear Lie
algebra $rho(frak(h))$ is unipotent. By the inductive hypothesis there exists a
nonzero vector in $frak(g)\/frak(h)$ annihilated by all operators of
$rho(frak(h))$, i.e. there exists an element $C in frak(g) without frak(h)$ such
that $[frak(h), C] subset frak(h)$. But then $frak(h) + chevron.l C chevron.r$
is a subalgebra of $frak(g)$ and the maximality of $frak(h)$ implies that
$frak(h) + chevron.l C chevron.r = frak(g)$. With the above this means that
$frak(h)$ is an ideal of codimension one.

Consider the subspace $V_0 = {v in V: frak(h) v = 0} subset V$. By the inductive
hypothesis $V_0 != 0$. The fact that $frak(h)$ is an ideal in $frak(g)$ easily
implies that $V_0$ is $frak(g)$-invariant. Let $C$ be any element of $frak(g)$
which does not belong to $frak(h)$. Since $C$ is nilpotent and $V_0$ is
invariant with respect to $C$, there exists a nonzero vector in $V_0$
annihilated by $C$. Clearly, this vector is annihilated by all the operators of
$frak(g)$.#qed-mark

#corollary[Under the conditions of the theorem there exists a basis of $V$ with
  respect to which all operators of $frak(g)$ are expressed by niltriangular
  matrices.] <cor:engel-niltriangular-basis>

#source(141)This corollary is deduced from the theorem like the similar
corollary of Lie's theorem, cf. @ss:lie-theorem. This in turn implies

#corollary[Any unipotent Lie algebra is
  solvable.] <cor:unipotent-algebra-solvable>

Engel's theorem implies not only the solvability but also the nilpotency of any
unipotent linear Lie algebra. (For the definition of a nilpotent Lie algebra see
Exercise~@exc:nilpotent-group-iff-algebra.) In fact, the Lie algebra of
niltriangular matrices is clearly nilpotent.
Corollary~@cor:engel-niltriangular-basis of Engel's theorem shows that any
unipotent linear Lie algebra is isomorphic to some subalgebra of the Lie algebra
of niltriangular matrices and therefore is also nilpotent. However, the converse
is false: there exist nilpotent Lie algebras which are not unipotent, e.g. the
Lie algebra of triangular matrices with equal elements on the diagonal.

=== Unipotent Algebraic Linear Groups <ss:unipotent-algebraic-linear-groups>
Let $V$ be a complex vector space.

#problem[An operator $X in frak(g l)(V)$ is nilpotent (semisimple) if and only
  if $exp t X$ is unipotent (semisimple) for any
  $t in CC$.] <pr:exp-semisimple-nilpotent-criterion>

For any nilpotent $X in frak(g l)(V)$ the linear group ${exp t X: t in CC}$ is
algebraic, see @ss:commutative-unipotent-linear-groups. Clearly, its tangent
algebra is generated by $X$. Therefore any one-dimensional unipotent linear Lie
algebra is algebraic.

#problem[Any unipotent linear Lie algebra is
  algebraic.] <pr:unipotent-lie-algebra-algebraic>

#problem[A connected algebraic linear group is unipotent (see
  @ss:commutative-unipotent-linear-groups) if and only if its tangent algebra is
  unipotent.] <pr:unipotent-group-iff-unipotent-algebra>

This explains the term “unipotent” applied to the linear Lie algebras.

#theorem[Any unipotent complex algebraic linear group $G subset GL(V)$ is
  solvable and is expressed in some basis by unitriangular matrices. The map
  $exp: frak(g) -> G$ is an isomorphism of algebraic
  varieties.] <th:unipotent-group-exp-isomorphism>

#problem[Prove this theorem.] <pr:prove-unipotent-group-exp-isomorphism>

Notice that the last statement of the theorem makes sense independently of a
linear representation of $G$.

=== The Jordan Decomposition in the Tangent Algebra of an Algebraic Group
<ss:jordan-decomposition-tangent-algebra>
Let $G$ be a complex algebraic group. For any $xi in frak(g)$ denote by $G(xi)$
the smallest algebraic subgroup of $G$ whose tangent algebra contains $xi$, i.e.
the closure (in the Zariski topology) of the subgroup ${exp t xi: t in CC}$.
This is an irreducible commutative algebraic group. By Corollary of
Theorem~@th:commutative-algebraic-group-structure it splits into the direct
product of a torus and a vector group.

An element $xi in frak(g)$ is called #idx(
  "Element",
  "semisimple (of an algebraic Lie algebra)",
)_semisimple_ (#idx(
  "Element",
  "nilpotent (of an algebraic Lie algebra)",
)_nilpotent_) if $G(xi)$ is a torus (a vector group).

#problem[Let $f: G -> H$ be an algebraic group homomorphism. If $xi in frak(g)$
  is semisimple (nilpotent) then so is
  $d f(xi) in frak(h)$.] <pr:differential-semisimple-nilpotent>

#problem[Let $R$ be a linear representation of $G$. If $xi in frak(g)$ is
  semisimple (nilpotent) then so is the linear operator
  $d R(xi)$.] <pr:representation-semisimple-nilpotent>

#theorem[#source(142)Any element $xi$ of the tangent algebra $frak(g)$ of a
  complex algebraic group $G$ can be uniquely presented in the form of the sum
  of commuting semisimple and nilpotent elements $xi_s$,
  $xi_n$.] <th:jordan-decomposition-tangent-algebra>

The elements $xi_s$ and $xi_n$ are called the _semisimple_ and _nilpotent_ parts
of $xi$ respectively and the decomposition $xi = xi_s + xi_n$ is called its
#idx("Jordan decomposition in an algebraic Lie algebra")_Jordan decomposition._

#problem[Prove Theorem~@th:jordan-decomposition-tangent-algebra.]
<pr:prove-jordan-decomposition-tangent>

#problem[Let $R$ be a locally faithful (i.e. with a finite kernel) linear
  representation of $G$ and $xi in frak(g)$. If $d R(xi)$ is semisimple
  (nilpotent) then so is $xi$.] <pr:locally-faithful-reflects-semisimple>

Problems~@pr:representation-semisimple-nilpotent and
@pr:locally-faithful-reflects-semisimple show in particular that semisimple and
nilpotent elements of the tangent algebra of $GL(V)$ are the same as semisimple
and nilpotent linear operators.

#problem[Let $f: G -> H$ be an algebraic group homomorphism. For any semisimple
  (nilpotent) element $eta in d f(frak(g))$ its pre-image $(d f)^(-1) (eta)$
  contains a semisimple (nilpotent) element.] <pr:semisimple-nilpotent-preimage>

=== The Tangent Algebra of a Real Algebraic Group
<ss:tangent-algebra-real-algebraic-group>
Let $G$ be a real algebraic group, $frak(g)$ its tangent algebra (as of a real
Lie group), $G(CC)$ its complexification, see @ss:algebraic-group-definitions.

The tangent algebra of $G(CC)$ coincides with the complexification $frak(g)(CC)$
of $frak(g)$, see @ss:analytic-structure-of-varieties. If $tau$ is the complex
conjugation on $G(CC)$ then $d tau$ is the complex conjugation on $frak(g)(CC)$.

#problem[A connected algebraic subgroup of $G(CC)$ is a complexification of an
  algebraic subgroup of $G$ if and only if its tangent algebra is defined over
  $RR$ (as a subspace of
  $frak(g)(CC)$).] <pr:complexification-subgroup-criterion>

A Lie subalgebra $frak(h) subset frak(g)$ is called #idx(
  "subalgebra",
  "algebraic",
)_algebraic_ if it is the tangent algebra of an algebraic subgroup $H subset G$.
For any subalgebra $frak(h) subset frak(g)$ there exists the smallest algebraic
subalgebra containing $frak(h)$. It is called the #idx(
  "algebraic closure (of a subalgebra)",
)_algebraic closure_ of $frak(h)$ and is denoted by $frak(h)^a$.

#problem[The subalgebra $frak(h) subset frak(g)$ is algebraic if and only if its
  complexification $frak(h)(CC)$ is an algebraic subalgebra of $frak(g)(CC)$. In
  any case
  $frak(h)^a (CC) = frak(h)(CC)^a$.] <pr:real-algebraic-subalgebra-criterion>

Due to this fact most of the results of @ss:algebraic-subalgebras are routinely
carried over to the real setting. In particular, in this way we obtain that the
following subalgebras of $frak(g)$ are algebraic:

1) the derived algebra of any subalgebra; in particular, any subalgebra
coinciding with its derived algebra;

2) a subalgebra generated by any family of algebraic subalgebras;

3) the radical of $frak(g)$.

=== The Union of Borel Subgroups and the Centralizers of Tori
<ss:borel-union-torus-centralizers>
Let $G$ be a connected complex algebraic group, $frak(g)$ its tangent algebra.

#problem[Any element of $frak(g)$ is contained in some of its Borel
  subalgebras.] <pr:borel-subalgebras-cover-algebra>

#problem[#source(143)The union of all Borel subgroups of $G$ is an épais subset
  in $G$.] <pr:borel-subgroups-union-epais>

Actually, the following statement holds:

#theorem[Every element of a connected complex algebraic group is contained in
  some of its Borel subgroups.] <th:borel-subgroups-cover-group>

#proof[Let $U$ be the union of all Borel subgroups of $G$. It follows from
  Problem~@pr:borel-subgroups-union-epais that $U$ is dense in $G$ in the real
  topology. Therefore it suffices to prove that $U$ is closed in the real
  topology.

  We have $U = union.big_(g in G) g B g^(-1)$, where $B$ is a fixed Borel
  subgroup of $G$. Let the sequence of elements $g_n b_n g_n^(-1)$ ($g_n in G$,
  $b_n in B$) converge to some $g in G$. Since $G\/B$ is compact
  (Theorem~@th:borel-conjugate-quotient-projective), then, passing to a
  subsequence, we may assume that $g_n = g'_n c_n$, where $g'_n -> h in G$ and
  $c_n in B$, but then
  $ c_n b_n c_n^(-1) -> h^(-1) g h = b in B $
  hence, $g = h b h^(-1) in U$.]

The combination of this theorem with
Theorem~@th:solvable-semisimple-conjugate-torus and Corollary of
Theorem~@th:borel-conjugate-quotient-projective yields the following two
corollaries.

#corollary[Every semisimple element of $G$ is contained in a
  torus.] <cor:semisimple-element-in-torus>

#corollary[Every central semisimple element of $G$ is contained in the
  intersection of all maximal tori of
  $G$.] <cor:central-semisimple-in-maximal-tori>

#problem[Let $S subset G$ be a torus and $g in G$ a semisimple element commuting
  with it. Then there exists a torus $T subset G$ containing $S$ and
  $g$.] <pr:torus-with-commuting-semisimple>

#theorem[The centralizer $Z(S)$ of any torus $S$ in a connected complex
  algebraic group $G$ is connected.] <th:torus-centralizer-connected>

#problem[Prove the theorem.] <pr:prove-torus-centralizer-connected>

#exercises[
  #exercise[The subgroup ${(e^z, e^(i z)): z in CC} subset (CC^*)^2$ is a Lie
    subgroup but not an algebraic
    subgroup.] <exc:nonalgebraic-subgroup-of-torus>

  #exercise[Any differentiable linear representation of a complex algebraic
    torus is polynomial.] <exc:torus-representations-polynomial>

  #exercise[Give an example of a nonpolynomial differentiable linear
    representation of $CC$.] <exc:nonpolynomial-additive-representation>

  #exercise[The complex Lie group $CC\/(ZZ + i ZZ)$ does not admit an algebraic
    structure. (For a broader interpretation of the notion of an algebraic
    group, which does not require that the group variety is affine, this Lie
    group admits an algebraic structure. However, there are examples of complex
    Lie groups which do not admit an algebraic structure in this broader sense
    either.)] <exc:complex-torus-not-algebraic>

  #exercise[The complex Lie group $CC times CC^*$ admits a continuum of
    different algebraic structures.] <exc:continuum-algebraic-structures>

  #exercise[An algebraic normal subgroup of a connected complex algebraic group
    $G$ which is a quasitorus is contained in the center of
    $G$.] <exc:normal-quasitorus-central>

  #exercise[#source(144)An element $xi$ of the tangent algebra of a complex
    algebraic group $G$ is semisimple if and only if $exp xi in G$ is
    semisimple.] <exc:semisimple-iff-exp-semisimple>

  #exercise[A Lie algebra $frak(g)$ (over an arbitrary field) is nilpotent if
    and only if the linear Lie algebra $ad frak(g)$ is
    unipotent.] <exc:nilpotent-iff-adjoint-unipotent>

  #exercise[The derived algebra of any solvable subalgebra of the tangent
    algebra of a complex algebraic group is unipotent (i.e. all its elements are
    nilpotent).] <exc:solvable-derived-algebra-unipotent>

  #exercise[Given a linear operator $X in frak(g l)(V)$ let $frak(g)(X)$ be the
    smallest algebraic linear Lie algebra which contains it, i.e. the algebraic
    closure of the one-dimensional linear Lie algebra $chevron.l X chevron.r$.
    If $X = X_s + X_n$ is the additive Jordan decomposition of $X$ then
    $frak(g)(X) = frak(g)(X_s) plus.o chevron.l X_n chevron.r$.]
  <exc:operator-algebraic-closure-jordan>

  #exercise[Under the notation of
    Exercise~@exc:operator-algebraic-closure-jordan if $X$ is expressed in some
    basis by a diagonal matrix $diag(x_1, ..., x_n)$ then $frak(g)(X)$ consists
    of all operators which in the same basis are expressed by matrices of the
    form $diag(y_1, ..., y_n)$, where $y_1, ..., y_n$ satisfy all linear
    equations with integer coefficients satisfied by
    $x_1, ..., x_n$.] <exc:diagonal-closure-integer-relations>

  #exercise[Under the notation of @ss:jordan-decomposition-tangent-algebra the
    dimension of the vector factor of $G(xi)$ does not
    exceed 1.] <exc:one-parameter-closure-vector-factor>
]

#hints[
  #hint[@pr:torus-subgroups-rational-subspaces][Make use of the description of
    algebraic subgroups of a torus given in
    Theorem~@th:algebraic-subgroups-of-torus.]

  #hint[@pr:derived-of-algebraic-is-algebraic][Follows from
    Theorems~@th:commutator-subgroup-irreducible and
    @th:commutator-subgroup-tangent-algebra.]

  #hint[@pr:prove-generated-subgroup-tangent-algebra][Let
    $hat(frak(h)) subset frak(h)$ be a subalgebra generated by $frak(h)_alpha$,
    $alpha in A$, and $hat(H) subset H$ the corresponding connected virtual Lie
    subgroup (cf. Theorem~@th:subalgebra-has-virtual-subgroup). For any
    $alpha in A$ we have $hat(frak(h)) supset frak(h)_alpha$, hence
    $hat(H) supset H_alpha$. Therefore $hat(H) = H$ and
    $hat(frak(h)) = frak(h)$.]

  #hint[@pr:borel-subalgebra-of-borel-subgroup][First prove that any Borel
    subalgebra is an algebraic subalgebra.]

  #hint[@pr:algebraic-closure-of-ideal][Solution is similar to that of
    Problem~@pr:malcev-closure-of-ideal.]

  #hint[@pr:radical-algebraic-subgroup][Prove that the radical of $frak(g)$ is
    an algebraic subalgebra.]

  #hint[@pr:unipotent-algebra-adjoint-unipotent][It is subject to a
    straightforward verification that if $X^m = 0$ then $(ad X)^(2m - 1) = 0$.]
  <hint:unipotent-algebra-adjoint-unipotent>

  #hint[@pr:exp-semisimple-nilpotent-criterion][First prove the “only if” part.
    After this prove that $exp t X = (exp t X_s)(exp t X_n)$ is the
    (multiplicative) Jordan decomposition of $exp t X$.]

  #hint[@pr:unipotent-lie-algebra-algebraic][Follows from the remark made just
    before the formulation of the problem and Corollary of
    Theorem~@th:generated-subgroup-tangent-algebra.]

  #hint[@pr:unipotent-group-iff-unipotent-algebra][The “if” part is proved with
    the help of Corollary~@cor:engel-niltriangular-basis of Engel's theorem. The
    “only if” part follows from Problem~@pr:exp-semisimple-nilpotent-criterion.]

  #hint[@pr:prove-unipotent-group-exp-isomorphism][The first part of the theorem
    follows from Problem~@pr:unipotent-group-iff-unipotent-algebra and
    corollaries of Engel's theorem. The surjectivity of $exp: frak(g) -> G$
    follows from the fact that together with $A$ the group $G$ contains the
    subgroup $G(A) = {exp t X: t in CC}$, where $X = log(A)$, cf.
    Theorem~@th:unipotent-closure-additive-group. The remaining properties of
    the map $exp$ are proved with the help of
    Problem~@pr:exp-log-nilpotent-unipotent.]

  #hint[@pr:differential-semisimple-nilpotent][Notice that the element $d f(xi)$
    is contained in the tangent algebra of the algebraic subgroup
    $f(G(xi)) subset H$.]

  #hint[@pr:representation-semisimple-nilpotent][Make use of the hint to
    Problem~@pr:differential-semisimple-nilpotent and of
    Problem~@pr:exp-semisimple-nilpotent-criterion.]

  #hint[@pr:prove-jordan-decomposition-tangent][Let $G(xi) = T times U$, where
    $T$ is a torus and $U$ a vector group. If
    $frak(g)(xi) = frak(t) plus.o frak(u)$ #source(145)is the corresponding
    decomposition of the tangent algebra then the decomposition
    $xi = xi_s + xi_n$, where $xi_s in frak(t)$ and $xi_n in frak(u)$, is the
    desired one. The uniqueness of the desired decomposition follows, due to
    Problem~@pr:representation-semisimple-nilpotent, from the uniqueness of the
    additive Jordan decomposition of a linear operator.]

  #hint[@pr:locally-faithful-reflects-semisimple][Consider the Jordan
    decomposition of $xi$ and make use of
    Problem~@pr:representation-semisimple-nilpotent.]

  #hint[@pr:semisimple-nilpotent-preimage][Take any pre-image and consider its
    Jordan decomposition.]

  #hint[@pr:complexification-subgroup-criterion][
    Problem~@pr:group-real-form-from-involution implies that a connected
    algebraic subgroup $H subset G(CC)$ is a complexification of an algebraic
    subgroup of $G$ if and only if $tau(H) = H$ and this, in turn, is equivalent
    to the fact that $d tau(frak(h)) = frak(h)$. Next, make use of
    Problem~@pr:real-subspace-conjugation-invariant.]

  #hint[@pr:real-algebraic-subalgebra-criterion][Notice that if the subalgebra
    $frak(h)(CC)$ is algebraic then the corresponding connected algebraic
    subgroup of $G(CC)$ is according to
    Problem~@pr:complexification-subgroup-criterion a complexification of an
    algebraic subgroup of $G$. The second statement follows from the first one.]

  #hint[@pr:torus-with-commuting-semisimple][By
    Corollary~@cor:semisimple-element-in-torus of
    Theorem~@th:borel-subgroups-cover-group $g$ is contained in a torus. Let
    $H subset G$ be the subgroup generated by this torus and $S$. This is a
    connected algebraic subgroup by Theorem~@th:generated-subgroup-algebraic and
    $g$ belongs to its center. Let $T$ be a maximal torus of $H$ containing $S$.
    By Corollary~@cor:central-semisimple-in-maximal-tori of
    Theorem~@th:borel-subgroups-cover-group $T in.rev g$.]

  #hint[@pr:prove-torus-centralizer-connected][It suffices to prove that any
    semisimple element of $Z(S)$ is contained in $Z(S)^0$ but this follows from
    Problem~@pr:torus-with-commuting-semisimple.]
]
