// Chapter 4, § 3. Existence and Uniqueness Theorems. Printed pages
// 181-201. The section begins in the middle of page 181, after the Hints
// of § 2 (whose file anchors page 181); its Hints end on page 201, and
// page 202 opens § 4.
#import "main-defs.typ": *
#import "statements.typ": *
#import "diagrams/cd.typ": ar, cd
#import "diagrams/dynkin.typ": bond, dynkin, gap, v

== Existence and Uniqueness Theorems <sec:existence-uniqueness-theorems>

In this section we will prove that any Cartan matrix (see @ss:cartan-matrices)
corresponds to the root system of a unique (up to an isomorphism) semisimple
complex Lie algebra. After that we will study connected complex semisimple Lie
groups globally. In particular, we will prove that all these groups are
algebraic and we will classify them up to an isomorphism. We will also describe
irreducible finite-dimensional linear representations of connected complex
semisimple Lie groups. Everywhere except
@ss:free-lie-algebras-generators-relations the ground field is $CC$.

=== Free Lie Algebras, Generators and Defining Relations
<ss:free-lie-algebras-generators-relations>
#source(197)Let $frak(a)$ be a Lie algebra over $k$, $X subset frak(a)$ a
subset. Denote by $frak(b)$ the intersection of all subalgebras of $frak(a)$
containing $X$. Clearly, $frak(b)$ is the smallest subalgebra of $frak(a)$
containing $X$; it is called the _subalgebra_ of $frak(a)$ _generated by
$X$_. In particular, if $frak(b) = frak(a)$ then one says that $X$ is a _system
of generators_ of $frak(a)$; this means that there is no proper subalgebra of
$frak(a)$ containing $X$. In what follows we will consider the case when
$X = {x_1, ..., x_n}$ is finite. A Lie algebra admitting a finite system of
generators is called #idx(
  "Lie algebra",
  "finitely generated",
)_finitely generated._ For instance, any finite-dimensional Lie algebra is
finitely generated.

#problem[A set $x_1, ..., x_n$ is a system of generators of a Lie algebra
  $frak(a)$ if and only if each element of $frak(a)$ is a linear combination of
  elements of the form
  $
    [..., [[x_(i_1), x_(i_2)], x_(i_3)], ...], x_(i_m)] wide
    (1 <= i_1, ..., i_m <= n).
  $ <eq:left-normed-commutators>] <pr:generators-via-left-normed-commutators>

Let us now construct an important example of a Lie algebra with a given system
of generators $X = {x_1, ..., x_n}$. Define by induction non-associative words
in the alphabet $X$ in the following way: a word of length 1 is any element
$x_i in X$; a word of length $m > 1$ is a pair $(y, z)$, where $y$ and $z$ are
words of length $p$ and $q$ respectively for $p >= 1$, $q >= 1$, $p + q = m$.
Thus the set $X_1$ of words of length 1 coincides with $X$ and the set $X_m$ of
words of length $m > 1$ is defined by induction as follows:
$ X_m = product.co_(p + q = m) X_p times X_q. $
In the set $M_X = product.co_(m >= 1) X_m$ there is a binary algebraic operation
assigning to each $y in X_p$ and $z in X_q$ the word $(y, z) in X_(p + q)$. Let
us consider the corresponding algebra $k[M_X]$ over the field $k$. This is the
vector space over $k$ consisting of elements of the form $sum_(z in M_X) c_z z$,
where $c_z in k$, $c_z = 0$ for all $z$ except a finite number, and endowed with
a multiplication which extends by linearity the operation in $M_X$. The algebra
$k[M_X]$ is called the #idx(
  "algebra",
  "free",
  "generated by a set",
)_free algebra_ over $k$ _generated by the set $X$_. The set $M_X$ is its basis
over $k$.

#problem[Let $A$ be any algebra over $k$ with fixed elements $a_1, ..., a_n$.
  Then there exists a unique algebra homomorphism $phi: k[M_X] -> A$, such that
  $phi(x_i) = a_i$ for any
  $i = 1, ..., n$.] <pr:free-algebra-universal-property>

Denote by $I$ the two-sided ideal of $k[M_X]$, generated by elements of the form
$u u$ and $(u v) w + (v w) u + (w u) v$, where $u, v, w in k[M_X]$.#ed-note[In
  the book $I$ is generated only by the elements $x_i x_i$ and the Jacobi sums
  of the generators $x_i, x_j, x_k$. The elements of degree 2 of such an ideal
  are linear combinations of the $x_i x_i$, so $x_1 x_2 + x_2 x_1 in.not I$, and
  $k[M_X]\/I$ is not a Lie algebra. See #cite(<Bahturin2021>, form: "full"),
  2.2.4.] The algebra
$ frak(l)(X) = frak(l)(x_1, ..., x_n) = k[M_X]\/I $
is, clearly, a Lie algebra. It is called the #idx("Lie algebra", "free")_free
Lie algebra generated by $X$_ (over $k$).

#problem[Let $frak(a)$ be any Lie algebra over $k$, with fixed elements
  $a_1, ..., a_n$. Then there exists a unique Lie algebra homomorphism
  $phi: frak(l)(x_1, ..., x_n) -> frak(a)$, such that $phi(x_i) = a_i$ for any
  $i = 1, ..., n$. Every finitely generated Lie algebra is isomorphic to a
  quotient of a (finitely generated) free Lie
  algebra.] <pr:free-lie-algebra-universal-property>

#source(198)Let $frak(a)$ be again an arbitrary Lie algebra over $k$ and $X$ a
subset of $frak(a)$. Consider the intersection $frak(i)$ of all ideals of
$frak(a)$ containing $X$; this is the smallest ideal of $frak(a)$ containing
$X$. We say that $frak(i)$ is _generated_ by $X$.

In particular, let $(f_i)_(i in I)$ be a family of elements of a free Lie
algebra $frak(l)(x_1, ..., x_n)$ and $frak(i)$ the ideal of
$frak(l)(x_1, ..., x_n)$ generated by this family. The quotient algebra
$frak(l)(x_1, ..., x_n)\/frak(i)$ is called the Lie algebra with _generators_
$y_j = x_j + frak(i)$ ($j = 1, ..., n$) and #idx(
  "relations",
  "defining",
)_defining relations_ $f_i (y_1, ..., y_n) = 0$ ($i in I$).

=== Uniqueness Theorems <ss:uniqueness-theorems>
Let $frak(g)$ be a complex semisimple Lie algebra, $frak(t)$ its maximal
diagonalizable subalgebra, $Pi = {alpha_1, ..., alpha_l}$ a system of simple
roots of $frak(g)$ with respect to $frak(t)$. Under the notation of
@ss:weight-and-root-decompositions[°] and @ss:three-dimensional-subalgebras[°]
set
$
  h_i = h_(alpha_i), e_i = e_(alpha_i), f_i = e_(-alpha_i) wide
  (i = 1, ..., l).
$

Let $A = (a_(i j))$ be the matrix of $Pi$; we will call it the #idx(
  "Cartan matrix",
)_Cartan matrix_ of $frak(g)$.

#problem[The elements $h_i, e_i, f_i$ ($i = 1, ..., l$) form the system of
  generators of $frak(g)$ and satisfy
  $
    [h_i, h_j] = 0, \
    [h_i, e_j] - a_(j i) e_j = 0, wide [h_i, f_j] + a_(j i) f_j = 0, \
    [e_i, f_i] - h_i = 0, wide [e_i, f_j] = 0 quad "for" quad i != j.
  $ <eq:chevalley-generator-relations>] <pr:canonical-generators-relations>

The system ${h_i, e_i, f_i: i = 1, ..., l}$ is called the #idx(
  "system of generators",
)#idx(
  "system of generators",
  "canonical",
)_canonical system of generators_ of $frak(g)$ associated with $frak(t)$ and
$Pi$.

Now denote by $hat(frak(g)) = hat(frak(g))(A)$ the Lie algebra with generators
$hat(h)_i, hat(e)_i, hat(f)_i$ ($i = 1, ..., l$) and defining relations obtained
from @eq:chevalley-generator-relations by replacing $h_i, e_i, f_i$ by
$hat(h)_i, hat(e)_i, hat(f)_i$, respectively.
Problems~@pr:free-lie-algebra-universal-property and
@pr:canonical-generators-relations imply that there exists an epimorphism
$pi: hat(frak(g)) -> frak(g)$ such that
$
  pi(hat(h)_i) = h_i, wide pi(hat(e)_i) = e_i, wide pi(hat(f)_i) = f_i.
$ <eq:epimorphism-on-generators>
In particular, the elements $hat(h)_1, ..., hat(h)_l$ are linearly independent.
The subspace $hat(frak(t))$ generated by them is a commutative subalgebra of
$hat(frak(g))$.

Denote by $hat(frak(n))^+ (hat(frak(n))^-)$ the subalgebra of $hat(frak(g))$
generated by $hat(e)_1, ..., hat(e)_l$ (resp. $hat(f)_1, ..., hat(f)_l$).

#problem[$hat(frak(g)) = hat(frak(t)) + hat(frak(n))^+ + hat(frak(n))^-$.]
<pr:triangular-decomposition-g-hat>

For any $alpha in hat(frak(t))^*$ set
$
  hat(frak(g))_alpha = {x in hat(frak(g)): [h, x] = alpha(h) x
    " for all " h in hat(frak(t))}
$ <eq:root-subspaces-g-hat>

#problem[$hat(frak(g)) = plus.o.big_alpha hat(frak(g))_alpha,
  hat(frak(g))_0 = hat(frak(t))$.] <pr:root-decomposition-g-hat>

#problem[Any ideal of $hat(frak(g))$ is the sum of its intersections with the
  subspaces $hat(frak(g))_alpha$.] <pr:ideals-of-g-hat-graded>

#problem[#source(199)Among the ideals of $hat(frak(g))$ that do not contain any
  $hat(h)_i$, there exists the largest ideal $frak(m)$ and
  $frak(m) = frak(m)^+ plus.o frak(m)^-$, where
  $frak(m)^plus.minus = frak(m) inter hat(frak(n))^plus.minus$ are ideals of
  $hat(frak(g))$.] <pr:largest-ideal-avoiding-cartan>

#problem[$Ker pi = frak(m)$.] <pr:kernel-is-largest-ideal>

Therefore $frak(g) tilde.eq hat(frak(g))\/frak(m)$. Since $frak(m)$ is
determined uniquely we have proved the following

#theorem(title: [The first uniqueness theorem])[A semisimple Lie algebra is
  determined uniquely up to an isomorphism by its Cartan matrix (or Dynkin
  diagram). More precisely, if $frak(g)$ and $tilde(frak(g))$ are semisimple Lie
  algebras with canonical generators ${h_i, e_i, f_i quad (1 <= i <= l)}$ and
  ${tilde(h)_i, tilde(e)_i, tilde(f)_i quad (1 <= i <= l)}$ respectively and
  equal Cartan matrices then there exists a (unique) isomorphism
  $phi: frak(g) -> tilde(frak(g))$ such that $phi(h_i) = tilde(h)_i$,
  $phi(e_i) = tilde(e)_i$,
  $phi(f_i) = tilde(f)_i$.] <th:cartan-matrix-determines-algebra>

Now let $rho: frak(g) -> frak(g l)(V)$ be a finite-dimensional linear
representation, $Phi_rho$ its weights system. Each weight $lambda in P$ and, in
particular, each weight $lambda in Phi_rho$ is completely determined by the
integers $lambda(h_i) = chevron.l lambda|alpha_i chevron.r$ ($i = 1, ..., l$)
which are its coordinates in the basis of fundamental weights $pi_1, ..., pi_l$
(see @ss:root-and-weight-lattices[°]).

The numbers $lambda(h_i)$ are called the #idx("Label", "numerical")_numerical
labels_ of $lambda$.

Let $V = plus.o.big_(lambda in Phi_rho) V_lambda$ be the weight decomposition. A
weight vector $v in V_Lambda$ is called a #idx("Vector", "highest")_highest
vector_ if
$
  rho(e_i) v = 0 quad "for" quad i = 1, ..., l.
$ <eq:highest-vector-condition>
The corresponding weight $Lambda in Phi_rho$ is called a #idx(
  "weight of a representation",
  "highest",
)_highest weight_ of $rho$.

_Example._ If $rho = ad$ for a simple Lie algebra $frak(g)$ then the root vector
$e_delta$ corresponding to the highest root (see @ss:dynkin-diagrams[°]) is a
highest vector and the highest root $delta$ is a highest weight of the
representation.

#problem[For any weight $lambda in Phi_rho$ there exist simple roots
  $alpha_(i_1), ..., alpha_(i_k)$ such that
  $lambda + alpha_(i_1) + dots.c + alpha_(i_k)$ is a highest weight. In
  particular, a highest weight exists for any finite-dimensional
  $rho$.] <pr:highest-weight-exists>

Fix a highest weight $Lambda in Phi_rho$ and a highest vector
$v_Lambda in V_Lambda$. Denote by $Lambda_i$ the numerical labels $Lambda(h_i)$
of the highest weight. Consider the vectors
$
  v_(i_1 ... i_k) = rho(f_(i_1)) ... rho(f_(i_k)) v_Lambda wide
  (1 <= i_1, ..., i_k <= l), wide v_emptyset = v_Lambda.
$ <eq:lowering-operator-vectors>
Clearly, $v_(i_1 ... i_k) in V_(Lambda - alpha_(i_1) - dots.c - alpha_(i_k))$
and
$
       rho(h_i) v_emptyset & = Lambda_i v_emptyset, \
  rho(h_i) v_(i_1 ... i_k) & = (Lambda_i - a_(i_1 i) - dots.c - a_(i_k i))
                             v_(i_1 ... i_k), \
  rho(f_i) v_(i_1 ... i_k) & = v_(i i_1 ... i_k), \
       rho(e_i) v_emptyset & = 0, \
  rho(e_i) v_(i_1 ... i_k) & = (delta_(i i_1) rho(h_i)
                               + rho(f_(i_1)) rho(e_i)) v_(i_2 ... i_k).
$ <eq:action-on-lowered-vectors>
#source(200)These relations imply that the subspace of $V$ spanned by
$v_(i_1 ... i_k)$, $v_emptyset$ is $rho(frak(g))$-invariant.

An element $lambda in frak(t)(RR)^*$ is called #idx(
  "Element",
  "dominant",
)_dominant_ if $(lambda, alpha_i) >= 0$ ($i = 1, ..., l$). This means that
$lambda$ belongs to the closure of the Weyl chamber $C^or$ corresponding to the
base $alpha_1^or, ..., alpha_l^or$ of $Delta_frak(g)^or$.

#problem[Any highest weight $Lambda$ is dominant, i.e.
  $Lambda_i >= 0$.] <pr:highest-weight-dominant>

Now suppose that $rho$ is irreducible. Clearly, in this case $v_(i_1 ... i_k)$
for all $k$ and $v_emptyset$ generate $V$.

#problem[If $rho$ is irreducible and $Lambda$ is its highest weight then
  $dim V_Lambda = 1$. Any other weight $lambda in Phi_rho$ is of the form
  $lambda = Lambda - alpha_(i_1) - dots.c - alpha_(i_k)$, where
  $alpha_(i_j) in Pi$. The representation $rho$ has a unique highest
  weight.] <pr:irreducible-unique-highest-weight>

Now we wish to prove that an irreducible linear representation $rho$ is
determined uniquely up to an equivalence by its highest weight. For this we will
make use of the following construction.

Consider a vector space $hat(V)$ over $CC$ with basis
${hat(v)_emptyset, hat(v)_(i_1 ... i_k): 1 <= i_1, ..., i_k <= l, k >= 1}$.
Define a linear representation $hat(rho) = hat(rho)_Lambda$ of the above Lie
algebra $hat(frak(g))$ in $hat(V)$ by determining it on generators by
formulas~@eq:action-on-lowered-vectors with
$h_i, e_i, f_i, v_(i_1 ... i_k), v_emptyset$ and $rho$ replaced by
$hat(h)_i, hat(e)_i, hat(f)_i, hat(v)_(i_1 ... i_k), hat(v)_emptyset$ and
$hat(rho)$ respectively. (The latter of these formulas should be considered as a
recurrent definition of $hat(rho)(hat(e)_i)$).

#problem[Prove the existence of
  $hat(rho)_Lambda$.] <pr:verma-module-g-hat-exists>

For an arbitrary $lambda in hat(frak(t))^*$ set
$
  hat(V)_lambda = {v in hat(V): hat(rho)(h) v = lambda(h) v
    " for all " h in hat(frak(t))}.
$ <eq:weight-subspaces-v-hat>
Clearly,
$
  hat(V) = plus.o.big_(lambda in hat(frak(t))^*) hat(V)_lambda
$ <eq:weight-decomposition-v-hat>

#problem[Among the subspaces of $hat(V)$ invariant with respect to
  $hat(rho)(hat(frak(g)))$ and not coinciding with $hat(V)$ there exists the
  largest subspace $M^((Lambda))$.] <pr:largest-proper-submodule>

#problem[There exists a unique linear map $p: hat(V) -> V$ with the following
  properties:

  a) $p(hat(v)_emptyset) = v_emptyset$;

  b) The diagram
  $
    #cd(
      (
        A: (0, 0, $hat(V)$),
        B: (0, 1, $hat(V)$),
        C: (1, 0, $V$),
        D: (1, 1, $V$),
      ),
      (
        ar("A", "B", label: $hat(rho)(x)$),
        ar("A", "C", label: $p$, side: "right"),
        ar("B", "D", label: $p$),
        ar("C", "D", label: $rho(pi(x))$),
      ),
      column: 26mm,
      row: 26mm,
    )
  $
  commutes for any $x in hat(frak(g))$ and
  $p(hat(V)) = V$.] <pr:intertwining-map-onto-irreducible>

#problem[#source(201)$Ker p = M^((Lambda))$.] <pr:kernel-is-largest-submodule>

#problem[The ideal $frak(m)$ is contained in the kernel of the induced
  representation of $hat(frak(g))$ in
  $hat(V)\/M^((Lambda))$.] <pr:largest-ideal-in-kernel>

Thus $hat(rho)$ uniquely determines a linear representation of the Lie algebra
$hat(frak(g))\/frak(m) tilde.equiv frak(g)$ in $hat(V)\/M^((Lambda))$. This
representation is completely determined by $Lambda$, and the statement b) of
Problem~@pr:intertwining-map-onto-irreducible implies that it is equivalent to
$rho$ if we identify $hat(frak(g))\/frak(m)$ and $frak(g)$ with respect to the
above isomorphism. Therefore the following theorem holds.

#theorem(title: [The second uniqueness theorem])[An irreducible
  finite-dimensional linear representation of a semisimple Lie algebra is
  determined uniquely up to an isomorphism by its highest
  weight.] <th:highest-weight-determines-irreducible>

In what follows we will often make use of the following method of describing
irreducible linear representations of a semisimple Lie algebra $frak(g)$: on the
Dynkin diagram of $frak(g)$ mark the numerical labels of the representation
above the corresponding vertices. By
Theorem~@th:highest-weight-determines-irreducible the obtained diagram, called
the #idx("diagram of a representation")_diagram of_ this _representation_,
determines it uniquely.

=== Existence Theorems <ss:existence-theorems>
Let $A = (a_(i j))$ be an arbitrary $l times l$ matrix over $CC$ and
$Lambda = (Lambda_1, ..., Lambda_l)$ an arbitrary set of $l$ complex numbers.
Exactly as in @ss:uniqueness-theorems we can construct the Lie algebra
$hat(frak(g)) = hat(frak(g))(A)$, the vector space $hat(V)$ and the linear
representation $hat(rho) = hat(rho)_Lambda: hat(frak(g)) -> frak(g l)(hat(V))$
(it does not matter here whether $A$ is a Cartan matrix and whether $Lambda_i$
are nonnegative or integer).

Clearly, the statements of Problems~@pr:triangular-decomposition-g-hat,
@pr:ideals-of-g-hat-graded, @pr:verma-module-g-hat-exists,
@pr:largest-proper-submodule and formulas~@eq:highest-vector-condition and
@eq:weight-decomposition-v-hat remain true. The algebras $hat(frak(t))$,
$hat(frak(n))^+$ and $hat(frak(n))^-$ are defined as in @ss:uniqueness-theorems
but the linear independence of the elements $hat(h)_1, ..., hat(h)_l$ has to be
proved.

#problem[The elements $hat(h)_1, ..., hat(h)_l$ are linearly
  independent.] <pr:h-hat-linearly-independent>

This implies that if $A$ is invertible then the statements of
Problems~@pr:root-decomposition-g-hat and @pr:largest-ideal-avoiding-cartan
remain true.

In what follows let $A$ be invertible. Construct the quotient algebra
$frak(g) = frak(g)(A) = hat(frak(g))\/frak(m)$ and the quotient space
$V = V(Lambda) = hat(V)\/M^((Lambda))$, where $frak(m)$ and $M^((Lambda))$ are
defined as in @ss:uniqueness-theorems. Denote by $pi: hat(frak(g)) -> frak(g)$
and $p: hat(V) -> V$ the natural maps. Set
$
  h_i = pi(hat(h)_i), quad e_i = pi(hat(e)_i), quad f_i = pi(hat(f)_i),
  quad frak(t) = pi(hat(frak(t))), \
  frak(n)^plus.minus = pi(hat(frak(n))^plus.minus), quad
  v_emptyset = p(hat(v)_emptyset), quad
  v_(i_1 ... i_k) = p(hat(v)_(i_1 ... i_k)).
$
Finally, denote by $rho'$ the linear representation of $hat(frak(g))$ in $V$
induced by $hat(rho)$. By construction $rho'$ is irreducible.

Let us decompose $V$ into weight subspaces with respect to $rho'(hat(frak(t)))$.
Namely, for any $lambda in hat(frak(t))^*$ set
$
  V_lambda = {v in V: rho'(h) v = lambda(h) v " for all "
    h in hat(frak(t))}.
$
Clearly, $V_lambda = p(hat(V)_lambda)$. It follows from
@eq:weight-decomposition-v-hat that
#source(202)
$ V = plus.o.big_(lambda in Omega) V_lambda, $
where $Omega = {lambda in hat(frak(t))^*: V_lambda != 0}$.

On $hat(frak(t))$, define the linear functions $alpha_1, ..., alpha_l$ and
$Lambda$ setting
$
  alpha_i (hat(h)_j) = a_(i j), wide Lambda(hat(h)_i) = Lambda_i.
$ <eq:define-simple-roots-highest-weight>
Clearly, $v_emptyset in V_Lambda$.

#problem[We have $dim V_Lambda = 1$. Any element $lambda in Omega$ presents in
  the form $lambda = Lambda - alpha_(i_1) - dots.c - alpha_(i_k)$. If $V_lambda$
  contains a nonzero element annihilated by all $rho'(hat(e)_i)$ then
  $lambda = Lambda$ (cf. Problem~@pr:irreducible-unique-highest-weight).]
<pr:quotient-module-highest-weight>

#problem[$dim V_lambda < oo$ for all
  $lambda in Omega$.] <pr:weight-spaces-finite-dimensional>

#problem[$rho'(frak(m)) = 0$.] <pr:largest-ideal-acts-trivially>

This shows that $rho'$ determines an irreducible linear representation
$rho = rho(Lambda): frak(g) -> frak(g l)(V)$.

#problem[Any nonzero ideal of $frak(g)$ contains at least one of the elements
  $h_i$.] <pr:nonzero-ideal-contains-coroot>

#problem[If $x in frak(n)^-$ and $[e_i, x] = 0$ ($i = 1, ..., l$) then $x = 0$.
  Similarly, if $y in frak(n)^+$ and $[f_i, y] = 0$ ($i = 1, ..., l$) then
  $y = 0$.] <pr:common-kernel-ad-e-trivial>

Suppose now that $A$ is a Cartan matrix and the numbers $Lambda_i$ are
nonnegative integers. Our aim is to prove the following statements:

1) $V$ and $frak(g)$ are finite-dimensional;

2) $frak(g)$ is semisimple and its Cartan matrix coincides with $A$;

3) The numerical labels of the highest weight of $rho(Lambda)$ are $Lambda_i$.

These statements obviously imply the following theorems.

#theorem(title: [The first existence theorem])[Any Cartan matrix is the Cartan
  matrix of a semisimple Lie algebra.] <th:cartan-matrix-algebra-exists>

#theorem(title: [The second existence theorem])[For any semisimple Lie algebra
  $frak(g)$ and any dominant weight $Lambda in P$ there exists an irreducible
  finite-dimensional linear representation $rho(Lambda)$ of $frak(g)$ with
  highest weight $Lambda$.] <th:highest-weight-representation-exists>

Theorems~@th:cartan-matrix-algebra-exists and
@th:cartan-matrix-determines-algebra imply in particular that each of the
exceptional Dynkin diagrams $E_6$, $E_7$, $E_8$, $F_4$, $G_2$ (see
@ss:classification-root-systems[°]) is a Dynkin diagram of a uniquely determined
noncommutative simple Lie algebra. These Lie algebras are called #idx(
  "Lie algebra",
  "exceptional",
)_exceptional_ and are denoted in the same way as their Dynkin diagrams. Their
dimensions are listed in Table~@tab:weights-and-roots. The root systems of these
Lie algebras are the root systems corresponding to the exceptional Dynkin
diagrams whose existence has been established by an explicit construction in
§~@sec:root-systems.

First of all let us prove that $V$ is finite-dimensional.
Problem~@pr:weight-spaces-finite-dimensional implies that it suffices to prove
the finiteness of $Omega$.

In $hat(frak(t))^*$, consider the subgroup
$
  L = {gamma in hat(frak(t))^*: gamma(hat(h)_i) in ZZ quad (i = 1, ..., l)}.
$
#source(203)Clearly, $L$ is a lattice in its real linear span $bold(E)$.
Furthermore, the elements $alpha_1, ..., alpha_l$ and $Lambda$ defined by
formula~@eq:define-simple-roots-highest-weight are contained in $L$.

#problem[$Omega subset L$.] <pr:weights-in-integral-lattice>

Since $A$ is invertible, $alpha_1, ..., alpha_l$ constitute a basis of $bold(E)$
over $RR$. Theorem~@th:admissible-matrix-realized implies that there exists a
positive definite scalar product $(dot, dot)$ on $bold(E)$ such that
$chevron.l alpha_i|alpha_j chevron.r = a_(i j)$ for all $i, j$. Let $r_i$ be the
orthogonal reflection in $bold(E)$ with respect to the hyperplane orthogonal to
$alpha_i$. Problem~@pr:root-reflection-formula implies that $r_i (L) = L$.
Therefore the group $W$ generated by $r_i$ ($i = 1, ..., l$) is finite (cf.
Problem~@pr:weyl-group-finite). Now let us prove that $Omega$ is $W$-invariant.

#problem[$[hat(e)_k, (ad hat(f)_j)^(-a_(i j) + 1) hat(f)_i]
  = [hat(f)_k, (ad hat(e)_j)^(-a_(i j) + 1) hat(e)_i] = 0$ for any $i != j$ and
  any $k$.] <pr:serre-elements-commute-e-hat>

#problem[$(ad f_j)^(-a_(i j) + 1) f_i = (ad e_j)^(-a_(i j) + 1) e_i = 0$
  for any $i != j$.] <pr:serre-relations-hold>

Problem~@pr:serre-relations-hold implies that
$
  rho((ad f_j)^(-a_(i j) + 1) f_i) = ad rho(f_j)^(-a_(i j) + 1) rho(f_i) = 0
  wide (i != j).
$ <eq:serre-relations-in-representation>

#problem[Let $p$ and $q$ be two elements of an associative algebra such that
  $(ad p)^l q = 0$. Then any product of them containing $m$ factors equal to $p$
  and $n$ factors equal to $q$ presents as a linear combination of products of
  the form $p^(l_1) q p^(l_2) q ... p^(l_n) q p^(l_0)$ where $l_i >= 0$,
  $sum_(0 <= i <= n) l_i = m$, $l_i < l$ for
  $i = 1, ..., n$.] <pr:reordering-with-nilpotent-ad>

A linear operator $p$ is #idx("Operator", "locally nilpotent")_locally
nilpotent_ if for any vector $v$ there exists $m$ such that $p^m v = 0$. (If $p$
acts on a finite-dimensional space then $p$ is nilpotent.)

#problem[$rho(f_i)^(Lambda_i + 1) v_emptyset = 0$.]
<pr:lowering-highest-vector-vanishes>

#problem[$rho(f_i)$ and $rho(e_i)$ are locally nilpotent in
  $V$.] <pr:generators-locally-nilpotent>

Denote by $frak(g)^((i))$ the subspace of $frak(g)$ spanned by $h_i, e_i, f_i$.
Clearly, this is a subalgebra isomorphic to $frak(s l)_2 (CC)$.

#problem[The space $V$ splits into the direct sum of finite-dimensional
  subspaces invariant with respect to $rho(frak(g)^((i)))$ (for a fixed
  $i$).] <pr:sl2-finite-invariant-subspaces>

Let $rho_i$ be a linear representation of $frak(s l)_2 (CC)$ in $V$ which sends
the matrices $bold(h)$, $bold(e)$, $bold(f)$ in $rho(h_i)$, $rho(e_i)$,
$rho(f_i)$, respectively. By Problem~@pr:sl2-finite-invariant-subspaces there
exists a linear representation $R_i: SL_2 (CC) -> GL(V)$ preserving the
finite-dimensional subspaces appearing in this problem and such that
$d R_i = rho_i$ in each of these subspaces. Set
$ w_i = R_i (mat(0, 1; -1, 0)). $
Let us extend $r_i$ onto $hat(frak(t))^*$ by linearity and denote the dual
reflection in $hat(frak(t))$ also by $r_i$. Since $pi: hat(frak(t)) -> frak(t)$
(by the definition of $frak(m)$) is an isomorphism, we will identify
$hat(frak(t))$ and $frak(t)$ with the help of $pi$.

#problem[$w_i rho(h) w_i^(-1) = rho(r_i (h))$
  ($h in frak(t) = hat(frak(t))$).] <pr:sl2-element-induces-reflection>

#problem[We have $V_(r_i (lambda)) = w_i V_lambda$ for any
  $lambda in frak(t)^*$; in particular,
  $r_i (Omega) = Omega$.] <pr:weights-reflection-invariant>

#problem[#source(204)For any $gamma in bold(E)$ there exists $w in W$ such that
  $(w(gamma), alpha_i) >= 0$ for all
  $i = 1, ..., l$.] <pr:weyl-orbit-meets-dominant>

#problem[We have $(lambda, lambda) <= (Lambda, Lambda)$ for any
  $lambda in Omega$.] <pr:weights-bounded-by-highest>

Therefore, $Omega$ is a bounded subset of $L$ and hence it is finite. We have
proved that $V$ is finite-dimensional. Now let us go over to studying $frak(g)$.

For $alpha in frak(t)^*$ set
$
  frak(g)_alpha = {x in frak(g): [h, x] = alpha(h) x " for all "
    h in frak(t)}.
$
Clearly,
$ frak(g) = frak(t) plus.o plus.o.big_(alpha != 0) frak(g)_alpha. $

#problem[If $Lambda_i != 0$ for all $i$ then
  $Ker rho = 0$.] <pr:regular-highest-weight-faithful>

#problem[The Lie algebra $frak(g)$ is finite-dimensional and
  semisimple.] <pr:constructed-algebra-semisimple>

#problem[The subalgebra $frak(t)$ is a maximal diagonalizable subalgebra of
  $frak(g)$.] <pr:constructed-maximal-diagonalizable>

#problem[The linear functions $alpha_1, ..., alpha_l$ on
  $frak(t) = hat(frak(t))$ form a system of simple roots of $frak(g)$ with
  respect to $frak(t)$ and ${h_i, e_i, f_i quad (1 <= i <= l)}$ is a canonical
  system of generators.] <pr:constructed-simple-roots>

#problem[The Cartan matrix of ${alpha_1, ..., alpha_l}$ coincides with
  $A$.] <pr:constructed-algebra-cartan-matrix>

#problem[The weight $Lambda$ is the highest weight of the linear representation
  $rho$.] <pr:constructed-highest-weight>

_Example._ Let $frak(g) = frak(s l)_2 (CC)$. By
Theorems~@th:highest-weight-representation-exists and
@th:highest-weight-determines-irreducible there exists a unique up to an
equivalence irreducible representation $rho_k$ of $frak(g)$ with the diagram
$ #dynkin((a: v(0, 0, label: $k$)), ()) $ <eq:sl2-representation-diagram>
where $k$ is an arbitrary nonnegative integer. Let $V$ be the space of this
representation. The highest weight of $rho_k$ is of the form
$Lambda = k alpha\/2$ where $alpha$ is the positive root of $frak(s l)_2 (CC)$.
By Problem~@pr:irreducible-unique-highest-weight all the weights of $rho_k$ are
of the form $Lambda - s alpha = (k - 2 s) alpha\/2$ where $s$ is an integer.
Since the system of weights $Phi_(rho_k)$ is symmetric (Corollary of
Theorem~@th:weights-invariant-under-reflections), we have $0 <= s <= k$ so that
$ Phi_(rho_k) = {p alpha\/2: p = k, k - 2, ..., 2 - k, -k}. $
The weight basis consists of the vectors of the form $v_(i_1 ... i_k)$
determined by @eq:lowering-operator-vectors. Here it is clear that
$dim V_lambda = 1$ for all $lambda in Phi_(rho_k)$ and that as the weight
vectors we can take
$ v_(Lambda - s alpha) = rho_k (f)^s v_Lambda wide (s = 0, 1, ..., k), $
#source(205)where $v_Lambda$ is a highest vector. Therefore $dim V = k + 1$ and
$
  rho_k (e) v_(Lambda - s alpha) = s(k - s + 1) v_(Lambda - (s - 1) alpha)
  wide (s = 1, ..., k) \
  rho_k (e) v_Lambda = 0.
$

For $k = 0$ we get the trivial one-dimensional representation, for $k = 1$ the
standard representation in $CC^2$, for $k = 2$ the adjoint representation.

=== The Linearity of a Connected Complex Semisimple Lie Group
<ss:linearity-complex-semisimple-groups>
Let $G$ be a connected semisimple algebraic group over $CC$, $T$ its maximal
torus, $Q subset P subset frak(t)(RR)^*$ the root and weight lattices of the
root system $Delta_G$ (see @ss:root-and-weight-lattices[°]).

#theorem[The group $G$ is simply connected if and only if
  $
    cal(X)(T) = P.
  $ <eq:characters-equal-weight-lattice>]
<th:simply-connected-iff-weight-lattice>

First we prove the sufficiency of the
condition~@eq:characters-equal-weight-lattice and then we apply it to prove
Theorem~@th:complex-semisimple-group-linear. The latter proof will also imply
the necessity of this condition.

Let ${alpha_1, ..., alpha_l}$ be a system of simple roots of $G$ with respect to
$T$, $G^((k)) = G^((alpha_k))$ the three-dimensional subgroup of $G$
corresponding to $alpha_k$ (see @ss:three-dimensional-subalgebras[°]), $T^((k))$
the maximal torus of $G^((k))$ belonging to $T$.

#problem[Under condition~@eq:characters-equal-weight-lattice all groups
  $G^((k))$ are simply connected.] <pr:root-sl2-subgroups-simply-connected>

#problem[Under the same condition
  $T = T^((1)) times dots.c times T^((l))$.] <pr:torus-product-of-coroot-tori>

#problem[For any connected reductive algebraic group $G$ the homomorphism
  $i_*: pi_1 (T) -> pi_1 (G)$ generated by the embedding of the maximal torus
  $i: T -> G$ is surjective.] <pr:torus-fundamental-group-surjects>

Therefore it suffices to prove that @eq:characters-equal-weight-lattice implies
$i_* = 0$. To do this consider the diagram
$
  #cd(
    (
      T: (0, 0, $T = T^((1)) times dots.c times T^((l))$),
      G: (0, 1, $G$),
      P: (1, 0.7, $G^((1)) times dots.c times G^((l))$),
    ),
    (
      ar("T", "G", label: $i$),
      ar("T", "P", label: $i^((1)) times dots.c times i^((l))$, side: "right"),
      ar("P", "G", label: $m$),
    ),
    column: 40mm,
    row: 44mm,
  )
$
where $i^((k)): T^((k)) -> G^((k))$ is an embedding and
$m(g_1, ..., g_l) = g_1 ... g_l$ (see Problem~@pr:torus-product-of-coroot-tori).
Clearly, the diagram commutes, hence
$i_* = m_* (i_*^((1)) times dots.c times i_*^((l)))$, but $i_*^((k)) = 0$ by
Problem~@pr:root-sl2-subgroups-simply-connected. Therefore $i_* = 0$ and the
sufficiency of @eq:characters-equal-weight-lattice is proved.

#theorem[Any connected semisimple Lie group admits a faithful finite-dimensional
  linear representation.] <th:complex-semisimple-group-linear>

#corollary[Any connected semisimple Lie group admits a unique structure of an
  algebraic group.]

#problem[#source(206)Reduce the proof of the theorem to the case of a simply
  connected group.] <pr:linearity-reduce-simply-connected>

#problem[For any semisimple Lie algebra $frak(g)$ there exists a linear
  representation $rho$ whose weights generate the weight lattice $P$ of the root
  system $Delta_frak(g)$. Such a representation $rho$ is always
  faithful.] <pr:weights-generating-weight-lattice>

Now we will prove Theorem~@th:complex-semisimple-group-linear for a simply
connected semisimple group $G$. Let $frak(g)$ be the tangent algebra of $G$. By
Theorem~@th:homomorphism-existence-simply-connected there exists a linear
representation $R$ of $G$ such that $d R = rho$ is the representation of
$frak(g)$ satisfying the condition of
Problem~@pr:weights-generating-weight-lattice. Let us prove that $R$ is
faithful. Clearly, $R(G)$ is a connected algebraic group with tangent algebra
$rho(frak(g)) tilde.eq frak(g)$. If we identify the maximal diagonalizable
subalgebra $frak(t)$ of $frak(g)$ with $rho(frak(t))$ with the help of $rho$,
the weights of $rho$ are identified with the weights of the identity
representation of $R(G)$ which are the differentials of characters of the
maximal torus of $R(G)$. Therefore $R(G)$ satisfies the
condition~@eq:characters-equal-weight-lattice and is, as we have already proved,
simply connected. Thus the covering $R: G -> R(G)$ is bijective.
Theorem~@th:complex-semisimple-group-linear is proved.#qed-mark

If $G$ is a simply connected semisimple algebraic group then
Problem~@pr:weights-generating-weight-lattice implies the existence of a
representation $R$ of $G$ whose weights generate $P$. Therefore,
@eq:characters-equal-weight-lattice holds thereby completing the proof of
Theorem~@th:simply-connected-iff-weight-lattice.#qed-mark

=== The Center and the Fundamental Group
<ss:semisimple-center-fundamental-group>
Let $T$ be an algebraic torus, $frak(t)$ its tangent algebra. We will now
establish a one-to-one correspondence between the finite subgroups of $T$ and
the lattices in $frak(t)(RR)$ containing $frak(t)(ZZ)$. To this end consider the
homomorphism $cal(E): frak(t) -> T$ defined by the formula
$ cal(E)(x) = exp(2 pi i x). $ <eq:torus-exponential-map>

#problem[$Ker cal(E) = frak(t)(ZZ)$.] <pr:torus-exponential-kernel>

#problem[For any finite subgroup $S subset T$ its pre-image $cal(E)^(-1) (S)$ is
  a lattice in $frak(t)(RR)$. The map $S |-> cal(E)^(-1) (S)$ establishes a
  bijective correspondence between finite subgroups of $T$ and lattices in
  $frak(t)(RR)$ containing $frak(t)(ZZ)$. We also have
  $
    S tilde.eq cal(E)^(-1) (S)\/frak(t)(ZZ).
  $] <pr:torus-finite-subgroups-lattices>

Now apply these considerations to calculate the center and the fundamental group
of a semisimple Lie group in terms of the lattice of characters of its maximal
torus. Recall (see Theorem~@th:maximal-torus-equals-centralizer) that the center
$Z(G)$ of a connected semisimple Lie group $G$ is contained in any its maximal
torus $T$. Consider, as in @ss:root-and-weight-lattices[°], the root and the
weight lattices $Q subset P subset frak(t)(RR)^*$ and their dual lattices
$Q^or subset P^or subset frak(t)(RR)$.

#theorem[Let $G$ be a connected semisimple Lie group, $T$ its maximal torus.
  Then $cal(E)^(-1) (Z(G)) = P^or$ and
  $
    Z(G) tilde.eq P^or\/frak(t)(ZZ) tilde.equiv cal(X)(T)\/Q.
  $] <th:center-via-character-lattice>

#problem[#source(207)Prove this theorem.] <pr:prove-center-via-characters>

#corollary[If $G$ is a simply connected semisimple Lie group then
  $Z(G) tilde.eq P\/Q = pi(Delta_G)$.]

#problem[Let $tilde(G), G$ be connected semisimple Lie groups and let a
  homomorphism $p: tilde(G) -> G$ be a covering. If $tilde(T) subset tilde(G)$
  and $T subset G$ are maximal tori then $p(tilde(T))$ and $p^(-1) (T)$ are
  maximal tori of $G$ and $tilde(G)$ respectively. If $T = p(tilde(T))$, we have
  the commutative diagram
  $
    #cd(
      (
        A: (0, 0, $tilde(T)$),
        B: (0, 1, $T$),
        C: (1, 0, $frak(t)$),
        D: (1, 1, $frak(t)$),
      ),
      (
        ar("A", "B", label: $p$),
        ar("C", "A", label: $tilde(cal(E))$),
        ar("D", "B", label: $cal(E)$, side: "right"),
        ar("C", "D", label: $d p$),
      ),
      column: 26mm,
      row: 26mm,
    )
  $ <eq:covering-tori-diagram>
  where $d p$ is an isomorphism and where $cal(E)$ and $tilde(cal(E))$ are
  defined by @eq:torus-exponential-map.] <pr:covering-maps-maximal-tori>

#theorem[Let $p: tilde(G) -> G$ be a simply connected covering of a semisimple
  Lie group $G$. Then $tilde(cal(E))^(-1) (Ker p) = frak(t)(ZZ)$ and
  $
    pi_1 (G) tilde.eq frak(t)(ZZ)\/Q^or tilde.eq P\/cal(X)(T).
  $] <th:fundamental-group-via-characters>

#problem[Prove this theorem.] <pr:prove-fundamental-group-formula>

=== Classification of Connected Semisimple Lie Groups
<ss:classification-semisimple-groups>
In this section we will prove the following two theorems.

#theorem(title: [The global uniqueness theorem])[A connected semisimple Lie
  group $G$ is determined uniquely up to an isomorphism by its Dynkin diagram
  and the character lattice $cal(X)(T)$ of a maximal torus $T subset G$. More
  precisely, if $G_1$, $G_2$ are two connected semisimple Lie groups,
  $T_i subset G_i$ their maximal tori, $Pi_i$ the corresponding systems of
  simple roots then for any isomorphism $psi: Pi_1 -> Pi_2$ which maps
  $cal(X)(T_1)$ onto $cal(X)(T_2)$ there exists an isomorphism $Phi: G_1 -> G_2$
  mapping $T_1$ onto $T_2$ and inducing
  $psi$.] <th:global-uniqueness-semisimple-groups>

#theorem(title: [The global existence theorem])[Let $Delta subset bold(E)$ be a
  reduced root system, $Q subset P subset bold(E)$ its root and weight lattices.
  For any lattice $L subset bold(E)$ such that $Q subset L subset P$ there exist
  a connected semisimple Lie group $G$, its maximal torus $T$ and a root system
  isomorphism $Delta_G -> Delta$ mapping $cal(X)(T)$ onto
  $L$.] <th:global-existence-semisimple-groups>

Proof of Theorem~@th:global-uniqueness-semisimple-groups is based on the
following problem.

#problem[Let $G_1$, $G_2$ be two connected semisimple Lie groups,
  $T_i subset G_i$ their maximal tori. For any isomorphism
  $phi: frak(g)_1 -> frak(g)_2$ such that $phi(frak(t)_1 (ZZ)) = frak(t)_2 (ZZ)$
  there exists an isomorphism $Phi: G_1 -> G_2$ such that
  $d Phi = phi$.] <pr:lattice-preserving-isomorphism-lifts>

#problem[Prove Theorem~@th:global-uniqueness-semisimple-groups.]
<pr:prove-global-uniqueness>

#source(208)To prove Theorem~@th:global-existence-semisimple-groups consider a
semisimple Lie algebra $frak(g)$ whose Cartan matrix coincides with the Cartan
matrix of $Delta$ (see Theorem~@th:cartan-matrix-algebra-exists). By
Theorem~@th:root-system-determined-by-base we may identify $Delta$ with the root
system $Delta_frak(g)$ with respect to a maximal diagonalizable subalgebra
$frak(t)$. Let $tilde(G)$ be a simply connected Lie group with the tangent
algebra $frak(g)$, $tilde(T) = exp frak(t)$ a maximal torus and
$tilde(cal(E)): frak(t) -> tilde(T)$ the homomorphism defined by
formula~@eq:torus-exponential-map. Set $N = tilde(cal(E))(L^*)$, where
$L^* subset P^or$ is the dual lattice of $L$. By
Theorem~@th:center-via-character-lattice $N subset Z(tilde(G))$. The group
$G = tilde(G)\/N$ is the desired one. In fact, $L^* = tilde(cal(E))^(-1) (N)$
since $Q^or = Ker tilde(cal(E))$ by
Theorem~@th:simply-connected-iff-weight-lattice and $L^* supset Q^or$.
Considering diagram~@eq:covering-tori-diagram, where $T = tilde(T)\/N$ and
$p: tilde(G) -> G$ is the natural homomorphism, we see that $frak(t)(ZZ) = L^*$
and therefore $cal(X)(T) = L$.

Notice that a lattice $L$ such that $Q subset L subset P$ is completely
determined by the subgroup $L\/Q$ of the finite group $P\/Q = pi(Delta)$.
Therefore the classification of connected semisimple Lie groups can be given in
terms of subgroups of $pi(Delta)$. (Notice that by
Theorem~@th:center-via-character-lattice the group $L\/Q$ is isomorphic to the
center of the semisimple Lie group $G$ corresponding to $L$.) Let us give the
corresponding formulation in terms of Cartan matrices.

Let $A$ be an $l times l$ Cartan matrix. Then its rows generate a lattice $Q_A$
in $RR^l$ such that $Q_A subset ZZ^l$. Set $pi(A) = ZZ^l\/Q_A$. By an #idx(
  "isomorphism of Cartan matrices",
)_isomorphism_ of Cartan matrices $A_1$ and $A_2$ we will mean a pair of
identical permutations of rows and columns of $A_1$ that transforms $A_1$ to
$A_2$. Any such isomorphism determines an isomorphism $pi(A_1) -> pi(A_2)$.

#problem[There is a bijection between the connected semisimple Lie groups $G$
  (considered up to an isomorphism) and the pairs $(A, Z)$, where $A$ is a
  Cartan matrix and $Z$ is a subgroup of $pi(A)$, considered up to isomorphisms
  of Cartan matrices $A$ that transform subgroups $Z$ into each other. If a pair
  $(A, Z)$ corresponds to $G$ then $A$ is the matrix of $frak(g)$ and
  $Z tilde.equiv Z(G)$.] <pr:semisimple-groups-cartan-subgroup-pairs>

#example[Let $frak(g)$ be a simple Lie algebra. Let us see what the
  classification of connected Lie groups $G$ with the tangent algebra $frak(g)$
  looks like. If $frak(g) != D_(2 s)$, $s >= 2$, then $pi(Delta_frak(g))$ is a
  cyclic group. Therefore any of its subgroups is invariant under all the
  automorphisms of the group $pi(Delta_frak(g))$. Therefore in this case $G$ is
  determined up to an isomorphism by $frak(g)$ and the center $Z(G)$ which may
  be isomorphic to an arbitrary subgroup of
  $pi(Delta_frak(g))$.] <exm:groups-with-cyclic-fundamental-group>

#example[Let $frak(g) = D_(2 s) = frak(s o)_(4 s) (CC)$, $s >= 2$. Then
  $pi(Delta_frak(g)) tilde.eq ZZ_2 plus.o ZZ_2$. Clearly, for $s >= 3$ the only
  nontrivial automorphism of the Dynkin diagram (or the Cartan matrix) permutes
  the summands of this direct sum. Therefore there exist exactly two
  nonisomorphic connected Lie groups $G$ with the tangent algebra
  $frak(s o)_(4 s) (CC)$ ($s >= 3$) and the center $Z(G) tilde.eq ZZ_2$.
  Furthermore, for $frak(g) = D_4$ the automorphism group of the Dynkin diagram,
  isomorphic to $S_3$, acts as the automorphism group of the group
  $ZZ_2 plus.o ZZ_2$. Therefore, in this case there exists a unique connected
  Lie group with the given center.] <exm:groups-of-type-so-4s>

=== Classification of Irreducible Representations
<ss:classifying-irreducible-representations>
Let $G$ be a connected semisimple Lie group. To any finite-dimensional linear
representation $R: G -> GL(V)$ one can associate a representation
$rho = d R: frak(g) -> frak(g l)(V)$ of the tangent Lie algebra #source(
  209,
)$frak(g)$. The weight system $Phi_R$ of $R$ with respect to a maximal torus
$T subset G$ coincides with the weight system $Phi_rho$ with respect to the
corresponding subalgebra $frak(t)$ of $frak(g)$. The #idx(
  "Vector",
  "highest",
)_highest vectors_ and the #idx(
  "weight of a representation",
  "highest",
)_highest weights of $R$_ are the highest vectors and the highest weights of
$rho$. If $R$ is irreducible then so is $rho$ and
Problem~@pr:irreducible-unique-highest-weight implies that $R$ possesses a
unique highest weight $Lambda in cal(X)(T)$. By
Problem~@pr:highest-weight-dominant $Lambda$ is dominant. The #idx(
  "diagram of a representation",
)_diagram of an irreducible linear representation $R$_ is the diagram of $rho$.

#theorem[An irreducible finite-dimensional linear representation of a connected
  semisimple Lie group $G$ is determined uniquely up to an equivalence by its
  highest weight. For any dominant character $Lambda in cal(X)(T)$ there exists
  an irreducible finite-dimensional linear representation of $G$ with highest
  weight $Lambda$.] <th:group-representations-highest-weight>

#problem[Prove this theorem.] <pr:prove-group-highest-weight>

_Example._ Since $SL_2 (CC)$ is simply connected, it has a representation $R_k$
with diagram~@eq:sl2-representation-diagram such that $d R_k = rho_k$ ($k$ is
any nonnegative integer). Clearly, $R_k (-E) = E$ if and only if $k$ is even.
Therefore the irreducible representations of
$SO_3 (CC) tilde.eq SL_2 (CC)\/{plus.minus E}$ are determined by
diagrams~@eq:sl2-representation-diagram with arbitrary even $k >= 0$.

Now, introduce lowest weights which are sometimes more convenient than highest
weights. Let $R$ be a finite-dimensional linear representation of a connected
semisimple Lie group in a space $V$ and $rho = d R$ the corresponding tangent
representation. A #idx("Vector", "lowest")_lowest vector_ of $R$ (or $rho$) is a
(nonzero) weight vector $v in V$ such that $rho(f_i) v = 0$ ($i = 1, ..., l$).
The corresponding weight is called a #idx(
  "weight of a representation",
  "lowest",
)_lowest weight._ For instance, the _lowest root_ of a simple Lie algebra (see
@ss:dynkin-diagrams[°]) is the lowest weight of its adjoint representation. Let
us establish the connection between the highest and the lowest weights of a
representation.

Let $C_0$ be the Weyl chamber corresponding to a base $Pi$. Denote by $w_0$ the
(unique) element of $W$ sending $C_0$ to the opposite Weyl chamber $-C_0$.
Clearly, $w_0^2 = e$.

#problem[The transformation $attach(w, tl: t, br: 0)$ sends the highest weights
  of the representation $R$ (or $rho$) into the lowest weights and vice versa.
  If $n_0 in N(T)$ is an element such that $(Ad n_0)|frak(t)(RR) = w_0$ then
  $R(n_0)$ transforms the highest vectors in the lowest ones and vice
  versa.] <pr:longest-element-highest-to-lowest>

Problem~@pr:longest-element-highest-to-lowest implies that the properties of the
lowest weights are completely similar to the known properties of the highest
weights. Thus, any weight $lambda$ of a representation $R$ is expressed in the
form $lambda = M + alpha_(i_1) + dots.c + alpha_(i_k)$, where $M$ is a lowest
weight and $alpha_(i_j) in Pi$. If $R$ is irreducible then there exists a unique
lowest weight $M in Phi_R$, $dim V_M = 1$ and the representation is determined
by $M$ uniquely up to an equivalence.

#exercises[
  #exercise[The Lie algebra $hat(frak(n))^+$ of
    Problem~@pr:triangular-decomposition-g-hat is freely generated by the
    elements $hat(e)_1, ..., hat(e)_l$ (i.e. there exists an isomorphism
    $frak(l)(x_1, ..., x_l) -> hat(frak(n))^+$ sending $x_i$ to $hat(e)_i$).
    Similarly, $hat(frak(n))^-$ is freely generated by
    $hat(f)_1, ..., hat(f)_l$.] <exc:positive-part-freely-generated>

  #exercise[The relations of Problem~@pr:serre-relations-hold together with
    relations~@eq:chevalley-generator-relations form the complete #source(
      210,
    )set of defining relations of a semisimple Lie algebra $frak(g)$. (Hint: See
    [@bib:Serre1966], Appendix to Ch. VI).] <exc:serre-presentation-semisimple>

  #exercise[Under the notation of @ss:uniqueness-theorems $v in hat(V)_lambda$
    ($lambda != Lambda$) belongs to $M^((Lambda))$ if and only if
    $hat(rho)_Lambda (hat(e)_i) v in M^((Lambda))$ for all $i$. (This gives a
    recursive method for constructing
    $M^((Lambda))$.)] <exc:recursive-largest-submodule>

  #exercise[Under the notation of @ss:uniqueness-theorems let $Lambda$ be a
    highest weight of $rho$ and $lambda$ a dominant weight of the form
    $Lambda - alpha_(i_1) - dots.c - alpha_(i_k)$, where $alpha_(i_j) in Pi$.
    Then $lambda in Phi_rho$. (Hint: present $Lambda - lambda$ as the sum of a
    minimal number of positive roots:
    $Lambda - lambda = beta_1 + dots.c + beta_m$ and then by induction in $k$
    prove that $Lambda - beta_1 - dots.c - beta_k in Phi_rho$.)]
  <exc:dominant-weights-below-highest>

  Since any weight of $rho$ can be transformed into a dominant weight by a
  transformation from the Weyl group, we have a method for recovering all the
  weights of a representation from its highest weights.

  In
  Exercises~@exc:dual-representation-highest-weight)–@exc:orthogonal-symplectic-central-element)
  $R$ stands for a finite-dimensional linear representation of a connected
  semisimple Lie group $G$ in a space $V$, $rho = d R: frak(g) -> frak(g l)(V)$
  the corresponding tangent representation, $Pi$ a system of simple roots of
  $G$.

  #exercise[We have $Phi_(R^*) = -Phi_R$, where $R^*$ is the representation dual
    to $R$. If $R$ is the irreducible representation with the highest weight
    $Lambda$ and the lowest weight $M$ then $R^*$ is the irreducible
    representation with the highest weight
    $-M = -attach(w, tl: t, br: 0) Lambda$ and the lowest weight
    $-Lambda = -attach(w, tl: t, br: 0) M$, where $w_0 in W$ is the element
    defined in @ss:classifying-irreducible-representations.]
  <exc:dual-representation-highest-weight>

  #exercise[The transformation $nu = -attach(w, tl: t, br: 0)$ is an
    automorphism of $Pi$. If $frak(g)$ is simple and different from
    $frak(s l)_n (CC)$ ($n >= 3$), $frak(s o)_(4 n + 2) (CC)$ and $E_6$ then
    $nu = e$. For the remaining simple Lie algebras $nu$ is determined by the
    only nontrivial symmetry of the Dynkin diagram of $Pi$. If $frak(g)$ is not
    simple then $nu$ acts on $Pi$ componentwise. (Hint: apply
    Exercise~@exc:minus-identity-weyl-classification).]
  <exc:opposition-involution>

  A representation $R$ is called #idx(
    "representation",
    "self-dual",
  )_self-dual_ if $R^* tilde.op R$.

  #exercise[If $frak(g)$ is a simple Lie algebra different from
    $frak(s l)_n (CC)$, ($n >= 3$), $frak(s o)_(4 n + 2) (CC)$ or $E_6$ then any
    irreducible representation of $frak(g)$ is self-dual. For the remaining
    three types an irreducible representation is self-dual if and only if its
    numerical labels are symmetrically located on its Dynkin
    diagram.] <exc:self-dual-irreducible-criterion>

  #exercise[Let $H$ be the three-dimensional connected simple subgroup of $G$
    corresponding to the principal three-dimensional subalgebra
    $frak(h) subset frak(g)$ (see
    Exercise~@exc:principal-three-dimensional-subalgebra). If $R$ is an
    irreducible representation with the highest weight $Lambda$ and the lowest
    weight $M$ then there exists in $V$ a subspace invariant and irreducible
    with respect to $R(H)$ and containing $V_Lambda$, $V_M$. In this subspace,
    $R$ induces an irreducible representation $R_m$ of $H$, where
    $m = sum_(alpha in Pi) r_alpha Lambda_alpha$.]
  <exc:principal-sl2-restriction>

  #exercise[A linear representation $R$ is self-dual if and only if there exists
    a non-degenerate bilinear form on $V$ invariant with respect to
    $R(G)$.] <exc:self-dual-iff-invariant-form>

  #exercise[If for an irreducible representation $R$ there exists a nonzero
    bilinear form on $V$ invariant with respect to $R(G)$ then this form is
    non-degenerate and either symmetric or skew-symmetric; any two invariant
    bilinear forms are proportional to each
    other.] <exc:invariant-form-irreducible-unique>

  A linear representation $R$ is called #idx(
    "representation",
    "orthogonal",
  )_orthogonal_ if it preserves a non-degenerate symmetric invariant bilinear
  form and #idx("representation", "symplectic")_symplectic_ if it preserves a
  non-degenerate skew-symmetric invariant bilinear form. Any self-dual
  irreducible representation is, clearly, either orthogonal or symplectic.

  #exercise[#source(211)The representation $R_k$ of $SL_2 (CC)$ is orthogonal if
    $k$ is even and symplectic if $k$ is odd. Any irreducible representation of
    $SO_3 (CC)$ is orthogonal.] <exc:sl2-orthogonal-or-symplectic>

  #exercise[Let $R$ be an irreducible self-dual representation with highest
    weight $Lambda$ and $Lambda_alpha = Lambda(h_alpha)$ ($alpha in Pi$) the
    numerical labels of the highest weight. $R$ is orthogonal if
    $sum_(alpha in Pi) r_alpha Lambda_alpha$ is even and symplectic if this
    number is odd. Here $r_alpha$ are the coordinates of the vector
    $2 rho^or = sum_(alpha in Delta_frak(g)^+) alpha^or$ in the basis
    $Pi^or = {h_alpha: alpha in Pi}$. Thanks to
    Exercise~@exc:half-sum-positive-roots
    $rho^or = sum_(alpha in Pi) pi_(alpha^or)$, where
    $pi_(alpha^or) in frak(t)(RR)$ are the fundamental weights of the root
    system $Delta_frak(g)^or$.] <exc:orthogonal-symplectic-parity>

  #exercise[Deduce from Exercise~@exc:orthogonal-symplectic-parity the following
    rule for determining whether a self-dual irreducible representation of $G$
    is orthogonal or symplectic. Find the sum of numerical labels of the highest
    weight corresponding to the black vertices in the connected components of
    the Dynkin diagram of $G$ of the types indicated below (other types give
    zero contribution). The representation is orthogonal if and only if this sum
    is even and symplectic if it is odd.

    #grid(
      columns: 3,
      align: left + horizon,
      column-gutter: 1.2em,
      row-gutter: 1.2em,
      $A_(4 q + 1)$,
      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(3, 0, black: true),
          d: v(5, 0),
          e: v(6, 0),
        ),
        (bond("a", "b"), gap("b", "c"), gap("c", "d"), bond("d", "e")),
      ),
      [(the black vertex is the middle one).],

      $B_(4 q + 1), B_(4 q + 2)$,
      dynkin(
        (a: v(0, 0), b: v(1, 0), c: v(3, 0), d: v(4, 0, black: true)),
        (bond("a", "b"), gap("b", "c"), bond("c", "d", 2, to: "d")),
      ),
      [],

      $C_(2 q)$,
      dynkin(
        (
          a: v(0, 0, black: true),
          b: v(1, 0),
          c: v(2, 0, black: true),
          d: v(4, 0, black: true),
          e: v(5, 0),
        ),
        (
          bond("a", "b"),
          bond("b", "c"),
          gap("c", "d"),
          bond("d", "e", 2, to: "d"),
        ),
      ),
      [],

      $C_(2 q + 1)$,
      dynkin(
        (
          a: v(0, 0, black: true),
          b: v(1, 0),
          c: v(2, 0, black: true),
          d: v(4, 0),
          e: v(5, 0, black: true),
        ),
        (
          bond("a", "b"),
          bond("b", "c"),
          gap("c", "d"),
          bond("d", "e", 2, to: "d"),
        ),
      ),
      [],

      $D_(4 q + 2)$,
      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(3, 0),
          d: v(4, 0.5, black: true),
          e: v(4, -0.5, black: true),
        ),
        (bond("a", "b"), gap("b", "c"), bond("c", "d"), bond("c", "e")),
      ),
      [],

      $E_7$,
      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(2, 0),
          d: v(3, 0, black: true),
          e: v(4, 0),
          f: v(5, 0, black: true),
          g: v(2, -1, black: true),
        ),
        (
          bond("a", "b"),
          bond("b", "c"),
          bond("c", "d"),
          bond("d", "e"),
          bond("e", "f"),
          bond("c", "g"),
        ),
      ),
      [],
    )] <exc:orthogonal-symplectic-black-vertices>

  #exercise[Express the criterion of Exercise~@exc:orthogonal-symplectic-parity
    in the following form: let $z_0 in Z(G)$ be the element defined by the
    formula
    $ z_0 = cal(E)(rho^or) = exp(2 pi i rho^or); $
    an irreducible self-dual representation $R$ is orthogonal if $R(z_0) = E$
    and symplectic if
    $R(z_0) = -E$.] <exc:orthogonal-symplectic-central-element>

  A connected semisimple Lie group $G$ is called a #idx(
    "Lie group",
    "of adjoint type",
  )_group of adjoint type_ if it satisfies either of the following equivalent
  conditions: $cal(X)(T) = Q$ or $Z(G) = {e}$ or
  $pi_1 (G) tilde.equiv pi(Delta_G)$.

  #exercise[For any semisimple Lie algebra $frak(g)$ there exists a unique up to
    an isomorphism group of adjoint type with the tangent algebra $frak(g)$.
    Such a group is the adjoint group $Ad G$ for any connected Lie group $G$
    with the tangent algebra $frak(g)$.] <exc:adjoint-type-group-unique>

  #exercise[Any self-dual irreducible linear representation of a group of
    adjoint type is orthogonal.] <exc:adjoint-type-self-dual-orthogonal>

  #source(212)Let $G$ be a connected semisimple Lie group, $R_1, ..., R_m$ its
  linear representations, $R = R_1 ... R_m$.

  #exercise[The weights of $R$ are of the form $lambda_1 + dots.c + lambda_m$,
    where $lambda_i in Phi_(R_i)$. Then
    $(V_1)_(lambda_1) times.o dots.c times.o (V_m)_(lambda_m) subset
    (V_1 times.o dots.c times.o V_m)_(lambda_1 + dots.c + lambda_m)$.]
  <exc:tensor-product-weights>

  #exercise[If $v_(Lambda_i)$ is a highest vector of $R_i$ then
    $v_Lambda = v_(Lambda_1) times.o dots.c times.o v_(Lambda_m)$ is a highest
    vector of $R$.] <exc:tensor-product-highest-vector>

  Suppose $G = G_1 times dots.c times G_m$, where $G_i$'s are simple groups.

  For any irreducible representation $tilde(R)_i: G_i -> GL(V_i)$ we can define
  an irreducible representation $R_i: G -> GL(V_i)$ setting
  $R_i (g_1, ..., g_m) = tilde(R)_i (g_i)$.

  #exercise[Let $tilde(R)_i: G_i -> GL(V_i)$ be an irreducible representation
    for each $i = 1, ..., m$. Then $R_1 ... R_m$ is an irreducible
    representation of $G$ in the space $V_1 times.o dots.c times.o V_m$. Recover
    its highest weight from the highest weights of
    $tilde(R)_i$'s.] <exc:product-group-tensor-irreducible>

  #exercise[Conversely, any irreducible representation of $G$ factors into the
    product of $R_i$'s obtained by the above method from some irreducible
    representations $tilde(R)_i$ of $G_i$. The representations $tilde(R)_i$ are
    determined uniquely.] <exc:product-group-irreducible-factors>

  Let $T^p V$ be the $p$-th tensor power of a vector space $V$. Let $Lambda^p V$
  and $S^p V$ be its exterior and symmetric powers. Any representation
  $R: G -> GL(V)$ induces the $p$-th tensor power $T^p R = R^p$ in the space
  $T^p V$, the $p$-th exterior power $Lambda^p R$ in $Lambda^p V$ and the $p$-th
  symmetric power $S^p R$ in $S^p V$.

  #exercise[$T^2 R tilde.eq Lambda^2 R plus.o S^2 R$. (For $p > 2$ the similar
    statement is false!)] <exc:tensor-square-decomposition>

  #exercise[Find the representations of the tangent algebra $frak(g)$
    corresponding to $Lambda^p R$ and
    $S^p R$.] <exc:tangent-exterior-symmetric-powers>

  #exercise[$V_(lambda_1) and dots.c and V_(lambda_p) subset
    (Lambda^p V)_(lambda_1 + dots.c + lambda_p)$;
    $V_(lambda_1) ... V_(lambda_p) subset
    (S^p V)_(lambda_1 + dots.c + lambda_p)$.]
  <exc:exterior-symmetric-power-weights>

  #exercise[If $v_Lambda$ is a highest vector of $R$, then $v_Lambda^p$ is a
    highest vector of $S^p R$ and its weight is
    $p Lambda$.] <exc:symmetric-power-highest-vector>

  #exercise[Let $R$ be an irreducible representation with the highest weight
    $Lambda$ and ${v_1, ..., v_p}$, where $v_i in V_(lambda_i)$, a linearly
    independent system of its weight vectors with the minimal possible sum
    $sum_(1 <= i <= p) italic("ht")(Lambda - lambda_i)$, where
    $italic("ht")(gamma)$ (the _height_ of a weight $gamma in P$) is the sum of
    coordinates of $gamma$ in the basis consisting of simple roots. Then
    $v_1 and dots.c and v_p$ is a highest vector of
    $Lambda^p R$.] <exc:exterior-power-highest-vector>

  #exercise[The diagrams of the identity representations $Id$ of the classical
    simple Lie groups are the following:
    #grid(
      columns: 2,
      align: left + horizon,
      column-gutter: 2.5em,
      row-gutter: 1.2em,
      [$SL_n (CC)$, $n >= 2$:],
      dynkin(
        (a: v(0, 0, label: $1$), b: v(1, 0), c: v(3, 0), d: v(4, 0)),
        (bond("a", "b"), gap("b", "c"), bond("c", "d")),
      ),

      [$SO_(2 n + 1) (CC)$, $n >= 2$:],
      dynkin(
        (a: v(0, 0, label: $1$), b: v(1, 0), c: v(3, 0), d: v(4, 0)),
        (bond("a", "b"), gap("b", "c"), bond("c", "d", 2, to: "d")),
      ),

      [$SO_3 (CC)$:], dynkin((a: v(0, 0, label: $2$)), ()),

      [$SO_(2 n) (CC)$, $n >= 3$:],
      dynkin(
        (
          a: v(0, 0, label: $1$),
          b: v(1, 0),
          c: v(3, 0),
          d: v(4, 0.5),
          e: v(4, -0.5),
        ),
        (
          bond("a", "b"),
          gap("b", "c"),
          bond("c", "d"),
          bond("c", "e"),
        ),
      ),

      [$Sp_(2 n) (CC)$, $n >= 1$:],
      dynkin(
        (a: v(0, 0, label: $1$), b: v(1, 0), c: v(3, 0), d: v(4, 0)),
        (bond("a", "b"), gap("b", "c"), bond("c", "d", 2, to: "c")),
      ),
    )] <exc:identity-representation-diagrams>

  #exercise[#source(213)For the indicated values of $p$ the representations
    $Lambda^p Id$ are irreducible and their diagrams are the following:
    #grid(
      columns: 3,
      align: left + horizon,
      column-gutter: 2.5em,
      row-gutter: 1.2em,
      [$SL_n (CC)$, $n >= 2$:],
      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(3, 0, label: $1$),
          d: v(5, 0),
          e: v(6, 0),
        ),
        (
          bond("a", "b"),
          gap("b", "c"),
          gap("c", "d"),
          bond("d", "e"),
        ),
      ),
      [$p <= n - 1$,],

      [$SO_(2 n + 1) (CC)$, $n >= 2$:],
      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(3, 0, label: $1$),
          d: v(5, 0),
          e: v(6, 0),
        ),
        (
          bond("a", "b"),
          gap("b", "c"),
          gap("c", "d"),
          bond("d", "e", 2, to: "e"),
        ),
      ),
      [$p <= n - 1$,],

      [$SO_(2 n) (CC)$, $n >= 3$:],
      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(3, 0, label: $1$),
          d: v(5, 0),
          e: v(6, 0.5),
          f: v(6, -0.5),
        ),
        (
          bond("a", "b"),
          gap("b", "c"),
          gap("c", "d"),
          bond("d", "e"),
          bond("d", "f"),
        ),
      ),
      $p <= n - 2$,
    )
    (the unit occupies the $p$-th
    place.)] <exc:exterior-powers-identity-diagrams>

  #exercise[The representation $S^p Id$ of $SL_n (CC)$ is irreducible for all
    $p$, its diagram is $#dynkin(
      (a: v(0, 0, label: $p$), b: v(1, 0), c: v(3, 0), d: v(4, 0)),
      (bond("a", "b"), gap("b", "c"), bond("c", "d")),
    )$ and $S^p Id tilde.op R_p$ for
    $n = 2$.] <exc:symmetric-powers-identity-sl-n>

  #exercise[Using Theorem~@th:simply-connected-iff-weight-lattice prove that
    $SL_n (CC)$ and $Sp_(2 n) (CC)$ are simply connected and
    $pi_1 (SO_n (CC)) tilde.equiv ZZ_2$ for
    $n >= 3$.] <exc:classical-groups-fundamental-groups>

  In
  Exercises~@exc:image-character-lattice-weights–@exc:adjoint-image-iff-zero-weight
  $R$ is a locally faithful linear representation of a connected semisimple Lie
  group $G$, $rho = d R$, $T$ a maximal torus of $G$.

  #exercise[If we identify $frak(t)(RR)^*$ with its image with respect to
    $attach(rho, tl: t, tr: -1)$ then the character lattice $cal(X)(R(T))$ is
    identified with the sublattice $L_R subset cal(X)(T)$ generated by the
    weights of $R$. The lattice $L_R$ is generated by the lattice $Q$ and all
    highest (or all lowest) weights of $R$, and the dual lattice is of the form
    $
      L_R^* = {x in P^or: Lambda(x) in ZZ
        " for all the highest (lowest) weights of " R}
    $] <exc:image-character-lattice-weights>

  #exercise[$Z(R(G)) tilde.equiv P^or\/L_R^* tilde.equiv L_R\/Q; wide
    Ker R tilde.equiv L_R^*\/frak(t)(ZZ) tilde.equiv cal(X)(T)\/L_R$.]
  <exc:image-center-and-kernel>

  #exercise[A representation $R$ is faithful if and only if its weights generate
    $cal(X)(T)$ or if
    $L_R^* = frak(t)(ZZ)$.] <exc:faithful-iff-weights-generate>

  #exercise[$R(G)$ is a group of adjoint type if and only if $L_R = Q$. If $R$
    is irreducible then this is equivalent to the fact that the weight system
    $Phi_R$ contains a zero weight.] <exc:adjoint-image-iff-zero-weight>

  Denote by $Spin_n (CC)$ the simply connected covering group for $SO_n (CC)$,
  $n >= 3$.

  #exercise[We have the following isomorphisms:
    $
      Spin_3 (CC) tilde.equiv SL_2 (CC), \
      Spin_4 (CC) tilde.equiv SL_2 (CC) times SL_2 (CC), \
      Spin_5 (CC) tilde.equiv Sp_4 (CC), \
      Spin_6 (CC) tilde.equiv SL_4 (CC).
    $] <exc:low-dimensional-spin-isomorphisms>

  #exercise[#source(214)A connected semisimple Lie group admits a faithful
    irreducible representation if and only if its center is
    cyclic.] <exc:faithful-irreducible-iff-cyclic-center>

  #exercise[The following representations of $Spin_n (CC)$ are faithful:
    #grid(
      columns: 4,
      align: left + horizon,
      column-gutter: 1.2em,
      row-gutter: 1.2em,
      dynkin(
        (a: v(0, 0), b: v(1, 0), c: v(3, 0), d: v(4, 0, label: $1$)),
        (bond("a", "b"), gap("b", "c"), bond("c", "d", 2, to: "d")),
      ),
      [],
      [],
      [for odd $n$],

      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(3, 0),
          d: v(4, 0.5, label: $1$),
          e: v(4, -0.5),
        ),
        (bond("a", "b"), gap("b", "c"), bond("c", "d"), bond("c", "e")),
      ),
      [],
      [],
      [for $n = 4 k + 2$, $k in ZZ$],

      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(3, 0),
          d: v(4, 0.5, label: $1$),
          e: v(4, -0.5),
        ),
        (bond("a", "b"), gap("b", "c"), bond("c", "d"), bond("c", "e")),
      ),
      $+$,
      dynkin(
        (
          a: v(0, 0),
          b: v(1, 0),
          c: v(3, 0),
          d: v(4, 0.5),
          e: v(4, -0.5, label: $1$, at: "below"),
        ),
        (bond("a", "b"), gap("b", "c"), bond("c", "d"), bond("c", "e")),
      ),
      [for $n = 4 k$, $k in ZZ$],
    )] <exc:faithful-spin-representations>
]

#hints[
  #hint[@pr:generators-via-left-normed-commutators][By induction in the length
    $m$ of a word verify that the words of the form~@eq:left-normed-commutators
    constitute a subalgebra of $frak(a)$.]

  #hint[@pr:canonical-generators-relations][Make use of
    Problems~@pr:bracket-of-root-spaces and @pr:positive-root-chain-of-simple.]

  #hint[@pr:triangular-decomposition-g-hat][Making use of
    Problem~@pr:generators-via-left-normed-commutators and
    relation~@eq:chevalley-generator-relations show that
    $hat(frak(t)) + hat(frak(n))^+ + hat(frak(n))^-$ is a subalgebra of
    $hat(frak(g))$.]

  #hint[@pr:root-decomposition-g-hat][The identity
    $hat(frak(g))_0 = hat(frak(t))$ follows from the invertibility of $A$ and
    the linear independence of the elements $hat(h)_i$.]

  #hint[@pr:largest-ideal-avoiding-cartan][First prove that the ideal
    $frak(m) subset hat(frak(g))$ does not contain any $hat(h)_i$ if and only if
    $frak(m) inter hat(frak(t)) = 0$. Then show that any ideal $frak(m)$ is of
    the form $frak(m) = plus.o.big_alpha frak(m) inter hat(frak(g))_alpha$. To
    prove that $frak(m)^plus.minus$ are ideals notice that
    $
      [hat(f)_i, hat(frak(n))^+] subset hat(frak(t)) + hat(frak(n))^+, wide
      [hat(e)_i, hat(frak(n))^-] subset hat(frak(t)) + hat(frak(n))^-.
    $]

  #hint[@pr:kernel-is-largest-ideal][Follows from the fact that any non-zero
    ideal of $frak(g)$ contains at least one of the elements $h_i$.]

  #hint[@pr:highest-weight-exists][Apply Problem~@pr:root-vectors-shift-weights
    (more precisely, its generalization to any linear representations of
    $frak(g)$).]

  #hint[@pr:highest-weight-dominant][Let $r_i = r_(alpha_i)$ be the reflection
    corresponding to the root $alpha_i$. By Problem~@pr:alpha-string-of-weights
    $r_i (Lambda) = Lambda - Lambda_i alpha_i$ is a weight of the representation
    $rho$ in the subspace spanned by the vectors $v_(i_1 ... i_k)$,
    $v_emptyset$. By Problem~@pr:root-vectors-shift-weights
    $v_(i_1 ... i_k) in V_(Lambda - alpha_(i_1) - dots.c - alpha_(i_k))$. This
    implies that $Lambda_i >= 0$.]

  #hint[@pr:verma-module-g-hat-exists][Make use of
    Problem~@pr:free-lie-algebra-universal-property.]

  #hint[@pr:largest-ideal-in-kernel][Follows from the commutative diagram of
    Problem~@pr:intertwining-map-onto-irreducible.]

  #hint[@pr:h-hat-linearly-independent][Make use of the existence of the
    representation $hat(rho)_Lambda$ for any $Lambda_1, ..., Lambda_l$.]

  #hint[@pr:largest-ideal-acts-trivially][
    Problem~@pr:largest-ideal-avoiding-cartan implies that the subspace
    $rho'(frak(m)^-)(V)$ is $frak(g)$-invariant. If $rho'(frak(m)^-) != 0$ then
    $rho'(frak(m)^-)(V) = V$, $v_emptyset in rho'(frak(m)^-)(V)$ which
    contradicts Problem~@pr:quotient-module-highest-weight. To prove that
    $rho'(frak(m)^+) = 0$ consider the subspace
    $inter.big_(x in frak(m)^+) Ker rho'(x)$ invariant with respect to $frak(g)$
    and containing $v_emptyset$.]

  #hint[@pr:common-kernel-ad-e-trivial][Prove that the elements of the form
    $(ad f_(i_1)) ... (ad f_(i_p)) (ad h_(j_1)) ... (ad h_(j_q)) (x)$
    ($p, q >= 0$) form an ideal of $frak(g)$ belonging to $frak(n)^-$.]

  #hint[@pr:reordering-with-nilpotent-ad][#source(215)Expanding $(ad p)^l q = 0$
    we see that the product $p^l q$ is presented in the desired form.]

  #hint[@pr:lowering-highest-vector-vanishes][The vector
    $v = rho'(hat(f)_i)^(Lambda_i + 1) v_emptyset$ is obviously a weight vector
    of weight $Lambda - (Lambda_i + 1) alpha_i$. By a straightforward
    verification $rho(e_k) v = 0$ for all $k$.
    Problem~@pr:quotient-module-highest-weight shows that $v = 0$.]

  #hint[@pr:generators-locally-nilpotent][For $rho(e_i)$ this is clear from
    Problem~@pr:quotient-module-highest-weight. To prove the local nilpotency of
    $rho(f_i)$ consider the subspace $U_i = union.big_m Ker(rho(f_i))^m$.
    Problem~@pr:lowering-highest-vector-vanishes shows that $U_i != 0$. By a
    straightforward verification $U_i$ is invariant with respect to $rho(h_k)$
    and $rho(e_k)$ for all $k$. Finally, with the help of
    formula~@eq:serre-relations-in-representation and
    Problem~@pr:reordering-with-nilpotent-ad applied to $p = rho(f_i)$ and
    $q = rho(f_k)$, it is not difficult to show that $U_i$ is invariant with
    respect to $rho(f_k)$ for any $k$. This implies that $U_i = V$.]

  #hint[@pr:sl2-finite-invariant-subspaces][It suffices to prove that any weight
    vector belongs to a finite-dimensional subspace invariant with respect to
    $rho(frak(g)^((i)))$. Let $lambda in Omega$. Consider the subspace
    $
      U = V_lambda plus.o (plus.o.big_m rho(e_i)^m V_lambda) plus.o
      (plus.o.big_m rho(f_i)^m V_lambda).
    $
    It is easy to verify that $U$ is invariant with respect to
    $rho(frak(g)^((i)))$ and Problems~@pr:weight-spaces-finite-dimensional and
    @pr:generators-locally-nilpotent imply that $U$ is finite-dimensional.]

  #hint[@pr:sl2-element-induces-reflection][It suffices to consider two cases:
    $h = h_i$ and $alpha_i (h) = 0$. In the first case the statement of the
    problem reduces to the statement concerning $SL_2 (CC)$ which can be
    verified directly. In the second case it is necessary to prove that $rho(h)$
    commutes with $w_i$ but this follows from the fact that $rho(h)$ commutes
    with $rho(h_i), rho(e_i), rho(f_i)$.]

  #hint[@pr:weyl-orbit-meets-dominant][In the orbit of $gamma$ under $W$, choose
    an element $gamma_1$ with the minimal sum of the coefficients in its linear
    expression in terms of $alpha_1, ..., alpha_l$ and consider the elements
    $r_i (gamma_1)$.]

  #hint[@pr:weights-bounded-by-highest][Thanks to
    Problems~@pr:weights-reflection-invariant and @pr:weyl-orbit-meets-dominant
    we may assume that $(lambda, alpha_i) >= 0$ for all $i$. Making use of
    Problem~@pr:quotient-module-highest-weight we get
    $(Lambda - lambda, lambda) >= 0$.]

  #hint[@pr:regular-highest-weight-faithful][Under the conditions of the
    problem, $h_i in.not Ker rho$ for any $i$. Then apply
    Problem~@pr:nonzero-ideal-contains-coroot.]

  #hint[@pr:constructed-algebra-semisimple][Let $frak(a)$ be a commutative ideal
    of $frak(g)$ and $frak(a) != 0$. By
    Problem~@pr:nonzero-ideal-contains-coroot $h_i in frak(a)$ for some $i$ but
    then $e_i = 1/2 [h_i, e_i] in frak(a)$ contradicting the commutativity of
    $frak(a)$.]

  #hint[@pr:constructed-simple-roots][Make use of
    Problem~@pr:triangular-decomposition-g-hat and linear independence of the
    forms $alpha_1, ..., alpha_l$.]

  #hint[@pr:root-sl2-subgroups-simply-connected][The group $G^((k))$ is the
    image of the simply connected group $SL_2 (CC)$ with respect to the
    homomorphism $Phi_k = Phi_(alpha_k)$ (see
    @ss:three-dimensional-subalgebras[°]); it is simply connected if and only if
    $Phi_k$ is injective, i.e. $t_k = Phi_k (-E) != e$. It is easy to see that
    $t_k = exp(pi i h_k)$. The condition~@eq:characters-equal-weight-lattice
    implies the existence of a character $chi in cal(X)(T)$ such that
    $(d chi)(h_k) = 1$. Then $chi(t_k) = exp(pi i (d chi)(h_k)) = -1$ so that
    $t_k != e$.]

  #hint[@pr:torus-product-of-coroot-tori][Clearly, $T = T^((1)) ... T^((l))$.
    Let $t_k in T^((k))$ be elements such that $t_1 ... t_l = e$.
    Condition~@eq:characters-equal-weight-lattice implies the existence of
    characters $chi_i in cal(X)(T)$ ($i = 1, ..., l$), such that
    $d chi_i = pi_i$ (fundamental weights). We have
    $chi_k (t_1 ... t_l) = chi_k (t_k) = 1$. Let $t_k = exp(2 pi i c_k h_k)$,
    where $c_k in CC$. Then $chi_k (t_k) = exp(2 pi i c_k)$ so that $c_k in ZZ$
    and $t_k = e$.]

  #hint[@pr:torus-fundamental-group-surjects][Make use of
    Theorems~@th:homotopy-sequence-homogeneous-space,
    @th:flag-variety-simply-connected and
    Problem~@pr:borel-semidirect-decomposition.]

  #hint[@pr:linearity-reduce-simply-connected][Make use of
    Theorem~@th:chevalley-line-stabilizer.]

  #hint[@pr:weights-generating-weight-lattice][#source(216)Such is e.g. the sum
    of the irreducible representations with highest weights $pi_1, ..., pi_l$
    existing thanks to Theorem~@th:highest-weight-representation-exists. The
    representation is faithful thanks to
    Problem~@pr:weights-integral-on-coroots.]

  #hint[@pr:prove-center-via-characters][Make use of the fact that
    $Z(G) = {exp x: x in frak(t), e^(alpha(x)) = 1 " for all "
      alpha in Delta_frak(g)}$.]

  #hint[@pr:covering-maps-maximal-tori][Make use of the relation
    $Ker p subset Z(tilde(G))$.]

  #hint[@pr:prove-fundamental-group-formula][Make use of
    Diagram~@eq:covering-tori-diagram.]

  #hint[@pr:lattice-preserving-isomorphism-lifts][Let $p_i: tilde(G)_i -> G_i$
    be a simply connected covering of $G_i$ ($i = 1, 2$) and $T_i subset G_i$,
    $tilde(T)_i subset tilde(G)_i$ the maximal tori corresponding to
    $frak(t)_i$. The isomorphism $phi$ determines an isomorphism
    $tilde(Phi): tilde(G)_1 -> tilde(G)_2$ such that the diagram
    $
      #cd(
        (
          A: (0, 0, $tilde(T)_1$),
          B: (0, 3, $tilde(T)_2$),
          C: (1, 1, $frak(t)_1$),
          D: (1, 2, $frak(t)_2$),
          E: (2, 0, $T_1$),
          F: (2, 3, $T_2$),
        ),
        (
          ar("A", "B", label: $tilde(Phi)$),
          ar("A", "E", label: $p_1$, side: "right"),
          ar("B", "F", label: $p_2$),
          ar("C", "A", label: $tilde(cal(E))_1$, side: "right"),
          ar("D", "B", label: $tilde(cal(E))_2$),
          ar("C", "E", label: $cal(E)_1$),
          ar("D", "F", label: $cal(E)_2$, side: "right"),
          ar("C", "D", label: $phi$),
        ),
        column: 20mm,
        row: 16mm,
      )
    $
    where $cal(E)_i$, $tilde(cal(E))_i$ are defined as in
    @eq:torus-exponential-map, commutes (see
    Problem~@pr:covering-maps-maximal-tori).
    Theorem~@th:fundamental-group-via-characters implies that
    $tilde(Phi)(Ker p_1) = Ker p_2$ so that $tilde(Phi)$ determines the desired
    isomorphism $Phi: G_1 -> G_2$.]

  #hint[@pr:prove-global-uniqueness][Make use of
    Theorem~@th:cartan-matrix-determines-algebra and
    Problem~@pr:lattice-preserving-isomorphism-lifts.]

  #hint[@pr:semisimple-groups-cartan-subgroup-pairs][Let $A$ be the Cartan
    matrix of $frak(g)$. It follows from
    @eq:simple-roots-via-fundamental-weights that the isomorphism $ZZ^l -> P$
    sending the set $(k_1, ..., k_l)$ to $sum_(1 <= i <= l) k_i pi_i$ maps $Q_A$
    onto $Q$ and therefore induces an isomorphism $pi(A) -> pi(Delta_frak(g))$.
    With the subgroup $cal(X)(T)\/Q subset pi(Delta_frak(g))$ associated is an
    isomorphic subgroup $Z subset pi(A)$.
    Theorems~@th:global-uniqueness-semisimple-groups and
    @th:global-existence-semisimple-groups imply that the correspondence
    $G |-> (A, Z)$ determines the desired bijection.]

  #hint[@pr:prove-group-highest-weight][The uniqueness of the representation
    with given highest weight follows from
    Theorems~@th:highest-weight-determines-irreducible and
    @th:homomorphism-determined-by-differential. Let $Lambda in cal(X)(T)$ be a
    dominant character. By Theorem~@th:highest-weight-representation-exists
    there exists an irreducible finite-dimensional linear representation
    $rho: frak(g) -> frak(g l)(V)$ of $frak(g)$ with the highest weight
    $Lambda$. By Theorem~@th:homomorphism-existence-simply-connected
    $rho = d tilde(R)$ for an irreducible representation
    $tilde(R): tilde(G) -> GL(V)$, where $tilde(G)$ is a simply connected
    covering group of $G$. By Theorem~@th:fundamental-group-via-characters the
    kernel of the covering $phi: tilde(G) -> G$ is of the form
    $Ker phi = tilde(cal(E))(frak(t)(ZZ))$. On the other hand, it follows from
    Problem~@pr:highest-weight-exists that $Phi_(tilde(R)) subset cal(X)(T)$
    whence we derive that $tilde(R)(Ker phi) = e$ so that $tilde(R)$ determines
    the desired linear representation $R: G -> GL(V)$.]

  #hint[@pr:longest-element-highest-to-lowest][Let $B^+$ and $B^-$ be the Borel
    subgroups of $G$ corresponding to the Weyl chambers $C_0$ and $-C_0$ (see
    @ss:borel-subgroups-and-maximal-tori[°]). It follows from
    Problem~@pr:automorphisms-act-on-weights-roots that $n_0 B^+ n_0^(-1) = B^-$
    and $n_0 B^- n_0^(-1) = B^+$.]
]
