// Reference Chapter, § 1. Useful Formulae. Printed pages 289-292, up to
// § 2 Tables.
#import "main-defs.typ": *
#import "statements.typ": *

== Useful Formulae <sec:useful-formulae>

=== Weyl Groups and Exponents <ss:weyl-groups-and-exponents>
Let $G$ be a simply connected noncommutative simple complex Lie group, $frak(g)$
its tangent algebra, $W$ the Weyl group, $(alpha_0, alpha_1, ..., alpha_l)$ the
extended system of simple roots. Denote by $n_0, n_1, ..., n_l$ the coefficients
of the linear relation among $alpha_0, alpha_1, ..., alpha_l$ normed so that
$n_0 = 1$ (see Table~@tab:affine-dynkin-diagrams).

Let us arrange the positive roots of $frak(g)$ in a table in such a way that the
$k$-th row consist of the roots of height $k$ (see
Exercise~@exc:exterior-power-highest-vector) with aligned last elements of all
rows. The lengths of the rows of this table form a non-increasing sequence with
the first row of length $l$. Let $m_i$ be the number of elements in the $i$-th
column. The numbers $m_1, ..., m_l$ are called the #idx(
  "exponent",
)_exponents_ of $G$ (or $frak(g)$). (See Table~@tab:exponents).

Define the #idx("Killing-Coxeter element")_Killing---Coxeter_ element $c in W$:
$ c = r_1 ... r_l, $
where $r_1, ..., r_l$ are the reflections associated with the simple roots. The
element $c$ does not depend on the numbering of simple roots up to conjugacy in
$W$.

In this notation we have the following formulas.

#formula-item[The number of roots of $frak(g)$ equals
  $l sum n_i = 2 sum m_i$.] <eq:number-of-roots>

#formula-item[The order $z$ of $Z(G)$ equals the number of 1’s among
  $n_i$’s.] <eq:order-of-center>

#formula-item[The order of $W$ equals
  $ z l! product n_i = product (m_i + 1). $] <eq:weyl-group-order>

#formula-item[If $g_k$ is the number of elements of $W$, whose space of fixed
  elements is of dimension $l - k$, then
  $ sum g_k t^k = product (1 + m_i t) $] <eq:weyl-elements-by-fixed-space>

#formula-item[The order $h$ of $c$ (the #idx(
    "Coxeter number",
  )_Coxeter number_) equals
  $ sum n_i = max m_i + 1. $] <eq:coxeter-number>

#formula-item[The eigenvalues of $c$ are $epsilon^(m_1), ..., epsilon^(m_l)$,
  where $epsilon$ is a primitive root of degree $h$
  of 1.] <eq:coxeter-element-eigenvalues>

#formula-item[#source(305)The algebra of $W$-invariant polynomials on a maximal
  diagonalizable subalgebra is freely generated by homogeneous polynomials of
  degrees $m_1 + 1, ..., m_l + 1$.] <eq:weyl-invariant-degrees>

#formula-item[The Poincaré polynomial of $G$ is
  $product (1 + t^(2 m_i + 1))$.] <eq:lie-group-poincare-polynomial>

=== Linear Representations of Complex Semisimple Lie Algebras
<ss:representations-complex-semisimple>
Let $frak(g)$ be a semisimple complex Lie algebra. We will use the following
notation:

$R(Lambda)$ is the irreducible linear representation of $frak(g)$ with the
highest weight $Lambda$;

$V(Lambda)$ is the space of this representation;

$V_lambda (Lambda)$ is the weight subspace of $V(Lambda)$ corresponding to
$lambda$;

$m_lambda (Lambda) = dim V_lambda (Lambda)$ is the multiplicity of the weight
$lambda$ in $R(Lambda)$;

$Lambda' = nu(Lambda)$ is the highest weight of $R(Lambda)^*$;

$Lambda_i = Lambda(h_i)$ ($i = 1, ..., l$) are the “numerical labels” of the
weight $Lambda$;

$rho$ is the half sum of positive roots (see
Exercise~@exc:half-sum-positive-roots and Tables~@tab:weights-and-roots and
@tab:inverse-cartan-matrices).

The following formulas are valid:

#formula-item[#idx("Weyl formula")_H.~Weyl's formula_
  $
    dim R(Lambda)
    = product_(alpha > 0) ((Lambda + rho, alpha))/((rho, alpha)).
  $] <eq:weyl-dimension-formula>

#formula-item[#idx(
    "Freudenthal’s formula",
  )_Freudenthal's formula_ (see [@bib:Freudenthal1954] and Exercise 5 to §~9 of
  Chapter VIII in [@bib:Bourbaki1968]):
  $
    [(Lambda + rho, Lambda + rho) - (lambda + rho, lambda + rho)]
    m_lambda (Lambda)
    = 2 sum_(alpha > 0, k > 0) (lambda + k alpha, alpha)
    m_(lambda + k alpha) (Lambda).
  $] <eq:freudenthal-multiplicity-formula>

#formula-item[The multiplicity of $R(N)$ in $R(Lambda) times.o R(M)$ equals
  $
    dim {v in V_(N - Lambda) (M): d R(M)(e_i)^(Lambda_i + 1) v = 0
      quad "for" quad i = 1, ..., l} \
    = dim {v in V_(Lambda - M') (N): d R(N)(e_i)^(M'_i + 1) v = 0
      quad "for" quad i = 1, ..., l}
  $
  (see [@bib:Parthasarathy1967] and Exercise 14 to §~9 of Ch. VIII in
  [@bib:Bourbaki1968]).] <eq:tensor-product-multiplicity>

=== Linear Representations of Real Semisimple Lie Algebras
<ss:representations-real-semisimple>
Let $frak(g)$ be a real semisimple Lie algebra. We will use the following
notation.

If $rho: frak(g) -> frak("gl")(V)$ is a real linear representation, then
$rho(CC): frak(g) -> frak("gl")(V(CC))$ is the complex extension of $rho$.

If $rho: frak(g) -> frak("gl")(V)$ is a complex linear representation then
$overline(rho)$ is the representation $rho$ considered in the space
$overline(V)$ obtained from $V$ by the change of the sign of the complex
structure and $rho^RR$ is the representation $rho$ considered in the real space
$V^RR$.

We will say that a complex representation $rho$ #idx(
  "structure",
  "real",
)_admits a real_ (#idx("structure", "quaternionic")_quaternionic_) _structure_
if there is an antilinear operator $J$ in $V$ such that $J^2 = E$ (resp. $-E$)
commuting with any $rho(x)$ ($x in frak(g)$). A real structure exists if and
only if #source(306)$rho = rho_0 (CC)$, where
$rho_0: frak(g) -> frak("gl")(V^J)$ is a real representation, and a quaternionic
structure is the same as a quaternionic vector space structure on $V$ compatible
with $rho$.

The irreducible real representations of $frak(g)$ are divided into two classes
(see [@bib:Iwahori1959]): a) irreducible representations $rho$, for which
$rho(CC)$ is irreducible (over $CC$); b) representations $rho^RR$, where $rho$
is a complex irreducible representation that admits no real structure. In the
class a) $rho_1 tilde.op rho_2 <=> rho_1 (CC) tilde.op rho_2 (CC)$ and in the
class b) $rho_1^RR tilde.op rho_2^RR <=>$ either ($rho_1 tilde.op rho_2$) or
($rho_1 tilde.op overline(rho)_2$) (see
Exercises~@exc:complexified-representation-irreducible and
@exc:complex-type-representation-splits). Therefore the description of the
irreducible real representations reduces to the following two questions on
irreducible complex representations: When $rho_1 tilde.op overline(rho)_2$ (in
particular, when $rho tilde.op overline(rho)$)? Which irreducible
representations such that $rho tilde.op overline(rho)$ admit a real structure?
These questions are answered in terms of highest weights.

The #idx("weight of a representation", "highest")_highest weight of a real
irreducible representation_ $rho$ of $frak(g)$ is the highest weight $Lambda$ of
the extension of this representation to $frak(g)(CC)$; we will write
$rho = rho(Lambda)$, since $Lambda$ defines $rho$ up to an isomorphism
(Theorem~@th:highest-weight-determines-irreducible). Let $theta$ be the
canonical involutive automorphism of $frak(g)(CC)$ corresponding to the real
form $frak(g)$ and $tau = eta(theta)$ the corresponding automorphism of the
system of simple roots. Then
$
  overline(rho(Lambda)) = rho(nu tau(Lambda)).
$ <eq:conjugate-representation-weight>
In particular,
$
  rho(Lambda) tilde.op overline(rho(Lambda)) <=> nu tau(Lambda) = Lambda.
$ <eq:self-conjugate-criterion>

Now let $rho: frak(g) -> frak("gl")(V)$ be an irreducible complex representation
such that $rho tilde.op overline(rho)$. Then there exists an invertible
antilinear operator $J$ in $V$, commuting with $rho(x)$ ($x in frak(g)$), such
that $J^2 = c E$, where $c in RR^*$. The number
$epsilon(rho) = op("sign") c = plus.minus 1$ does not depend on the choice of
$J$ and is called the #idx("Index")_index of $rho$_ (see [@bib:Iwahori1959]).

Suppose $tau = id$, i.e. $theta in Int frak(g)(CC)$. Then
$rho(Lambda) tilde.op overline(rho(Lambda))$ is expressed as
$nu Lambda = Lambda$ and the index is calculated via the formula
$
  epsilon(rho(Lambda)) = (-1)^(2 Lambda(2 u + rho^or)),
$ <eq:index-for-inner-real-form>
where $exp(2 pi i u) = theta$ and
$rho^or = 1\/2 sum_(alpha > 0) h_alpha = sum_(1 <= i <= l) pi_(alpha_i^or)$
(see [@bib:Karpelevich1955]). In particular, for compact Lie algebras $frak(g)$
we have $epsilon(rho(Lambda)) = (-1)^(2 Lambda(rho^or)) = 1$ or $-1$ depending
on whether the nondegenerate bilinear form invariant with respect to $rho$ is
symmetric or skew-symmetric, respectively
(Exercise~@exc:orthogonal-symplectic-parity). If $tau != id$ and $frak(g)(CC)$
is simple then $rho(Lambda) tilde.op overline(rho(Lambda))$ if and only if
$Lambda_(2p - 1) = Lambda_(2p)$ for $frak(g)(CC) = frak("so")_(4p) (CC)$ and it
is always so if $frak(g)(CC)$ is of the type $A_l$ ($l > 1$), $D_(2p+1)$, $E_6$.
The corresponding indices were calculated in [@bib:Iwahori1959].

In the following table listed are the indices of irreducible complex
representations of non-compact real forms $frak(g)$ of simple complex Lie
algebras; for $frak(g)$ not mentioned in the table
$epsilon(rho) = 1$:#footnote[We are thankful to B.P.~Komrakov for a correction
  of this table.]
#source(307)
// The book prints two tables of four forms each, the forms in the first row
// and the indices in the second; at our type size such rows overflow the
// page, so the forms are listed in one column, in the book's order.
#figure(
  table(
    columns: 2,
    align: center + horizon,
    table.header(
      $frak(g)$,
      [$epsilon(rho(Lambda))$#ed-note[The book gives
          $(-1)^((k+1) p Lambda_(p-1))$ for $frak("su")_(k, 2p - k)$ and
          $(-1)^((k + l(l-1)\/2) Lambda_l)$ for $frak("so")_(2k, 2(l - k) + 1)$.
          Both contradict @eq:index-for-inner-real-form: for
          $frak("su")_(1, 3) tilde.eq frak(u)_3^* (HH)$ the representation
          $Lambda^2 CC^4$ is quaternionic, and for the split algebra
          $frak("so")_(4, 3)$ the spinor representation is real.]],
    ),

    $frak("su")_(k, 2p - k)$, $(-1)^((k + p) Lambda_p)$,

    $frak(u)_l^* (HH)$,
    $(-1)^(Lambda_1 + Lambda_3 + dots.c + Lambda_(2[l\/2] - 1))$,

    $frak("sl")_p (HH)$,
    $(-1)^(Lambda_1 + Lambda_3 + dots.c + Lambda_(2p - 1))$,

    $frak("so")_(2k - 1, 2(l - k) + 1)$,
    $(-1)^(((k + 1) + (l - 1)(l - 2)\/2)(Lambda_(l - 1) + Lambda_l))$,

    $frak("so")_(2k, 2(l - k) + 1)$, $(-1)^((k + l(l + 1)\/2) Lambda_l)$,

    $frak("so")_(2k, 2(2p - k))$,
    $(-1)^((k + p)(Lambda_(2p - 1) + Lambda_(2p)))$,

    $frak("sp")_(k, l - k)$,
    $(-1)^(Lambda_1 + Lambda_3 + dots.c + Lambda_(2[(l - 1)\/2] + 1))$,

    real-form("EVI"), $(-1)^(Lambda_1 + Lambda_3 + Lambda_7)$,
  ),
  numbering: none,
)

Let $frak(g) = frak(g)_0^RR$, where $frak(g)_0$ is a simple Lie algebra over
$CC$. Making use of the normal real form of $frak(g)_0$ we may identify
$frak(g)(CC) tilde.eq frak(g)_0 plus.o overline(frak(g))_0$ with
$frak(g)_0 plus.o frak(g)_0$. A dominant weight of $frak(g)(CC)$ is expressed in
the form $Lambda = (Lambda_1, Lambda^1)$, where $Lambda_1, Lambda^1$ are
dominant weights of $frak(g)_0$. The condition
$rho(Lambda) tilde.op overline(rho(Lambda))$ is expressed by the identity
$Lambda_1 = Lambda^1$ with $epsilon(rho(Lambda)) = 1$.

Finally, let us describe how to calculate the index of a representation of any
semisimple Lie algebra $frak(g)$ over $RR$. Let
$frak(g) = plus.o.big_(1 <= i <= s) frak(g)_i$, where $frak(g)_i$ are simple,
and $Lambda = (Lambda_1, ..., Lambda_s)$, where $Lambda_i$ is a dominant weight
of $frak(g)_i (CC)$. Then $rho(Lambda) tilde.op overline(rho(Lambda))$ if and
only if $rho(Lambda_i) = overline(rho(Lambda_i))$ for all $i = 1, ..., s$ and
$epsilon(rho(Lambda)) = product_(1 <= i <= s) epsilon(rho(Lambda_i))$.
