// Reference Chapter, § 2. Tables: Tables 9 and 10. Printed pages 312-321.
// Table 9 fills three spreads (312-317): the left page of each carries the
// columns g(C), g, k, dim k, dim p, rk g, the right page the Satake
// diagrams and the columns Type of Σ, r, dim g_λ, dim g_2λ of the same
// rows, in the same order. Table 10 begins on page 318 with its
// description; its body is printed sideways on pages 319-320 and upright
// on page 321. Page 322 begins the Bibliography.
#import "main-defs.typ": *
#import "statements.typ": *
#import "diagrams/dynkin.typ": bond, dynkin, gap, pair, v
#import "diagrams/76-tables-9-10.typ": e6-arched

// Satake diagrams of Table 9. The widest (eight grid steps) and the four
// columns beside it share the width of the page only with a grid a little
// smaller than the default of dynkin.typ.
#let table-9-grid = 7mm
#let satake = dynkin.with(unit: table-9-grid)

// The cyclic group ⟨Z⟩_m of order m generated by Z (Table 10).
#let cyclic(generator, order) = $chevron.l generator chevron.r_order$

// Table 9 is printed on three spreads, and its blocks follow them: the left
// page of a spread, the real forms and their Cartan decompositions, then the
// right page, the same rows continued.
#let table-9-left(
  columns: (auto, auto, auto, 1fr, auto, auto),
  ..rows,
) = book-table(
  columns: columns,
  align: center + horizon,
  head: (
    [$frak(g)(CC)$],
    [$frak(g)$],
    [$frak(k)$],
    [$dim frak(k)$],
    [$dim frak(p)$],
    [$rk_RR frak(g)$],
  ),
  ..rows,
)
#let table-9-right(
  columns: (auto, auto, 1.15fr, 1fr, auto),
  ..rows,
) = book-table(
  columns: columns,
  align: center + horizon,
  head: (
    [Satake diagram],
    [Type \ of $Sigma$],
    [$r$],
    [$dim frak(g)_(lambda_j)$],
    [$dim frak(g)_(2 lambda_j)$],
  ),
  ..rows,
)

// A sideways part of Table 10 (pages 319-320), one page as printed. Its
// columns but one are as wide as their widest entry, which a wider inset
// than the tables' keeps clear of the rules.
#let table-10(..rows) = sideways(book-table(
  columns: (auto, auto, 1fr, auto, auto, auto),
  inset: (x: 0.7em, y: 0.5em),
  align: (
    center + horizon,
    center + horizon,
    left + horizon,
    center + horizon,
    center + horizon,
    center + horizon,
  ),
  head: (
    [$frak(g)$],
    [$Z(G)$],
    table.cell(align: center + horizon)[Generators of $Z(G)$],
    [$Lambda(G)$],
    [$G_"lin"$],
    [$b_0$],
  ),
  ..rows,
))

#table-section[Real Simple Lie Algebras] <tab:real-simple-lie-algebras>
#source(327)In the table are listed noncompact real Lie algebras $frak(g)$ that
do not admit a complex structure, i.e. the real forms of complex simple Lie
algebras $frak(g)(CC)$. The column "Type of $Sigma$" contains the type of the
system $Sigma$ of real roots. The column "$r$" describes the restriction map
$r: Pi_1 -> Theta$, where $Theta$ is the base of $Sigma$. The simple roots from
$Pi$ are denoted by $alpha_j$, those from $Theta$ by $lambda_j$; the numbering
in both these systems is the same as in Table~@tab:weights-and-roots.

#table-9-left(
  table.cell(rowspan: 4)[$frak(s l)_(l+1) (CC)$ \ $(l >= 1)$],
  [$frak(s l)_(l+1) (RR)$],
  [$frak(s o)_(l+1)$],
  [$l(l + 1)\/2$],
  [$l(l + 3)\/2$],
  [$l$],

  [$frak(s l)_(p+1) (HH)$ \ $(l = 2p + 1, p >= 1)$],
  [$frak(s p)_(p+1)$],
  [$(p + 1)(2p + 3)$],
  [$p(2p + 3)$],
  [$p$],

  [$frak(s u)_(p, l+1-p)$ \ $(1 <= p <= l\/2)$],
  [$frak(s u)_p plus.o frak(u)_(l+1-p)$],
  [$p^2$ \ $+ (l + 1 - p)^2 - 1$],
  [$2p(l + 1 - p)$],
  [$p$],

  [$frak(s u)_(p, p)$ \ $(l = 2p - 1, p >= 2)$],
  [$frak(s u)_p plus.o frak(u)_p$],
  [$2p^2 - 1$],
  [$2p^2$],
  [$p$],

  [$frak(s o)_(2l+1) (CC)$ \ $(l >= 1)$],
  [$frak(s o)_(p, 2l+1-p)$ \ $(1 <= p <= l)$],
  [$frak(s o)_p plus.o frak(s o)_(2l+1-p)$],
  [$p(p - 1)\/2$ \ $+ (2l + 1 - p)$ \ $dot.c (2l - p)\/2$],
  [$p(2l + 1 - p)$],
  [$p$],

  table.cell(rowspan: 3)[$frak(s p)_(2l) (CC)$],
  [$frak(s p)_(2l) (RR)$],
  [$frak(u)_l$],
  [$l^2$],
  [$l(l + 1)$],
  [$l$],

  [$frak(s p)_(p, l-p)$ \ $(1 <= p <= ½(l - 1))$],
  [$frak(s p)_p plus.o frak(s p)_(l-p)$],
  [$p(2p + 1)$ \ $+ (l - p)$ \ $(2l - 2p + 1)$],
  [$4p(l - p)$],
  [$p$],

  [$frak(s p)_(p, p)$ \ $(l = 2p)$],
  [$frak(s p)_p plus.o frak(s p)_p$],
  [$2p(2p + 1)$],
  [$4p^2$],
  [$p$],
)

#source(328)#table-9-right(
  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(3, 0, label: [ℓ−1]),
      d: v(4, 0, label: [ℓ]),
    ),
    (bond("a", "b"), gap("b", "c"), bond("c", "d")),
  ),
  [$A_l$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= l)$],
  [$1$],
  [$0$],

  satake(
    (
      a: v(0, 0, black: true),
      b: v(1, 0, label: [2]),
      c: v(2, 0, black: true),
      d: v(4, 0, label: [2p]),
      e: v(5, 0, black: true),
    ),
    (bond("a", "b"), bond("b", "c"), gap("c", "d"), bond("d", "e")),
  ),
  [$A_p$],
  [$r(alpha_(2j)) = lambda_j$ \ $(1 <= j <= p)$],
  [$4$],
  [$0$],

  table.cell(rowspan: 2, satake(
    (
      a1: v(0, 0, label: [1]),
      a2: v(1, 0, label: [2]),
      a3: v(3, 0, label: [p]),
      c1: v(4, 0, black: true),
      c2: v(4, -1, black: true),
      c3: v(4, -3, black: true),
      c4: v(4, -4, black: true),
      b1: v(0, -4, label: [ℓ], at: "below"),
      b2: v(1, -4, label: [ℓ−1], at: "below"),
      b3: v(3, -4, label: [ℓ+1−p], at: "below"),
    ),
    (
      bond("a1", "a2"),
      gap("a2", "a3"),
      bond("a3", "c1"),
      bond("c1", "c2"),
      gap("c2", "c3"),
      bond("c3", "c4"),
      bond("b1", "b2"),
      gap("b2", "b3"),
      bond("b3", "c4"),
      pair("a1", "b1"),
      pair("a2", "b2"),
      pair("a3", "b3"),
    ),
  )),
  table.cell(rowspan: 2)[$B C_p$],
  table.cell(rowspan: 2)[$r(alpha_j)$ \ $= r(alpha_(l+1-j))$ \ $= lambda_j$ \
    $(1 <= j <= p)$],
  [$2$ $(j <= p - 1)$],
  [$0$],
  [$2(l + 1 - 2p)$ \ $(j = p)$],
  [$1$],

  satake(
    (
      a1: v(0, 1, label: [1]),
      a2: v(1, 1, label: [2]),
      a3: v(3, 1, label: [p−1]),
      m: v(4, 0, label: [p], at: "right"),
      b1: v(0, -1, label: [2p−1], at: "below"),
      b2: v(1, -1, label: [2p−2], at: "below"),
      b3: v(3, -1, label: [p+1], at: "below"),
    ),
    (
      bond("a1", "a2"),
      gap("a2", "a3"),
      bond("a3", "m"),
      bond("b1", "b2"),
      gap("b2", "b3"),
      bond("b3", "m"),
      pair("a1", "b1"),
      pair("a2", "b2"),
      pair("a3", "b3"),
    ),
  ),
  [$C_p$],
  [$r(alpha_j)$ \ $= r(alpha_(2p-j))$ \ $= lambda_j$ \
    $(1 <= j <= p)$],
  [$2$ $(j <= p - 1)$ \ $1$ $(j = p)$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(3, 0, label: [p]),
      d: v(4, 0, black: true),
      e: v(6, 0, black: true),
      f: v(7, 0, black: true),
    ),
    (
      bond("a", "b"),
      gap("b", "c"),
      bond("c", "d"),
      gap("d", "e"),
      bond("e", "f", 2, to: "f"),
    ),
  ),
  [$B_p$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= p)$],
  [$1$ $(j <= p - 1)$ \ $2(l - p) + 1$ \ $(j = p)$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(3, 0, label: [ℓ−1]),
      d: v(4, 0, label: [ℓ]),
    ),
    (bond("a", "b"), gap("b", "c"), bond("c", "d", 2, to: "c")),
  ),
  [$C_l$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= l)$],
  [$1$],
  [$0$],

  table.cell(rowspan: 2, satake(
    (
      a: v(0, 0, black: true),
      b: v(1, 0, label: [2]),
      c: v(2, 0, black: true),
      d: v(4, 0, label: [2p]),
      e: v(5, 0, black: true),
      f: v(7, 0, black: true),
      g: v(8, 0, black: true),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      gap("c", "d"),
      bond("d", "e"),
      gap("e", "f"),
      bond("f", "g", 2, to: "f"),
    ),
  )),
  table.cell(rowspan: 2)[$B C_p$],
  table.cell(rowspan: 2)[$r(alpha_(2j)) = lambda_j$ \ $(1 <= j <= p)$],
  [$4$ $(j <= p - 1)$],
  [$0$],
  [$4(l - 2p)$ \ $(j = p)$],
  [$3$],

  satake(
    (
      a: v(0, 0, black: true),
      b: v(1, 0, label: [2]),
      c: v(2, 0, black: true),
      d: v(4, 0, label: [2p−2]),
      e: v(5, 0, black: true),
      f: v(6, 0, label: [2p]),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      gap("c", "d"),
      bond("d", "e"),
      bond("e", "f", 2, to: "e"),
    ),
  ),
  [$C_p$],
  [$r(alpha_(2j)) = lambda_j$ \ $(1 <= j <= p)$],
  [$4$ $(j <= p - 1)$ \ $3$ $(j = p)$],
  [$0$],
)

#source(329)#table-9-left(
  table.cell(rowspan: 5)[$frak(s o)_(2l) (CC)$ \ $(l >= 4)$],
  [$frak(s o)_(p, 2l-p)$ \ $(1 <= p <= l - 2)$],
  [$frak(s o)_p times frak(s o)_(2l-p)$],
  [$p(p - 1)\/2 + (2l - p)$ \ $dot.c (2l - p - 1)\/2$],
  [$p(2l - p)$],
  [$p$],

  [$frak(s o)_(l-1, l+1)$],
  [$frak(s o)_(l-1) times frak(s o)_(l+1)$],
  [$(l - 1)(l - 2)\/2$ \ $+ l(l + 1)\/2$],
  [$l^2 - 1$],
  [$l - 1$],

  [$frak(s o)_(l, l)$],
  [$frak(s o)_l times frak(s o)_l$],
  [$l(l - 1)$],
  [$l^2$],
  [$l$],

  [$frak(u)_(2p)^* (HH)$ \ $(l = 2p)$],
  [$frak(u)_(2p)$],
  [$4p^2$],
  [$2p(2p - 1)$],
  [$p$],

  [$frak(u)_(2p+1)^* (HH)$ \ $(l = 2p + 1)$],
  [$frak(u)_(2p+1)$],
  [$(2p + 1)^2$],
  [$2p(2p + 1)$],
  [$p$],

  table.cell(rowspan: 4)[$E_6$],
  real-form("EI"),
  [$frak(s p)_4$],
  [$36$],
  [$42$],
  [$6$],
  real-form("EII"),
  [$frak(s u)_2 plus.o frak(s u)_6$],
  [$38$],
  [$40$],
  [$4$],
  real-form("EIII"),
  [$frak(s o)_10 plus.o RR$],
  [$46$],
  [$32$],
  [$2$],
  real-form("EIV"),
  [$F_4$],
  [$52$],
  [$26$],
  [$2$],
)

#source(330)#table-9-right(
  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(3, 0, label: [p]),
      d: v(4, 0, black: true),
      e: v(6, 0, black: true),
      f: v(7, 0.5, black: true),
      g: v(7, -0.5, black: true),
    ),
    (
      bond("a", "b"),
      gap("b", "c"),
      bond("c", "d"),
      gap("d", "e"),
      bond("e", "f"),
      bond("e", "g"),
    ),
  ),
  [$B_p$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= p)$],
  [$1$ $(j <= p - 1)$ \ $2(l - p)$ \ $(j = p)$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(3, 0, label: [ℓ−2], at: "north-west"),
      d: v(4, 0.5, label: [ℓ−1], at: "right"),
      e: v(4, -0.5, label: [ℓ], at: "right"),
    ),
    (
      bond("a", "b"),
      gap("b", "c"),
      bond("c", "d"),
      bond("c", "e"),
      pair("d", "e"),
    ),
  ),
  [$B_(l-1)$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= l - 1)$, \
    $r(alpha_l) = lambda_(l-1)$],
  [$1$ $(j <= l - 2)$ \ $2$ $(j = l - 1)$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(3, 0, label: [ℓ−2], at: "north-west"),
      d: v(4, 0.5, label: [ℓ−1], at: "right"),
      e: v(4, -0.5, label: [ℓ], at: "right"),
    ),
    (bond("a", "b"), gap("b", "c"), bond("c", "d"), bond("c", "e")),
  ),
  [$D_l$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= l)$],
  [$1$],
  [$0$],

  satake(
    (
      a: v(0, 0, black: true),
      b: v(1, 0, label: [2]),
      c: v(2, 0, black: true),
      d: v(4, 0, label: [2p−2], at: "north-west"),
      e: v(5, 0.5, black: true),
      f: v(5, -0.5, label: [2p], at: "right"),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      gap("c", "d"),
      bond("d", "e"),
      bond("d", "f"),
    ),
  ),
  [$C_p$],
  [$r(alpha_(2j)) = lambda_j$ \ $(1 <= j <= p)$],
  [$4$ $(j <= p - 1)$ \ $1$ $(j = p)$],
  [$0$],

  satake(
    (
      a: v(0, 0, black: true),
      b: v(1, 0, label: [2]),
      c: v(2, 0, black: true),
      d: v(4, 0, label: [2p−2]),
      e: v(5, 0, black: true),
      f: v(6, 0.5, label: [2p], at: "right"),
      g: v(6, -0.5, label: [2p+1], at: "right"),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      gap("c", "d"),
      bond("d", "e"),
      bond("e", "f"),
      bond("e", "g"),
      pair("f", "g"),
    ),
  ),
  [$B C_p$],
  [$r(alpha_(2j)) = lambda_j$ \ $(1 <= j <= p)$ \
    $r(alpha_(2p+1)) = lambda_p$],
  [$4$],
  [$0$ $(j <= p - 1)$ \ $1$ $(j = p)$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(2, 0, label: [3]),
      d: v(3, 0, label: [4]),
      e: v(4, 0, label: [5]),
      f: v(2, -1, label: [6], at: "right"),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      bond("c", "d"),
      bond("d", "e"),
      bond("c", "f"),
    ),
  ),
  [$E_6$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= 6)$],
  [$1$],
  [$0$],

  e6-arched(
    labels: (
      "1": "south",
      "2": "south",
      "3": "south-east",
      "4": "south",
      "5": "south",
      "6": "east",
    ),
    arcs: (("1", "5", 0.85), ("2", "4", 0.45)),
    unit: table-9-grid,
  ),
  [$F_4$],
  [$r(alpha_1) = r(alpha_5)$ \ $= lambda_1$, \
    $r(alpha_2) = r(alpha_4)$ \ $= lambda_2$, \
    $r(alpha_3) = lambda_3$, \ $r(alpha_6) = lambda_4$],
  [$2$ $(j = 1, 2)$ \ $1$ $(j = 3, 4)$],
  [$0$],

  table.cell(rowspan: 2, e6-arched(
    filled: ("2", "3", "4"),
    labels: ("1": "south", "5": "south", "6": "east"),
    arcs: (("1", "5", 0.85),),
    unit: table-9-grid,
  )),
  table.cell(rowspan: 2)[$B C_2$],
  table.cell(rowspan: 2)[$r(alpha_1) = r(alpha_5)$ \ $= lambda_2$, \
    $r(alpha_6) = lambda_1$],
  [$6$ $(j = 1)$],
  [$0$],
  [$8$ $(j = 2)$],
  [$1$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, black: true),
      c: v(2, 0, black: true),
      d: v(3, 0, black: true),
      e: v(4, 0, label: [5]),
      f: v(2, -1, black: true),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      bond("c", "d"),
      bond("d", "e"),
      bond("c", "f"),
    ),
  ),
  [$A_2$],
  [$r(alpha_1) = lambda_1$, \ $r(alpha_5) = lambda_2$],
  [$8$],
  [$0$],
)

#source(331)#table-9-left(
  columns: (1.5fr, 2.5fr, 2.1fr, 2.5fr, 1.7fr, 1fr),
  table.cell(rowspan: 3)[$E_7$],
  real-form("EV"),
  [$frak(s u)_8$],
  [$63$],
  [$70$],
  [$7$],
  real-form("EVI"),
  [$frak(s u)_2 plus.o frak(s o)_12$],
  [$69$],
  [$64$],
  [$4$],
  real-form("EVII"),
  [$E_6 plus.o RR$],
  [$79$],
  [$54$],
  [$3$],
  table.cell(rowspan: 2)[$E_8$],
  real-form("EVIII"),
  [$frak(s o)_16$],
  [$120$],
  [$128$],
  [$8$],
  real-form("EIX"),
  [$frak(s u)_2 plus.o E_7$],
  [$136$],
  [$112$],
  [$4$],
  table.cell(rowspan: 2)[$F_4$],
  real-form("FI"),
  [$frak(s u)_2 plus.o frak(s p)_3$],
  [$24$],
  [$28$],
  [$4$],
  real-form("FII"),
  [$frak(s o)_9$],
  [$36$],
  [$16$],
  [$1$],
  [$G_2$],
  real-form("G"),
  [$frak(s o)_3 plus.o frak(s o)_3$],
  [$6$],
  [$8$],
  [$2$],
)

#source(332)#table-9-right(
  columns: (auto, auto, auto, 1fr, auto),
  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(2, 0, label: [3]),
      d: v(3, 0, label: [4]),
      e: v(4, 0, label: [5]),
      f: v(5, 0, label: [6]),
      g: v(3, -1, label: [7], at: "right"),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      bond("c", "d"),
      bond("d", "e"),
      bond("e", "f"),
      bond("d", "g"),
    ),
  ),
  [$E_7$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= 7)$],
  [$1$],
  [$0$],

  satake(
    (
      a: v(0, 0, black: true),
      b: v(1, 0, label: [2]),
      c: v(2, 0, black: true),
      d: v(3, 0, label: [4]),
      e: v(4, 0, label: [5]),
      f: v(5, 0, label: [6]),
      g: v(3, -1, black: true),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      bond("c", "d"),
      bond("d", "e"),
      bond("e", "f"),
      bond("d", "g"),
    ),
  ),
  [$F_4$],
  [$r(alpha_2) = lambda_1$, $r(alpha_4) = lambda_2$, \
    $r(alpha_5) = lambda_3$, $r(alpha_6) = lambda_4$],
  [$4$ $(j = 1, 2)$ \ $1$ $(j = 3, 4)$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(2, 0, black: true),
      d: v(3, 0, black: true),
      e: v(4, 0, black: true),
      f: v(5, 0, label: [6]),
      g: v(3, -1, black: true),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      bond("c", "d"),
      bond("d", "e"),
      bond("e", "f"),
      bond("d", "g"),
    ),
  ),
  [$C_3$],
  [$r(alpha_6) = lambda_1$, $r(alpha_2) = lambda_2$, \
    $r(alpha_1) = lambda_3$],
  [$8$ $(j = 1, 2)$ \ $1$ $(j = 3)$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(2, 0, label: [3]),
      d: v(3, 0, label: [4]),
      e: v(4, 0, label: [5]),
      f: v(5, 0, label: [6]),
      g: v(6, 0, label: [7]),
      h: v(4, -1, label: [8], at: "below"),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      bond("c", "d"),
      bond("d", "e"),
      bond("e", "f"),
      bond("f", "g"),
      bond("e", "h"),
    ),
  ),
  [$E_8$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= 8)$],
  [$1$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(2, 0, label: [3]),
      d: v(3, 0, black: true),
      e: v(4, 0, black: true),
      f: v(5, 0, black: true),
      g: v(6, 0, label: [7]),
      h: v(4, -1, black: true),
    ),
    (
      bond("a", "b"),
      bond("b", "c"),
      bond("c", "d"),
      bond("d", "e"),
      bond("e", "f"),
      bond("f", "g"),
      bond("e", "h"),
    ),
  ),
  [$F_4$],
  [$r(alpha_7) = lambda_1$, $r(alpha_3) = lambda_2$, \
    $r(alpha_2) = lambda_3$, $r(alpha_1) = lambda_4$],
  [$8$ $(j = 1, 2)$ \ $1$ $(j = 3, 4)$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, label: [2]),
      c: v(2, 0, label: [3]),
      d: v(3, 0, label: [4]),
    ),
    (bond("a", "b"), bond("b", "c", 2, to: "b"), bond("c", "d")),
  ),
  [$F_4$],
  [$r(alpha_j) = lambda_j$ \ $(1 <= j <= 4)$],
  [$1$],
  [$0$],

  satake(
    (
      a: v(0, 0, label: [1]),
      b: v(1, 0, black: true),
      c: v(2, 0, black: true),
      d: v(3, 0, black: true),
    ),
    (bond("a", "b"), bond("b", "c", 2, to: "b"), bond("c", "d")),
  ),
  [$B C_1$],
  [$r(alpha_1) = lambda_1$],
  [$8$],
  [$7$],

  satake(
    (a: v(0, 0, label: [1]), b: v(1, 0, label: [2])),
    (bond("a", "b", 3, to: "a"),),
  ),
  [$G_2$],
  [$r(alpha_j) = lambda_j$ \ $(j = 1, 2)$],
  [$1$],
  [$0$],
)

#table-section[Centers and Linearizers of Simply Connected Real Simple Lie
  Groups] <tab:centers-and-linearizers>
#source(333)Denote by $frak(g)$ a noncompact real simple Lie algebra that does
not admit a complex structure, $G$ the corresponding simply connected Lie group.
Denote by $cyclic(Z, m)$ the cyclic group of order $m = 2, 3, ..., oo$ with
generator $Z$. In the column "Generators" representatives of the generators of
$Z(G)$ in the lattice $P^or (Delta_(frak(g)(CC))) inter frak(k)(CC)$ (see
Theorem~@th:real-semisimple-center-fundamental-group) are listed. In the fifth
column the group $G_"lin" = G\/Lambda(G)$ is given (for classical $frak(g)$);
here $Spin_(p, q)$ denotes the connected real form of the group
$Spin_(p+q) (CC)$ (see exercises to §~@sec:existence-uniqueness-theorems)
corresponding to the real form $frak(s o)_(p, q)$ of $frak(s o)_(p+q) (CC)$. In
the column "$b_0$" indicated is a representative of an element $b_0 in Z(G)$
with the property $R(b_0) = epsilon(d R) id$, where $R$ is an irreducible
complex representation of $G$ such that $overline(d R) tilde.op d R$ (see
@ss:representations-real-semisimple[°]).#ed-note[In the row
  $frak(s o)_(2p, 2(l-p)+1)$ the book admits $p = l$. For $frak(s o)_(2l, 1)$,
  however, $Z(G) = cyclic(Z_2, 2)$ with $Z_2 = h_l\/2$, $Lambda(G) = {e}$,
  $G_"lin" = Spin_(2l, 1)$ and $b_0 = (l + l(l + 1)\/2) Z_2$
  (Theorems~@th:real-semisimple-center-fundamental-group and
  @th:linearizer-via-characteristic-lattice). The table also omits
  $frak(s o)_(1, 2l-1)$, $l >= 4$: there $Z(G) = cyclic(Z_2, 2)$ with
  $Z_2 = (h_(l-1) + h_l)\/2$, $Lambda(G) = {e}$, $G_"lin" = Spin_(1, 2l-1)$ and
  $b_0 = ((l - 1)(l - 2)\/2) Z_2$.]

#source(334)#table-10(
  [$frak(s l)_(2p+1) (RR)$ \ $(p >= 1)$],
  [$cyclic(Z_1, 2)$],
  [$Z_1 = h_p + h_(p+1)$],
  [$cyclic(Z_1, 2)$],
  [$SL_(2p+1) (RR)$],
  [$0$],

  [$frak(s l)_(4p+2) (RR)$ \ $(p >= 1)$],
  [$cyclic(Z_2, 4)$],
  [$Z_2 = (h_1 + h_3 + dots.c + h_(4p+1))\/2$],
  [$cyclic(2Z_2, 2)$],
  [$SL_(4p+2) (RR)$],
  [$0$],

  [$frak(s l)_(4p) (RR)$ \ $(p >= 1)$],
  [$cyclic(Z_2, 2) times cyclic(Z_3, 2)$],
  [$Z_2 = (h_1 + h_3 + dots.c + h_(4p-1))\/2$ \ $Z_3 = h_(2p)$],
  [$cyclic(Z_3, 2)$],
  [$SL_(4p) (RR)$],
  [$0$],

  [$frak(s l)_p (HH)$ \ $(p >= 2)$],
  [$cyclic(Z_2, 2)$],
  [$Z_2 = (h_1 + h_3 + dots.c + h_(2p-1))\/2$],
  [${e}$],
  [$SL_p (HH)$],
  [$Z_2$],

  [$frak(s u)_(p, q)$ \ $1 <= p <= q$],
  [$cyclic(Z_4, oo) times cyclic(Z_5, d)$, \ $d = op("LCD") (p, q)$],
  [$Z_4 = a pi_1^or + b pi_(p+q-1)^or$, where $a q + b p = d$; \
    $Z_5 = (p pi_1^or - q pi_(p+q-1)^or)\/d$],
  [$cyclic(pi_1^or + pi_(p+q-1)^or, oo)$],
  [$SU_(p, q)$],
  [$pi_p^or + rho^or$],

  [$frak(s o)_(2, 2l-1)$],
  [$cyclic(Z_1, oo) times cyclic(Z_2, 2)$],
  [$Z_1 = h_1, quad Z_2 = h_l\/2$],
  [$cyclic(Z_1, oo)$],
  [$Spin_(2, 2l-1)$],
  [$(1 + l(l + 1)\/2)Z_2$],

  [$frak(s o)_(2p, 2(l-p)+1)$ \ $(2 <= p < l)$],
  [$cyclic(Z_1, 2) times cyclic(Z_2, 2)$],
  [$Z_1 = h_p, quad Z_2 = h_l\/2$],
  [$cyclic(Z_1, 2)$],
  [$Spin_(2p, 2(l-p)+1)$],
  [$(p + l(l + 1)\/2)Z_2$],

  [$frak(s p)_(4p+2) (RR)$ \ $(p >= 0)$],
  [$cyclic(Z_1, oo)$],
  [$Z_1 = (h_1 + h_3 + dots.c + h_(2p+1))\/2$],
  [$cyclic(2Z_1, oo)$],
  [$Sp_(4p+2) (RR)$],
  [$0$],

  [$frak(s p)_(4p) (RR)$ \ $(p >= 1)$],
  [$cyclic(Z_1, 2) times cyclic(Z_2, oo)$],
  [$Z_1 = (h_1 + h_3 + dots.c + h_(2p-1))\/2$ \ $Z_2 = h_(2p)$],
  [$cyclic(Z_2, oo)$],
  [$Sp_(4p) (RR)$],
  [$0$],

  [$frak(s p)_(p, q)$ \ $(1 <= p <= q)$],
  [$cyclic(Z_1, 2)$],
  [$Z_1 = (h_1 + h_3 + dots.c)\/2$],
  [${e}$],
  [$Sp_(p, q)$],
  [$Z_1$],
)

#source(335)#table-10(
  [$frak(s o)_(2, 2l-2)$ \ $(l >= 3)$],
  [$cyclic(Z_1, oo) times cyclic(Z_2, 2)$],
  [$Z_1 = pi_(l-1)^or$, \ $Z_2 = (h_(l-1) + h_l)\/2$],
  [$cyclic(2Z_1, oo) (l = 2p)$ \ $cyclic(2Z_1 + Z_2, oo)$ \
    $(l = 2p + 1)$],
  [$Spin_(2, 2l-2)$],
  [$Z_2$ if $l = 4q$ \ or $4q + 1$, $0$ otherwise],

  [$frak(s o)_(2p, 2(l-p))$ \ $l = 2q + 1$ \ $(2 <= p <= [l\/2])$],
  [$cyclic(Z_1, 4) times cyclic(Z_3, 2)$],
  [$Z_1 = pi_(l-1)^or$, \ $Z_3 = h_p$],
  [$cyclic(Z_3, 2)$],
  [$Spin_(2p, 2(l-p))$],
  [$(p + q)Z_2$],

  [$frak(s o)_(2p, 2(l-p))$ \ $(2 <= p <= l\/2)$ \ $l = 2q$, $p$ odd],
  [$cyclic(Z_1, 4) times cyclic(Z_4, 2)$],
  [$Z_1 = pi_(l-1)^or$, \ $Z_4 = h_p + (h_(l-1) + h_l)\/2$],
  [$cyclic(2Z_1, 2)$],
  [$Spin_(2p, 2(l-p))$],
  [$(1 + q)Z_2$],

  [$frak(s o)_(2p, 2(l-p))$ \ $(2 <= p <= l\/2)$ \ $l$, $p$ even, $l = 2q$],
  [$cyclic(Z_1, 2) times cyclic(Z_4, 2)$ \ $times cyclic(Z_5, 2)$],
  [$Z_1 = pi_(l-1)^or$, \ $Z_4 = h_p + (h_(l-1) + h_l)\/2$ \
    $Z_5 = pi_l^or$],
  [$cyclic(Z_1 + Z_4 + Z_5, 2)$],
  [$Spin_(2p, 2(l-p))$],
  [$q Z_2$],

  [$frak(s o)_(2p+1, 2(l-p)-1)$ \ $(1 <= p <= [(l - 1)\/2])$],
  [$cyclic(Z_2, 2) times cyclic(Z_3, 2)$],
  [$Z_2 = (h_(l-1) + h_l)\/2$ \ $Z_3 = h_p$],
  [$cyclic(Z_3, 2)$],
  [$Spin_(2p+1, 2(l-p)-1)$],
  [$(p + (l - 1)(l - 2)\/2)Z_2$],

  [$frak(u)_l^* (HH)$ \ $l = 2p + 1$ \ $(p >= 1)$],
  [$cyclic(Z_6, oo)$],
  [$Z_6 = pi_(l-1)^or - p(h_(l-1) + h_l)\/2$],
  [$cyclic(4Z_6, oo)$],
  table.cell(rowspan: 3)[The two-sheeted \ covering of the \ group
    $upright(U)_l^* (HH)$],
  [$(h_1 + h_3 + dots.c + h_(2p-1))\/2$ \ $+ (h_(2p) - h_(2p+1))\/4$],

  [$frak(u)_l^* (HH)$ \ $l = 4p + 2$ \ $(p >= 0)$],
  [$cyclic(Z_7, 2) times cyclic(Z_8, oo)$],
  [$Z_7 = pi_(l-1)^or - p(h_(l-1) + h_l)$, \
    $Z_8 = pi_l^or - p(h_(l-1) + h_l)$],
  [$cyclic(2Z_8, oo)$],
  [$(h_1 + h_3 + dots.c + h_(4p+1))\/2$],

  [$frak(u)_l^* (HH)$ \ $l = 4p$ $(p >= 1)$],
  [$cyclic(Z_9, 2) times cyclic(Z_10, oo)$],
  [$Z_9 = pi_l^or - p(h_(l-1) + h_l)$, \
    $Z_10 = pi_(l-1)^or - p(h_(l-1) + h_l)$],
  [$cyclic(2Z_10, oo)$],
  [$(h_1 + h_3 + dots.c + h_(4p-1))\/2$],
)

#source(336)#book-table(
  columns: (1.3fr, 2.3fr, 3.6fr, 1.45fr, 0.9fr),
  align: (
    center + horizon,
    center + horizon,
    left + horizon,
    center + horizon,
    center + horizon,
  ),
  head: (
    [$frak(g)$],
    [$Z(G)$],
    table.cell(align: center + horizon)[Generators of $Z(G)$],
    [$Lambda(G)$],
    [$b_0$],
  ),
  real-form("EI"),
  [$cyclic(Z_1, 2)$],
  [$Z_1 = h_6$],
  [$cyclic(Z_1, 2)$],
  [$0$],
  real-form("EII"),
  [$cyclic(Z_2, 6)$],
  [$Z_2 = (h_1 - h_2 + h_4 - h_5)\/3$],
  [$cyclic(3Z_2, 2)$],
  [$0$],

  real-form("EIII"),
  [$cyclic(Z_2, oo)$],
  [$Z_2 = (h_1 - h_2 + h_4 - h_5)\/3$],
  [$cyclic(3Z_2, oo)$],
  [$2Z_2$],

  real-form("EIV"),
  [${e}$],
  [],
  [${e}$],
  [$0$],
  real-form("EV"),
  [$cyclic(Z_1, 4)$],
  [$Z_1 = (h_1 + h_3 + h_7)\/2$],
  [$cyclic(2Z_1, 2)$],
  [$0$],

  real-form("EVI"),
  [$cyclic(Z_1, 2) times cyclic(Z_2, 2)$],
  [$Z_1 = (h_1 + h_3 + h_7)\/2$ \ $Z_2 = h_2$],
  [$cyclic(Z_2, 2)$],
  [$Z_1$],

  real-form("EVII"),
  [$cyclic(Z_1, oo)$],
  [$Z_1 = (h_1 + h_3 + h_7)\/2$],
  [$cyclic(2Z_1, oo)$],
  [$0$],

  real-form("EVIII"),
  [$cyclic(Z_1, 2)$],
  [$Z_1 = h_7$],
  [$cyclic(Z_1, 2)$],
  [$0$],
  real-form("EIX"),
  [$cyclic(Z_2, 2)$],
  [$Z_2 = h_1$],
  [$cyclic(Z_2, 2)$],
  [$0$],
  real-form("FI"),
  [$cyclic(Z, 2)$],
  [$Z = h_4$],
  [$cyclic(Z, 2)$],
  [$0$],
  real-form("FII"),
  [${e}$],
  [],
  [${e}$],
  [$0$],
  real-form("G"),
  [$cyclic(Z, 2)$],
  [$Z = h_2$],
  [$cyclic(Z, 2)$],
  [$0$],
)
